(function(){'use strict';
const $=id=>document.getElementById(id),{CardiacModel,MODES,LEADS,NO_P,anteriorST,inferiorST,clamp}=CardAIModel,S=CardAIScorm;
const content={
  normal:{title:'Normal sinüs ritmi',label:'NORMAL SİNÜS RİTMİ',lead:'II',summary:'Sinüs düğümünden başlayan düzenli uyarı önce atriyumlara, ardından ventriküllere yayılır. Elektriksel etkinliği, kasılma ve kanın pompalanması izler.',clues:['Her QRS öncesinde P','Düzenli R–R aralıkları','Dar QRS'],note:'<b>İzleme ipucu:</b> P dalgasını atriyal kasılma, QRS kompleksini kısa bir gecikmeyle ventriküler kasılma izler.',cards:[['EKG özellikleri','75/dk düzenli ritim. Her QRS öncesinde P dalgası ve sabit PR aralığı.'],['Dolaşıma etkisi','Atriyal kasılma doluşa katkı sağlar. Ventriküller düzenli aralıklarla kan pompalar.'],['Öğrenme odağı','EKG elektriksel etkinliği gösterir; kasılma ve kan akışı bu uyarıyı izler.']]},
  af:{title:'Atriyal fibrilasyon (AF)',label:'ATRİYAL FİBRİLASYON',lead:'II',summary:'Atriyumlardaki düzensiz elektriksel etkinlik organize kasılmayı ortadan kaldırır. AV düğümden ventriküllere düzensiz aralıklarla uyarı iletilir.',clues:['Belirgin P dalgası yok','R–R aralıkları düzensiz','İnce f dalgaları'],note:'<b>Ayırt edici bulgu:</b> P dalgalarının yokluğu ile düzensiz R–R aralıklarını birlikte değerlendir. Bu örnekte QRS dardır.',cards:[['EKG özellikleri','P dalgaları seçilemez. R–R aralıkları belirgin biçimde düzensizdir.'],['Dolaşıma etkisi','Atriyal kasılmanın doluşa katkısı kaybolur. Değişken doluş süreleri, atımların gücünü etkileyebilir.'],['Klinik önemi','Atriyal kan stazı ve tromboemboli riski artabilir. Klinik değerlendirme gerekir.']]},
  stemi:{title:'ST elevasyonlu MI örneği',label:'ST ELEVASYONLU MI • ÖRNEK',lead:'V3',summary:'Bu senaryoda ön duvar iskemisi, ST segmentinde yükselme ve sol ventrikülün etkilenen bölgesinde azalmış kasılma ile gösterilir. Ritim düzenli kalabilir.',clues:['J noktasında +0,30 mV','Yükselmiş ST segmenti','Ritim düzenli kalabilir'],note:'<b>Klinik ipucu:</b> ST yükselmesi tek başına MI tanısı koydurmaz. Komşu derivasyonlar, belirtiler ve klinik değerlendirme birlikte ele alınır.',cards:[['EKG özellikleri','V3 benzeri örnek izde ST segmenti yükselmiştir. P dalgaları ve düzenli ritim korunur.'],['Dolaşıma etkisi','Örnekte bir koroner dalın akışı kesilir. İskemik bölge daha az kasılır; kalbin pompalaması sürer.'],['Klinik önemi','İskemik belirtilerle birlikte ST yükselmesi acil değerlendirme gerektirir. Tek şerit tanı için yeterli değildir.']]},
  pvc:{title:'Ventriküler erken atım (PVC)',label:'VENTRİKÜLER ERKEN ATIM • PVC',lead:'II',summary:'Sinüs ritmi sırasında ventrikülden erken başlayan bir uyarı, geniş QRS kompleksi ve ardından kompansatuvar duraklama oluşturur. Erken atımın doluş süresi ve mekanik etkinliği azalabilir.',clues:['Beklenenden erken kompleks','Geniş QRS · yaklaşık 140 ms','Ardından kompansatuvar duraklama'],note:'<b>Ayırt edici bulgu:</b> Erken ve geniş QRS öncesinde ilişkili P dalgası görülmez; sonraki sinüs atımına kadar daha uzun bir R–R aralığı oluşur.',cards:[['EKG özellikleri','Aralıklı erken, geniş ve farklı morfolojili QRS kompleksleri; diskordan ST–T değişikliği.'],['Dolaşıma etkisi','Erken atımda ventrikül doluşu daha kısa olduğundan mekanik atım daha zayıf olabilir.'],['Klinik önemi','PVC tek başına etiyoloji veya risk düzeyi belirlemez; sıklık, belirtiler ve yapısal kalp hastalığıyla birlikte değerlendirilir.']]},
  svt:{title:'Düzenli dar kompleks SVT',label:'SUPRAVENTRİKÜLER TAŞİKARDİ • SVT',lead:'II',summary:'Ventriküllerin üzerinde başlayan hızlı ve düzenli ritim, AV düğüm–His-Purkinje sistemi üzerinden iletilerek dar QRS kompleksleri oluşturur. Bu örnekte hız yaklaşık 167/dk’dır.',clues:['Düzenli hızlı ritim','Dar QRS · 80 ms','P dalgaları seçilemeyebilir'],note:'<b>Ayırt edici bulgu:</b> Düzenli, hızlı ve dar QRS’li ritmi tanı; P dalgalarının görünümü SVT mekanizmasına göre değişebilir.',cards:[['EKG özellikleri','Yaklaşık 167/dk düzenli dar kompleks taşikardi. P dalgaları bu sentetik şeritte seçilemez.'],['Dolaşıma etkisi','Diyastol ve ventrikül doluş süresi kısalır; ejeksiyon döngüleri daha sık gerçekleşir.'],['Klinik önemi','SVT bir üst başlıktır; kesin mekanizma ve tedavi kararı 12 derivasyonlu EKG ile klinik değerlendirme gerektirir.']]},
  inferior:{title:'İnferior ST elevasyonlu MI',label:'İNFERİOR STEMI • ÖRNEK',lead:'aVF',summary:'İnferior duvar örneğinde ST yükselmesi II, III ve aVF derivasyonlarında; karşılıklı ST çökmesi ise I ve aVL’de belirginleşir. Ritim düzenli kalabilir.',clues:['II–III–aVF’de ST ↑','I–aVL’de karşılıklı ST ↓','Bölgesel kasılma azalması'],note:'<b>Derivasyon ipucu:</b> Birinci ve ikinci sütunda II ile aVF’yi seç; inferior komşu derivasyonlardaki eş yönlü değişimi birlikte değerlendir.',cards:[['EKG özellikleri','II, III ve aVF’de sentetik ST yükselmesi; I ve aVL’de karşılıklı ST çökmesi.'],['Dolaşıma etkisi','Koroner akım engeli ve bölgesel duvar hareketinde azalma şematik olarak gösterilir.'],['Klinik önemi','Akut koroner oklüzyon kuşkusunda semptomlar, seri 12 derivasyonlu EKG ve acil klinik değerlendirme gerekir.']]},
  vt:{title:'Monomorfik ventriküler taşikardi',label:'VENTRİKÜLER TAŞİKARDİ • VT',lead:'V1',summary:'Ventrikülden başlayan hızlı ritim, düzenli ve geniş QRS kompleksleri oluşturur. Kısa doluş süresi ile ventriküler eşzamanlılık kaybı mekanik etkinliği azaltır.',clues:['Düzenli geniş kompleks','Yaklaşık 158/dk','QRS yaklaşık 180 ms'],note:'<b>Güvenlik notu:</b> Geniş kompleks taşikardi klinikte aksi kanıtlanana kadar VT kabul edilerek acil değerlendirilir.',cards:[['EKG özellikleri','Hızlı, düzenli, geniş ve tek biçimli komplekslerden oluşan sentetik monomorfik VT.'],['Dolaşıma etkisi','Doluş süresi ve her atımın etkinliği azalır; dolaşım kararlılığı klinik duruma göre değişebilir.'],['Klinik önemi','Nabız ve hemodinamik durum acil yaklaşımı belirler; bu simülasyon tedavi kararı vermez.']]},
  vf:{title:'Ventriküler fibrilasyon',label:'VENTRİKÜLER FİBRİLASYON • VF',lead:'II',summary:'Kaotik ventriküler elektriksel etkinlikte organize QRS, etkili ventriküler kasılma ve dolaşım yoktur.',clues:['Organize QRS yok','Kaotik düzensiz dalgalar','Etkili ejeksiyon yok'],note:'<b>Acil ritim:</b> VF kardiyak arrest ritmidir; gerçek yaşamda hemen resüsitasyon ve defibrilasyon algoritması gerekir.',cards:[['EKG özellikleri','Değişken genlikli, kaotik etkinlik; düzenli R–R veya seçilebilir QRS bulunmaz.'],['Dolaşıma etkisi','Etkili ventriküler kasılma ve ileri kan akımı oluşmaz.'],['Klinik önemi','Bu görünüm eğitim amaçlıdır; gerçek VF acil müdahale gerektirir.']]},
  pat:{title:'Paroksismal atriyal taşikardi (PAT)',label:'PAROKSİSMAL ATRİYAL TAŞİKARDİ • PAT',lead:'II',summary:'Sinüs düğümü dışındaki atriyal bir odaktan başlayan düzenli taşikardide P dalgasının ekseni ve biçimi değişir; QRS genellikle dardır.',clues:['Düzenli atriyal taşikardi','Farklı morfolojili P','Dar QRS · 150/dk'],note:'<b>Ayırt edici bulgu:</b> Her QRS öncesindeki sinüs P’sinden farklı P dalgasını, düzenli hız ve dar QRS ile birlikte değerlendir.',cards:[['EKG özellikleri','Yaklaşık 150/dk; inferior derivasyonlarda ters gösterilen ektopik P dalgası ve dar QRS.'],['Dolaşıma etkisi','Atriyal kasılma sürer; yüksek hız nedeniyle ventrikül doluş süresi kısalır.'],['Klinik önemi','“PAT” burada fokal atriyal taşikardiyi öğretmek için kullanılır; başlangıç ve bitiş şeritte gösterilmez.']]},
  flutter:{title:'Atriyal flutter',label:'ATRİYAL FLUTTER • 2:1 İLETİM',lead:'II',summary:'Düzenli makro-reentran atriyal etkinlik yaklaşık 300/dk hızda F dalgaları oluşturur. Bu örnekte 2:1 AV iletimle ventrikül hızı 150/dk’dır.',clues:['Testere dişi F dalgaları','II–III–aVF’de belirgin','2:1 iletim · 150/dk'],note:'<b>Derivasyon ipucu:</b> Tipik flutter dalgaları inferior derivasyonlarda daha belirgindir; ikinci sütunda aVF’yi seç.',cards:[['EKG özellikleri','İzoelektrik hat olmadan süren F dalgaları ve her iki atriyal dalgadan birinin ventriküle iletildiği örnek.'],['Dolaşıma etkisi','Koordineli atriyal kasılma azalır; hızlı ventrikül yanıtı doluş süresini kısaltır.'],['Klinik önemi','İletim oranı değişebilir; bu şerit yalnızca sabit 2:1 örneğini gösterir.']]},
  sintach:{title:'Sinüs taşikardisi',label:'SİNÜS TAŞİKARDİSİ',lead:'II',summary:'Uyarı sinüs düğümünden çıkar; hız artmış olsa da her QRS öncesinde uygun P dalgası ve düzenli dar kompleksler korunur.',clues:['Yaklaşık 120/dk','Her QRS öncesinde P','Düzenli dar QRS'],note:'<b>Ayırt edici bulgu:</b> Hızlı ritimde sinüs P morfolojisinin ve P–QRS ilişkisinin korunması sinüs taşikardisini destekler.',cards:[['EKG özellikleri','Yaklaşık 120/dk düzenli ritim; her dar QRS öncesinde sinüs P dalgası.'],['Dolaşıma etkisi','Döngüler sıklaşır ve diyastolik doluş süresi kısalır; etkin ejeksiyon sürer.'],['Klinik önemi','Sinüs taşikardisi çoğunlukla fizyolojik veya ikincil bir yanıttır; neden klinik bağlamla araştırılır.']]},
  lbbb:{title:'Sol dal bloğu (LBBB)',label:'SOL DAL BLOĞU • LBBB',lead:'V6',summary:'Sol dal iletiminin gecikmesi QRS’yi genişletir. V1’de derin negatif kompleks; I, aVL, V5–V6’da geniş ve çentikli R morfolojisi belirginleşir.',clues:['QRS yaklaşık 160 ms','V1’de QS/rS','I–aVL–V5–V6’da geniş R'],note:'<b>Karşılaştırma:</b> Üçüncü sütunda V1 ve V6 arasında geçiş yap; terminal QRS yönü ve sekonder ST–T diskordansını karşılaştır.',cards:[['EKG özellikleri','Geniş QRS; sağ prekordiyallerde derin S, lateral derivasyonlarda geniş/çentikli R.'],['Dolaşıma etkisi','Sol ventrikül aktivasyonu gecikir; kasılma eşzamanlılığı azaltılmış olarak gösterilir.'],['Klinik önemi','Dal bloğu etiyoloji veya akut iskemi tanısını tek başına belirlemez; eski EKG ve klinik bağlam gerekir.']]},
  rbbb:{title:'Sağ dal bloğu (RBBB)',label:'SAĞ DAL BLOĞU • RBBB',lead:'V1',summary:'Sağ dal iletiminin gecikmesi QRS’yi genişletir. V1–V2’de terminal R′; I ve V6’da geniş terminal S dalgası belirginleşir.',clues:['QRS yaklaşık 140 ms','V1–V2’de rSR′','I–V6’da geniş terminal S'],note:'<b>Karşılaştırma:</b> Üçüncü sütunda V1 ve V6 arasında geçiş yaparak rSR′ ile geniş terminal S morfolojilerini karşılaştır.',cards:[['EKG özellikleri','V1–V2’de rsR′/rSR′, lateral derivasyonlarda geniş terminal S ve sekonder ST–T değişikliği.'],['Dolaşıma etkisi','Sağ ventrikül aktivasyonu gecikir; model hafif eşzamanlılık kaybı gösterir.'],['Klinik önemi','Tam RBBB için erişkinde QRS genişliği ve morfoloji birlikte değerlendirilir.']]}
};
const questions=window.PulseCurriculum.questions;
const LEAD_GROUPS=[['I','II','III'],['aVR','aVL','aVF'],['V1','V2','V3','V4','V5','V6']];
const defaults={version:5,mode:'normal',time:2,speed:1,uiScale:120,viewed:Object.fromEntries(MODES.map(m=>[m,0])),answers:questions.map(()=>null),score:null,assessed:false,passed:false,leads:['II','aVF','V3'],activeLead:0,lead:'II',afProfile:'controlled',compare:false,caliper:{a:{x:.06,y:.46},b:{x:.25,y:.46}},caseAnswers:Array(50).fill(null),caseCorrect:Array(50).fill(false),caseViewed:Array(50).fill(0),currentCase:0,quizPage:0,challengeCorrect:{rr:false,st:false},features:{fullscreen:0,focus:0,zoom:0,compare:0,caliper:0,guide:0,systematic:0,cases:0},checklist:{},activeView:'sim'};
const freshState=()=>JSON.parse(JSON.stringify(defaults));
let state=freshState(),saved=S.load();
if(saved){
  state.mode=MODES.includes(saved.mode)?saved.mode:'normal';state.time=clamp(Number(saved.time)||2,0,36000);state.speed=[.25,.5,1,2].includes(Number(saved.speed))?Number(saved.speed):1;state.uiScale=[90,100,110,120,130,140].includes(Number(saved.uiScale))?Number(saved.uiScale):120;
  for(const m of MODES)state.viewed[m]=clamp(Number(saved.viewed?.[m])||0,0,16);
  if(Array.isArray(saved.answers))state.answers=questions.map((q,i)=>Number.isInteger(saved.answers[i])&&saved.answers[i]>=0&&saved.answers[i]<q.options.length?saved.answers[i]:null);
  state.assessed=!!saved.assessed&&state.answers.every(x=>x!==null);state.score=Number.isFinite(saved.score)?clamp(saved.score,0,100):(state.assessed?Math.round(state.answers.filter((x,i)=>x===questions[i].correct).length/questions.length*100):null);state.passed=!!saved.passed;
  state.leads=LEAD_GROUPS.map((group,i)=>group.includes(saved.leads?.[i])?saved.leads[i]:defaults.leads[i]);state.activeLead=clamp(Number(saved.activeLead)||0,0,2);state.lead=state.leads[state.activeLead];state.afProfile=saved.afProfile==='rapid'?'rapid':'controlled';state.compare=!!saved.compare;
  if(saved.caliper?.a&&saved.caliper?.b)for(const h of ['a','b'])state.caliper[h]={x:clamp(Number(saved.caliper[h].x)||defaults.caliper[h].x,.02,.98),y:clamp(Number(saved.caliper[h].y)||defaults.caliper[h].y,.04,.96)};
  if(Array.isArray(saved.caseAnswers))state.caseAnswers=state.caseAnswers.map((_,i)=>Number.isInteger(saved.caseAnswers[i])?saved.caseAnswers[i]:null);if(Array.isArray(saved.caseCorrect))state.caseCorrect=state.caseCorrect.map((_,i)=>!!saved.caseCorrect[i]);if(Array.isArray(saved.caseViewed))state.caseViewed=state.caseViewed.map((_,i)=>clamp(Number(saved.caseViewed[i])||0,0,16));state.currentCase=clamp(Number(saved.currentCase)||0,0,49);state.quizPage=clamp(Number(saved.quizPage)||0,0,49);
  if(saved.challengeCorrect)for(const k of ['rr','st'])state.challengeCorrect[k]=!!saved.challengeCorrect[k];if(saved.features)for(const k in state.features)state.features[k]=clamp(Number(saved.features[k])||0,0,99);
  if(saved.checklist&&typeof saved.checklist==='object')state.checklist={...saved.checklist};state.activeView=['sim','case','quiz','educator'].includes(saved.activeView)?saved.activeView:'sim';
}
state.version=5;if(S.previousStatus==='passed')state.passed=true;
let models=Object.fromEntries(MODES.map(m=>[m,new CardiacModel(m,m==='af'?{afProfile:state.afProfile}:{})])),model=models[state.mode],playing=!matchMedia('(prefers-reduced-motion: reduce)').matches,simVisible=true,lastFrame=0,lastText=0,lastSave=0,lastProgress=0,frameCount=0,dirty=true;
let snapshot=model.snapshot(state.time),resumeAfterDialog=false,ended=false,ecgGeom={};
const canvas=$('ecgCanvas'),ctx=canvas.getContext('2d');let cw=700,ch=210;
function resize(){const r=canvas.getBoundingClientRect();cw=r.width;ch=r.height;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(cw*dpr));canvas.height=Math.max(1,Math.round(ch*dpr));ctx.setTransform(dpr,0,0,dpr,0,0);dirty=true;}
new ResizeObserver(resize).observe(canvas);
const NS='http://www.w3.org/2000/svg',particleGroup=$('particles');
const flows=[['body-return','venous','#8ad3ff',10],['ra-rv','fill','#9dddff',4],['rv-lung','eject','#9dddff',9],['lung','pulm','#cab3ef',5],['lung-la','venous','#ffabb2',8],['la-lv','fill','#ffb5b4',4],['lv-body','eject','#ffacb4',13],['body','systemic','#cea0d1',5]];
const flowObjects=flows.map(([id,type,color,count])=>{const path=$('flow-'+id),length=path.getTotalLength();const particles=Array.from({length:count},(_,i)=>{const c=document.createElementNS(NS,'circle');c.setAttribute('r',id.includes('-lv')||id.includes('-rv')?'3':'3.2');c.setAttribute('fill',color);particleGroup.append(c);return {node:c,offset:i/count};});return {id,type,path,length,particles};});
function cumulativeFlow(t,type){
  // Analytic integral guarantees deterministic particle positions after pause or seek.
  if(type==='venous'||type==='pulm'||type==='systemic')return t*.12;
  const index=model.indexAt(t), first=Math.max(0,index-2);
  // Older contributions are complete; only the latest three need phase evaluation.
  const fast=['svt','pat','flutter','sintach'].includes(state.mode),ventricularFast=state.mode==='vt',ejectStart=ventricularFast?.10:fast?.06:.09,ejectSpan=ventricularFast?.15:fast?.12:.21,fillStart=ventricularFast?.32:fast?.26:.43,flowStep=state.mode==='vf'?0:ventricularFast?.07:fast?.11:.15,fillStep=state.mode==='vf'?0:ventricularFast?.07:fast?.11:.20;
  let cycles=type==='eject'?(first?model.beats[first-1].prefix*flowStep:0):first*fillStep;
  for(let i=first;i<=index;i++){const b=model.beats[i],d=t-b.r;if(type==='eject')cycles+=clamp((d-ejectStart)/ejectSpan,0,1)*flowStep*b.strength;else {const next=model.beats[i+1]||{r:b.r+(fast?.36:.8)};const start=b.r+fillStart,end=next.r+(fast?.02:.035);cycles+=clamp((t-start)/Math.max(.025,end-start),0,1)*fillStep;}}
  return cycles;
}
function renderHeart(s){
  $('ra').style.transform=`scale(${1-.08*s.atrial})`;$('la').style.transform=`scale(${1-.08*s.atrial})`;
  if(['af','flutter'].includes(state.mode)){const tremor=Math.sin(s.time*(state.mode==='flutter'?31:39))*.006;$('ra').style.transform=`scale(${1+tremor},${1-tremor})`;$('la').style.transform=`scale(${1-tremor},${1+tremor})`;}
  const delayed=state.mode==='lbbb'||state.mode==='rbbb'?model.snapshot(Math.max(0,s.time-.06)):s,rightCavity=state.mode==='rbbb'?delayed.cavity:s.cavity,leftCavity=state.mode==='lbbb'?delayed.cavity:s.cavity;
  $('rv').style.transform=`scale(${1-.065*rightCavity*s.flow},${1-.045*rightCavity*s.flow})`;
  // Ischaemic territory is a separate segment: the whole ventricle does not stop.
  $('lv').style.transform=`scale(${1-.075*leftCavity*s.flow},${1-.05*leftCavity*s.flow})`;
  $('regionalWall').setAttribute('transform',`translate(${-s.contract*(['stemi','inferior'].includes(state.mode)?.6:5)} 0)`);
  $('regionalWall').style.opacity=['stemi','inferior'].includes(state.mode)?'.3':'1';
  const patch=$('ischemicRegion');if(patch){patch.style.opacity=['stemi','inferior'].includes(state.mode)?'.8':'0';patch.setAttribute('transform',`translate(${s.contract*.5} ${-s.contract*.5})`);}
  $('tricuspid').setAttribute('d',s.avOpen?'M178 303l29 17 32-17':'M178 303l29 0 32 0');$('mitral').setAttribute('d',s.avOpen?'M298 306l33 17 33-17':'M298 306l33 0 33 0');
  $('pulmonaryValve').setAttribute('d',s.eject?'M260 242l12-13 12 13':'M260 242l12 0 12 0');$('aorticValve').setAttribute('d',s.eject?'M297 244l13-13 12 13':'M297 244l13 0 12 0');
  $('atrialWire').style.opacity=NO_P.includes(state.mode)?'.07':String(s.atrial*.8+.1);$('ventWire').style.opacity=s.phase==='qrs'?(state.mode==='vf'?'.45':'.95'):'.14';
  $('saNode').style.opacity=NO_P.includes(state.mode)?'.12':String(.3+s.atrial*.7);$('avNode').style.opacity=s.phase==='qrs'?1:.35;
  $('afSignals').style.opacity=['af','flutter','vf'].includes(state.mode)?String(.45+.3*Math.sin(s.time*(state.mode==='flutter'?31:34))):0;
  if($('coronaryBlock')){const blockAt=$('coronaryFlow').getPointAtLength($('coronaryFlow').getTotalLength()*.28);$('coronaryBlock').setAttribute('transform',`translate(${blockAt.x} ${blockAt.y})`);$('coronaryBlock').style.opacity=['stemi','inferior'].includes(state.mode)?1:0;}
  if($('ischemiaLabel'))$('ischemiaLabel').style.opacity=['stemi','inferior'].includes(state.mode)?1:0;
  for(const f of flowObjects){const progress=cumulativeFlow(s.time,f.type);const open=f.type==='eject'?s.eject:f.type==='fill'?s.avOpen:true;for(const p of f.particles){const pos=((progress+p.offset)%1+1)%1;const pt=f.path.getPointAtLength(pos*f.length);p.node.setAttribute('cx',pt.x.toFixed(2));p.node.setAttribute('cy',pt.y.toFixed(2));p.node.style.opacity=open?'.92':'.20';}}
  // Coronary microcirculation has its own native path and is reduced in the ischaemic example.
  const cp=$('coronaryFlow');if(cp){const len=cp.getTotalLength();document.querySelectorAll('.coronary-particle').forEach((p,i)=>{const f=((s.time*.17+i/5)%1+1)%1;const pt=cp.getPointAtLength(f*len);p.setAttribute('cx',pt.x);p.setAttribute('cy',pt.y);p.style.opacity=['stemi','inferior'].includes(state.mode)&&f>.28?0:.85;});}
}
function renderECG(){if(!cw||!ch)return;ctx.clearRect(0,0,cw,ch);ctx.fillStyle='#fffafb';ctx.fillRect(0,0,cw,ch);
  const gap=6,columnWidth=(cw-gap*2)/3,windowSeconds=cw<700?2.2:2.8,pxPerSecond=(columnWidth-12)/windowSeconds,small=pxPerSecond*.04,base=ch*.64,mv=small*10,leftTime=state.time-(columnWidth-12)/pxPerSecond;
  const columns=state.leads.map((lead,index)=>({lead,index,offset:index*(columnWidth+gap),width:columnWidth,cursor:index*(columnWidth+gap)+columnWidth-8,leftTime,pxPerSecond,small,base,mv}));
  const active=columns[state.activeLead]||columns[0];ecgGeom={...active,columns,windowSeconds,cw,ch};
  for(const col of columns){const {lead,offset,width,cursor}=col;ctx.save();ctx.beginPath();ctx.rect(offset,0,width,ch);ctx.clip();
    ctx.fillStyle=col.index===state.activeLead?'#fff7f8':'#fffafb';ctx.fillRect(offset,0,width,ch);
    for(let i=Math.floor(leftTime/.04);i*.04<state.time+.5;i++){const x=offset+(i*.04-leftTime)*pxPerSecond;ctx.strokeStyle=i%5===0?'#ebbec7':'#f5dce0';ctx.lineWidth=i%5===0?.8:.45;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,ch);ctx.stroke();}
    for(let i=-Math.ceil(ch/small);i<Math.ceil(ch/small);i++){const y=base+i*small;if(y<0||y>ch)continue;ctx.strokeStyle=i%5===0?'#ebbec7':'#f5dce0';ctx.lineWidth=i%5===0?.8:.45;ctx.beginPath();ctx.moveTo(offset,y);ctx.lineTo(offset+width,y);ctx.stroke();}
    if(['stemi','inferior'].includes(state.mode)){const st=(state.mode==='stemi'?anteriorST:inferiorST)[lead]||0;ctx.fillStyle=st>=0?'#fbbd7638':'#69b7d52f';for(const b of model.between(leftTime-.5,state.time)){const x=offset+(b.r+.04-leftTime)*pxPerSecond,xx=offset+(Math.min(b.r+.19,state.time)-leftTime)*pxPerSecond;if(xx>x)ctx.fillRect(x,base-mv*(st+.07),xx-x,mv*Math.max(.08,Math.abs(st)+.08));}}
    function trace(source,color,widthLine,dash=[]){ctx.save();ctx.beginPath();ctx.rect(offset,0,width-4,ch);ctx.clip();ctx.strokeStyle=color;ctx.lineWidth=widthLine;ctx.lineJoin='round';ctx.setLineDash(dash);ctx.beginPath();for(let lx=0;lx<=width-8;lx+=.55){const t=leftTime+lx/pxPerSecond,y=base-source.signal(t,lead)*mv,x=offset+lx;if(lx===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);}ctx.stroke();ctx.restore();}
    if(state.compare&&state.mode!=='normal')trace(models.normal,'#35a4bd',1.2,[4,3]);trace(model,state.mode==='normal'?'#144f67':'#b92036',1.8);
    ctx.strokeStyle='#44687535';ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(offset,base);ctx.lineTo(offset+width,base);ctx.stroke();ctx.setLineDash([]);
    ctx.strokeStyle='#25657677';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(cursor,10);ctx.lineTo(cursor,ch-16);ctx.stroke();ctx.fillStyle='#136077';ctx.beginPath();ctx.arc(cursor,base-model.signal(state.time,lead)*mv,2.8,0,Math.PI*2);ctx.fill();
    ctx.font='bold '+Math.round(10*(state.uiScale||120)/100)+'px ui-monospace,monospace';ctx.fillStyle='#7b3a46';ctx.textAlign='left';ctx.fillText(lead,offset+7,15);ctx.restore();
    if(col.index<2){ctx.fillStyle='#cfdae0';ctx.fillRect(offset+width+gap/2-1,0,2,ch);}
  }
}
function timeFormat(t){const m=Math.floor(t/60),s=(t%60).toFixed(2).padStart(5,'0');return String(m).padStart(2,'0')+':'+s;}
function renderText(s){$('rateText').textContent=s.rate||'—';$('rrMetric').textContent=s.rr?s.rr+' ms':'Ölçülemez';$('qrsMetric').textContent=s.qrs?s.qrs+' ms':'Seçilemez';const pText={af:'P yok · f dalgaları',svt:'P seçilemiyor',vt:'P–QRS ilişkisi yok',vf:'Organize atriyal etkinlik yok',flutter:'F dalgaları · 300/dk',pat:'Ektopik P dalgası',sintach:'Sinüs P dalgası var'}[state.mode];$('pMetric').textContent=pText||(state.mode==='pvc'&&s.beat.isPVC?'PVC öncesi P yok':'P dalgası var');$('phaseTag').textContent={fill:'Doluş / Gevşeme',atrial:'Atriyal etkinlik',qrs:'Depolarizasyon',eject:'Ejeksiyon',t:'Repolarizasyon'}[s.phase];$('mechanicText').textContent=s.mechanical;$('valveText').textContent=state.mode==='vf'?'İleri akım yok':s.eject?'Çıkış kapakları açık':s.avOpen?'AV kapaklar açık':'Tüm kapaklar kapalı';$('eventTitle').textContent=s.electrical;$('eventText').textContent=s.text;$('eventIcon').textContent=state.mode==='vf'?'≈':{atrial:'P',qrs:s.beat.isPVC?'V':'R',eject:'↗',t:'T',fill:'↘'}[s.phase];document.querySelectorAll('[data-phase]').forEach(b=>b.classList.toggle('active',b.dataset.phase===s.phase));$('timeText').textContent=timeFormat(state.time);const t=$('timeline');t.max=String(Math.max(30,Math.ceil(state.time/30)*30));t.value=state.time;window.dispatchEvent(new CustomEvent('cardai:tick',{detail:{snapshot:s}}));}
function progress(){let complete=0;for(const m of MODES){const yes=state.viewed[m]>=16;$('viewed-'+m).textContent=yes?'✓':'○';$('viewed-'+m).classList.toggle('done',yes);if(yes)complete++;}const sum=MODES.reduce((n,m)=>n+Math.min(16,state.viewed[m]),0),simComplete=complete===MODES.length;$('progressBar').style.width=(sum/(MODES.length*16)*100)+'%';$('progressText').textContent=complete+' / '+MODES.length+' ritim · 16 sn';if(state.assessed&&state.score>=80&&simComplete)state.passed=true;$('quizCount').textContent=state.answers.filter(x=>x!==null).length+'/'+questions.length;$('caseCount').textContent=state.caseAnswers.filter(x=>x!==null).length+'/50';for(const id of ['caseTab','quizTab']){$(id).classList.toggle('locked',!simComplete);$(id).dataset.locked=String(!simComplete);}return complete;}
function statusText(ok){if(ended)return;const text=S.detected?(S.isLMS?(ok?'İlerleme LMS’ye kaydedildi':'LMS kaydı başarısız; yeniden denenecek'):'LMS bağlantısı başlatılamadı'):(ok?'İlerleme bu tarayıcıya kaydedildi':'Tarayıcı kaydı kullanılamıyor');$('saveStatus').textContent=text;}
function persist(){progress();statusText(S.save(state));lastSave=performance.now();}
function markFeature(name,save=true){if(Object.hasOwn(state.features,name)){state.features[name]=Math.min(99,state.features[name]+1);if(save)persist();}}
function setPlaying(v){playing=!!v&&!ended;$('playBtn').innerHTML=playing?'Ⅱ <span>Duraklat</span>':'▶ <span>Oynat</span>';$('playBtn').setAttribute('aria-label',playing?'Simülasyonu duraklat':'Simülasyonu oynat');$('liveBadge').innerHTML=playing?'<i></i> CANLI · Ⅱ DURAKLAT':'▶ OYNAT';$('liveBadge').setAttribute('aria-label',playing?'Simülasyonu duraklat':'Simülasyonu oynat');dirty=true;}
const MODE_LEADS={normal:['II','aVF','V3'],af:['II','aVF','V1'],stemi:['II','aVL','V3'],pvc:['II','aVR','V1'],svt:['II','aVF','V1'],inferior:['II','aVF','V1'],vt:['II','aVR','V1'],vf:['II','aVF','V1'],pat:['II','aVF','V1'],flutter:['II','aVF','V1'],sintach:['II','aVF','V3'],lbbb:['I','aVL','V6'],rbbb:['I','aVR','V1']};
function setMode(m,resetTime=true){if(!MODES.includes(m))return;state.mode=m;if(resetTime){state.time=2;state.leads=[...MODE_LEADS[m]];state.activeLead=0;state.lead=state.leads[0];}model=models[m];applyMode();document.querySelector(`.rhythm-tab[data-mode="${m}"]`)?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'});persist();}
function setLead(column,lead){if(typeof lead==='undefined'){lead=column;column=LEAD_GROUPS.findIndex(g=>g.includes(lead));}column=Number(column);if(!LEAD_GROUPS[column]?.includes(lead))return;state.leads[column]=lead;state.activeLead=column;state.lead=lead;applyMode();persist();}
function setAfProfile(profile){state.afProfile=profile==='rapid'?'rapid':'controlled';models.af=new CardiacModel('af',{afProfile:state.afProfile});if(state.mode==='af')model=models.af;state.time=2;applyMode();persist();}
function applyMode(){const d=content[state.mode];state.lead=state.leads[state.activeLead];document.body.dataset.mode=state.mode;document.querySelectorAll('[data-mode]').forEach(b=>{const yes=b.dataset.mode===state.mode;b.classList.toggle('selected',yes);b.setAttribute('aria-pressed',yes);});$('explanationTitle').textContent=d.title;$('summaryText').textContent=d.summary;$('traceLabel').textContent=d.label;document.querySelectorAll('.lead-select').forEach((select,i)=>{select.value=state.leads[i];select.closest('.lead-choice').classList.toggle('active',i===state.activeLead);});$('afProfile').hidden=state.mode!=='af';$('afProfile').value=state.afProfile;const clues=[...d.clues];if(['stemi','inferior'].includes(state.mode)){const map=state.mode==='stemi'?anteriorST:inferiorST,lead=state.leads[state.activeLead],st=map[lead]||0;clues[0]=lead+' J noktası '+(st>=0?'+':'')+st.toFixed(2).replace('.',',')+' mV';}$('clues').innerHTML=clues.map(x=>'<span>'+x+'</span>').join('');$('teachingNote').innerHTML=d.note;$('detailCards').innerHTML=d.cards.map((x,i)=>'<article><h3><span>'+['∿','♡','+'][i]+'</span> '+x[0]+'</h3><p>'+x[1]+'</p></article>').join('');const ab=document.querySelector('[data-phase="atrial"]'),noDiscreteP=NO_P.includes(state.mode);ab.textContent=state.mode==='af'?'f / Sürekli':state.mode==='flutter'?'F / Sürekli':noDiscreteP?'P seçilemiyor':'P / Atriyum';ab.disabled=noDiscreteP;ab.title=noDiscreteP?'Bu örnekte ayrı bir P olayı seçilemez.':'';$('speed').value=state.speed;$('compareBtn').disabled=state.mode==='normal'||state.mode==='vf';if(state.mode==='normal'||state.mode==='vf'){state.compare=false;$('compareBtn').classList.remove('active');$('compareBtn').setAttribute('aria-pressed','false');$('compareKey').hidden=true;}$('measurementOutput').textContent='Bir şeride tıklayarak derivasyonu etkinleştir; dalgayı seçerek ilgili faza git.';$('selectedMetric').textContent='—';dirty=true;draw();window.dispatchEvent(new CustomEvent('cardai:mode',{detail:{mode:state.mode}}));}
function draw(){snapshot=model.snapshot(state.time);renderHeart(snapshot);renderECG();renderText(snapshot);dirty=false;}
function seek(t){setPlaying(false);state.time=clamp(t,0,36000);draw();persist();}
function showView(view='sim'){if(!['sim','case','quiz','educator'].includes(view))view='sim';let lockMessage='';if(['case','quiz'].includes(view)&&!MODES.every(m=>state.viewed[m]>=16)){const first=MODES.find(m=>state.viewed[m]<16);view='sim';if(first&&first!==state.mode)setMode(first);lockMessage='Vakalar ve değerlendirme için 13 simülasyon varyantının her birini en az 16 saniye izle.';}state.activeView=view;simVisible=view==='sim';for(const v of ['sim','case','quiz','educator']){$(v+'View').hidden=v!==view;const tab=$(v+'Tab');if(tab){tab.classList.toggle('active',v===view);tab.setAttribute('aria-pressed',String(v===view));}}if(view!=='sim')setPlaying(false);else{requestAnimationFrame(resize);dirty=true;}if(view==='quiz'){$('quizTitle').setAttribute('tabindex','-1');$('quizTitle').focus();}persist();if(lockMessage)$('saveStatus').textContent=lockMessage;window.dispatchEvent(new CustomEvent('cardai:view',{detail:{view}}));}
function resetAll(){const fresh=freshState();for(const k of Object.keys(state))delete state[k];Object.assign(state,fresh);models=Object.fromEntries(MODES.map(m=>[m,new CardiacModel(m,m==='af'?{afProfile:'controlled'}:{})]));model=models.normal;S.clearLocal();renderQuiz();applyMode();setPlaying(false);showView('sim');progress();persist();window.dispatchEvent(new Event('cardai:reset'));}
function frame(now){const elapsed=lastFrame?Math.max((now-lastFrame)/1000,0):0,dt=Math.min(elapsed,.1);lastFrame=now;if(playing&&simVisible&&!document.hidden&&!ended){state.time+=dt*state.speed;state.viewed[state.mode]=Math.min(16,Math.round((state.viewed[state.mode]+Math.min(elapsed,1))*1000)/1000);dirty=true;}if(dirty&&simVisible){snapshot=model.snapshot(state.time);renderHeart(snapshot);renderECG();if(now-lastText>90||!playing){renderText(snapshot);lastText=now;}dirty=false;frameCount++;}if(now-lastProgress>600){progress();lastProgress=now;}if(now-lastSave>10000&&!ended)persist();requestAnimationFrame(frame);}
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));
document.querySelectorAll('.lead-select').forEach((select,i)=>select.addEventListener('change',()=>setLead(i,select.value)));
$('playBtn').addEventListener('click',()=>setPlaying(!playing));$('liveBadge').addEventListener('click',()=>setPlaying(!playing));$('stepBtn').addEventListener('click',()=>seek(model.nextEvent(state.time)));$('resetBtn').addEventListener('click',()=>{state.time=0;draw();persist();});$('speed').addEventListener('change',()=>{state.speed=Number($('speed').value);persist();});$('timeline').addEventListener('input',()=>seek(Number($('timeline').value)));
document.querySelectorAll('[data-phase]').forEach(b=>b.addEventListener('click',()=>seek(model.phaseTime(state.time,b.dataset.phase))));
$('labelsToggle').addEventListener('change',()=>{$('anatomyLabels').style.display=$('labelsToggle').checked?'':'none';});$('electricToggle').addEventListener('change',()=>{$('conduction').style.display=$('electricToggle').checked?'':'none';});
function openInfo(){resumeAfterDialog=playing;setPlaying(false);$('infoDialog').showModal();}$('helpBtn').addEventListener('click',openInfo);$('sourceBtn').addEventListener('click',openInfo);$('closeInfo').addEventListener('click',()=>$('infoDialog').close());$('infoDialog').addEventListener('close',()=>setPlaying(resumeAfterDialog));
for(const v of ['sim','case','quiz','educator']){const tab=$(v+'Tab');if(tab)tab.addEventListener('click',()=>showView(v));}document.querySelectorAll('.back-sim').forEach(b=>b.addEventListener('click',()=>showView('sim')));
function renderQuiz(){const i=state.quizPage,q=questions[i],form=$('quizForm');form.innerHTML=`<fieldset class="question"><legend><span>${String(i+1).padStart(2,'0')} / 50</span>${q.text}</legend>${q.options.map((o,j)=>`<label id="answer-${i}-${j}"><input type="radio" name="q${i}" value="${j}" ${state.answers[i]===j?'checked':''}>${o}</label>`).join('')}<div class="feedback" id="feedback-${i}" ${state.assessed?'':'hidden'}>${state.assessed?q.feedback:''}</div></fieldset>`;form.onchange=e=>{state.answers[i]=Number(e.target.value);progress();persist();};$('quizPage').textContent=(i+1)+' / 50';$('quizPrev').disabled=i===0;$('quizNext').disabled=i===49;if(state.assessed){for(let j=0;j<q.options.length;j++){const el=$('answer-'+i+'-'+j);el.classList.toggle('correct',j===q.correct);el.classList.toggle('wrong',state.answers[i]===j&&j!==q.correct);el.querySelector('input').disabled=true;}}}
function grade(write=true){if(state.answers.some(x=>x===null)){$('quizResult').textContent=`${state.answers.filter(x=>x!==null).length}/50 soru yanıtlandı. Lütfen tüm soruları tamamla.`;return;}state.assessed=true;const correct=questions.reduce((n,q,i)=>n+(state.answers[i]===q.correct?1:0),0),attemptScore=Math.round(correct/questions.length*100);state.score=Math.max(state.score??0,attemptScore);progress();if(write)questions.forEach((q,i)=>S.interaction(i,state.answers[i],state.answers[i]===q.correct));$('checkBtn').hidden=true;$('retryBtn').hidden=false;$('quizResult').textContent=`${correct}/50 doğru · Bu deneme: ${attemptScore}/100 · En iyi puan: ${state.score}/100. `+(state.passed?'Modül başarıyla tamamlandı.':'Başarı için en az 40 doğru yanıt gerekir.');renderQuiz();if(write)persist();}
$('quizPrev').addEventListener('click',()=>{state.quizPage=Math.max(0,state.quizPage-1);renderQuiz();persist();});$('quizNext').addEventListener('click',()=>{state.quizPage=Math.min(49,state.quizPage+1);renderQuiz();persist();});$('checkBtn').addEventListener('click',()=>grade());$('retryBtn').addEventListener('click',()=>{state.answers=questions.map(()=>null);state.assessed=false;state.quizPage=0;$('checkBtn').hidden=false;$('retryBtn').hidden=true;$('quizResult').textContent='';renderQuiz();persist();});
$('finishBtn').addEventListener('click',()=>{setPlaying(false);progress();const ok=S.finish(state);if(S.ended){ended=true;$('finishBtn').disabled=true;$('continueBtn').textContent='Pencereyi kapat';$('finishTitle').textContent=ok?'Oturum kaydedildi':'Kayıt durumu doğrulanamadı';$('finishMessage').textContent=(state.passed?'Modül başarıyla tamamlandı. ':'İlerlemen saklandı; LMS’den yeniden açarak devam edebilirsin. ')+(ok?'Bu pencereyi kapatabilirsin.':'LMS raporunda kaydı kontrol et.');$('saveStatus').textContent='LMS oturumu sonlandırıldı';document.querySelectorAll('button,input,select').forEach(e=>e.disabled=true);}else{$('finishTitle').textContent=ok?'İlerleme kaydedildi':'İlerleme kaydedilemedi';$('finishMessage').textContent=S.isLMS?'LMS oturumu sonlandırılamadı. Yeniden kaydetmeyi deneyebilirsin.':ok?'İlerlemen bu tarayıcıda saklandı. SCORM paketini bir LMS içinde açtığında sonuçların LMS’ye kaydedilir.':'Bu ortam kalıcı kayda izin vermiyor. Simülasyonu kullanmaya devam edebilirsin.';}$('finishDialog').showModal();});$('closeFinish').addEventListener('click',()=>$('finishDialog').close());$('continueBtn').addEventListener('click',()=>$('finishDialog').close());
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!['INPUT','SELECT','BUTTON','TEXTAREA'].includes(e.target.tagName)&&simVisible&&!document.querySelector('dialog[open]')){e.preventDefault();setPlaying(!playing);}});
document.addEventListener('visibilitychange',()=>{lastFrame=0;if(document.hidden&&!ended)persist();});window.addEventListener('pagehide',e=>{if(!ended){if(e.persisted)persist();else S.finish(state);}});window.addEventListener('pageshow',e=>{if(e.persisted&&S.ended)location.reload();});
window.CardAIController={state,content,questions,get model(){return model;},get models(){return models;},get snapshot(){return snapshot;},get geom(){return {...ecgGeom};},get playing(){return playing;},setMode,setLead,setAfProfile,setPlaying,seek,draw,resize,persist,progress,showView,markFeature,resetAll};
window.CardAIDiagnostics={get state(){return JSON.parse(JSON.stringify(state));},get snapshot(){return {...snapshot};},get playing(){return playing;},get frameCount(){return frameCount;},get geom(){return {...ecgGeom};}};
renderQuiz();applyMode();setPlaying(playing);progress();showView(state.activeView);requestAnimationFrame(frame);
})();
