(function(){'use strict';
const $=id=>document.getElementById(id),{CardiacModel,MODES,LEADS,NO_P,anteriorST,inferiorST,clamp}=CardAIModel,S=CardAIScorm,COUNT=window.PulseState.COUNT;
const content={
  normal:{title:'Normal sinüs ritmi',label:'NORMAL SİNÜS RİTMİ',lead:'II',summary:'Sinüs düğümünden başlayan düzenli uyarı önce atriyumlara, ardından ventriküllere yayılır. Elektriksel etkinliği, kasılma ve kanın pompalanması izler.',clues:['Her QRS öncesinde P','Düzenli R–R aralıkları','Dar QRS'],note:'<b>İzleme ipucu:</b> P dalgasını atriyal kasılma, QRS kompleksini kısa bir gecikmeyle ventriküler kasılma izler.',cards:[['EKG özellikleri','75/dk düzenli ritim. Her QRS öncesinde P dalgası ve sabit PR aralığı.'],['Dolaşıma etkisi','Atriyal kasılma doluşa katkı sağlar. Ventriküller düzenli aralıklarla kan pompalar.'],['Öğrenme odağı','EKG elektriksel etkinliği gösterir; kasılma ve kan akışı bu uyarıyı izler.']]},
  af:{title:'Atriyal fibrilasyon (AF)',label:'ATRİYAL FİBRİLASYON',lead:'II',summary:'Atriyumlardaki düzensiz elektriksel etkinlik organize kasılmayı ortadan kaldırır. AV düğümden ventriküllere düzensiz aralıklarla uyarı iletilir.',clues:['Belirgin P dalgası yok','R–R aralıkları düzensiz','İnce f dalgaları'],note:'<b>Ayırt edici bulgu:</b> P dalgalarının yokluğu ile düzensiz R–R aralıklarını birlikte değerlendir. Bu örnekte QRS dardır.',cards:[['EKG özellikleri','P dalgaları seçilemez. R–R aralıkları belirgin biçimde düzensizdir.'],['Dolaşıma etkisi','Atriyal kasılmanın doluşa katkısı kaybolur. Değişken doluş süreleri, atımların gücünü etkileyebilir.'],['Klinik önemi','Atriyal kan stazı ve tromboemboli riski artabilir. Klinik değerlendirme gerekir.']]},
  stemi:{title:'ST elevasyonlu MI örneği',label:'ST ELEVASYONLU MI • ÖRNEK',lead:'V3',summary:'Bu senaryoda ön duvar iskemisi, ST segmentinde yükselme ve sol ventrikülün etkilenen bölgesinde azalmış kasılma ile gösterilir. Ritim düzenli kalabilir.',clues:['J+20 ms’de +0,32 mV','Yükselmiş ST segmenti','Ritim düzenli kalabilir'],note:'<b>Klinik ipucu:</b> ST yükselmesi tek başına MI tanısı koydurmaz. Komşu derivasyonlar, belirtiler ve klinik değerlendirme birlikte ele alınır.',cards:[['EKG özellikleri','V3 benzeri örnek izde ST segmenti yükselmiştir. P dalgaları ve düzenli ritim korunur.'],['Dolaşıma etkisi','Örnekte bir koroner dalın akışı kesilir. İskemik bölge daha az kasılır; kalbin pompalaması sürer.'],['Klinik önemi','İskemik belirtilerle birlikte ST yükselmesi acil değerlendirme gerektirir. Tek şerit tanı için yeterli değildir.']]},
  pvc:{title:'Ventriküler erken atım (PVC)',label:'VENTRİKÜLER ERKEN ATIM • PVC',lead:'II',summary:'Sinüs ritmi sırasında ventrikülden erken başlayan bir uyarı, geniş QRS kompleksi ve ardından kompansatuvar duraklama oluşturur. Erken atımın doluş süresi ve mekanik etkinliği azalabilir.',clues:['Beklenenden erken kompleks','Geniş QRS · yaklaşık 140 ms','Ardından kompansatuvar duraklama'],note:'<b>Ayırt edici bulgu:</b> Erken ve geniş QRS öncesinde ilişkili P dalgası görülmez; sonraki sinüs atımına kadar daha uzun bir R–R aralığı oluşur.',cards:[['EKG özellikleri','Aralıklı erken, geniş ve farklı morfolojili QRS kompleksleri; diskordan ST–T değişikliği.'],['Dolaşıma etkisi','Erken atımda ventrikül doluşu daha kısa olduğundan mekanik atım daha zayıf olabilir.'],['Klinik önemi','PVC tek başına etiyoloji veya risk düzeyi belirlemez; sıklık, belirtiler ve yapısal kalp hastalığıyla birlikte değerlendirilir.']]},
  svt:{title:'Düzenli dar kompleks SVT',label:'SUPRAVENTRİKÜLER TAŞİKARDİ • SVT',lead:'II',summary:'Ventriküllerin üzerinde başlayan hızlı ve düzenli ritim, AV düğüm–His-Purkinje sistemi üzerinden iletilerek dar QRS kompleksleri oluşturur. Bu örnekte hız yaklaşık 167/dk’dır.',clues:['Düzenli hızlı ritim','Dar QRS · 80 ms','P dalgaları seçilemeyebilir'],note:'<b>Ayırt edici bulgu:</b> Düzenli, hızlı ve dar QRS’li ritmi tanı; P dalgalarının görünümü SVT mekanizmasına göre değişebilir.',cards:[['EKG özellikleri','Yaklaşık 167/dk düzenli dar kompleks taşikardi. P dalgaları bu sentetik şeritte seçilemez.'],['Dolaşıma etkisi','Diyastol ve ventrikül doluş süresi kısalır; ejeksiyon döngüleri daha sık gerçekleşir.'],['Klinik önemi','SVT bir üst başlıktır; kesin mekanizma ve tedavi kararı 12 derivasyonlu EKG ile klinik değerlendirme gerektirir.']]},
  inferior:{title:'İnferior ST elevasyonlu MI',label:'İNFERİOR STEMI • ÖRNEK',lead:'aVF',summary:'İnferior duvar örneğinde ST yükselmesi II, III ve aVF derivasyonlarında; karşılıklı ST çökmesi ise I ve aVL’de belirginleşir. Ritim düzenli kalabilir.',clues:['II–III–aVF’de ST ↑','I–aVL’de karşılıklı ST ↓','Bölgesel kasılma azalması'],note:'<b>Derivasyon ipucu:</b> Ekstremite ve artırılmış gruplarda II ile aVF’yi seç; inferior komşu derivasyonlardaki eş yönlü değişimi birlikte değerlendir.',cards:[['EKG özellikleri','II, III ve aVF’de sentetik ST yükselmesi; I ve aVL’de karşılıklı ST çökmesi.'],['Dolaşıma etkisi','Koroner akım engeli ve bölgesel duvar hareketinde azalma şematik olarak gösterilir.'],['Klinik önemi','Akut koroner oklüzyon kuşkusunda semptomlar, seri 12 derivasyonlu EKG ve acil klinik değerlendirme gerekir.']]},
  vt:{title:'Monomorfik ventriküler taşikardi',label:'VENTRİKÜLER TAŞİKARDİ • VT',lead:'V1',summary:'Ventrikülden başlayan hızlı ritim, düzenli ve geniş QRS kompleksleri oluşturur. Kısa doluş süresi ile ventriküler eşzamanlılık kaybı mekanik etkinliği azaltır.',clues:['Düzenli geniş kompleks','Yaklaşık 158/dk','QRS yaklaşık 180 ms'],note:'<b>Güvenlik notu:</b> Geniş kompleks taşikardi klinikte aksi kanıtlanana kadar VT kabul edilerek acil değerlendirilir.',cards:[['EKG özellikleri','Hızlı, düzenli, geniş ve tek biçimli komplekslerden oluşan sentetik monomorfik VT.'],['Dolaşıma etkisi','Doluş süresi ve her atımın etkinliği azalır; dolaşım kararlılığı klinik duruma göre değişebilir.'],['Klinik önemi','Nabız ve hemodinamik durum acil yaklaşımı belirler; bu simülasyon tedavi kararı vermez.']]},
  vf:{title:'Ventriküler fibrilasyon',label:'VENTRİKÜLER FİBRİLASYON • VF',lead:'II',summary:'Kaotik ventriküler elektriksel etkinlikte organize QRS, etkili ventriküler kasılma ve dolaşım yoktur.',clues:['Organize QRS yok','Kaotik düzensiz dalgalar','Etkili ejeksiyon yok'],note:'<b>Acil ritim:</b> VF kardiyak arrest ritmidir; gerçek yaşamda hemen resüsitasyon ve defibrilasyon algoritması gerekir.',cards:[['EKG özellikleri','Değişken genlikli, kaotik etkinlik; düzenli R–R veya seçilebilir QRS bulunmaz.'],['Dolaşıma etkisi','Etkili ventriküler kasılma ve ileri kan akımı oluşmaz.'],['Klinik önemi','Bu görünüm eğitim amaçlıdır; gerçek VF acil müdahale gerektirir.']]},
  pat:{title:'Paroksismal atriyal taşikardi (PAT)',label:'PAROKSİSMAL ATRİYAL TAŞİKARDİ • PAT',lead:'II',summary:'Sinüs düğümü dışındaki atriyal bir odaktan başlayan düzenli taşikardide P dalgasının ekseni ve biçimi değişir; QRS genellikle dardır.',clues:['Düzenli atriyal taşikardi','Farklı morfolojili P','Dar QRS · 150/dk'],note:'<b>Ayırt edici bulgu:</b> Her QRS öncesindeki sinüs P’sinden farklı P dalgasını, düzenli hız ve dar QRS ile birlikte değerlendir.',cards:[['EKG özellikleri','Yaklaşık 150/dk; inferior derivasyonlarda ters gösterilen ektopik P dalgası ve dar QRS.'],['Dolaşıma etkisi','Atriyal kasılma sürer; yüksek hız nedeniyle ventrikül doluş süresi kısalır.'],['Klinik önemi','“PAT” burada fokal atriyal taşikardiyi öğretmek için kullanılır; başlangıç ve bitiş şeritte gösterilmez.']]},
  flutter:{title:'Atriyal flutter',label:'ATRİYAL FLUTTER • 2:1 İLETİM',lead:'II',summary:'Düzenli makro-reentran atriyal etkinlik yaklaşık 300/dk hızda F dalgaları oluşturur. Bu örnekte 2:1 AV iletimle ventrikül hızı 150/dk’dır.',clues:['Testere dişi F dalgaları','II–III–aVF’de belirgin','2:1 iletim · 150/dk'],note:'<b>Derivasyon ipucu:</b> Tipik flutter dalgaları inferior derivasyonlarda daha belirgindir; artırılmış grupta aVF’yi seç.',cards:[['EKG özellikleri','İzoelektrik hat olmadan süren F dalgaları ve her iki atriyal dalgadan birinin ventriküle iletildiği örnek.'],['Dolaşıma etkisi','Koordineli atriyal kasılma azalır; hızlı ventrikül yanıtı doluş süresini kısaltır.'],['Klinik önemi','İletim oranı değişebilir; bu şerit yalnızca sabit 2:1 örneğini gösterir.']]},
  sintach:{title:'Sinüs taşikardisi',label:'SİNÜS TAŞİKARDİSİ',lead:'II',summary:'Uyarı sinüs düğümünden çıkar; hız artmış olsa da her QRS öncesinde uygun P dalgası ve düzenli dar kompleksler korunur.',clues:['Yaklaşık 120/dk','Her QRS öncesinde P','Düzenli dar QRS'],note:'<b>Ayırt edici bulgu:</b> Hızlı ritimde sinüs P morfolojisinin ve P–QRS ilişkisinin korunması sinüs taşikardisini destekler.',cards:[['EKG özellikleri','Yaklaşık 120/dk düzenli ritim; her dar QRS öncesinde sinüs P dalgası.'],['Dolaşıma etkisi','Döngüler sıklaşır ve diyastolik doluş süresi kısalır; etkin ejeksiyon sürer.'],['Klinik önemi','Sinüs taşikardisi çoğunlukla fizyolojik veya ikincil bir yanıttır; neden klinik bağlamla araştırılır.']]},
  lbbb:{title:'Sol dal bloğu (LBBB)',label:'SOL DAL BLOĞU • LBBB',lead:'V6',summary:'Sol dal iletiminin gecikmesi QRS’yi genişletir. V1’de derin negatif kompleks; I, aVL, V5–V6’da geniş ve çentikli R morfolojisi belirginleşir.',clues:['QRS yaklaşık 160 ms','V1’de QS/rS','I–aVL–V5–V6’da geniş R'],note:'<b>Karşılaştırma:</b> Prekordiyal grupta V1 ve V6 arasında geçiş yap; terminal QRS yönü ve sekonder ST–T diskordansını karşılaştır.',cards:[['EKG özellikleri','Geniş QRS; sağ prekordiyallerde derin S, lateral derivasyonlarda geniş/çentikli R.'],['Dolaşıma etkisi','Sol ventrikül aktivasyonu gecikir; kasılma eşzamanlılığı azaltılmış olarak gösterilir.'],['Klinik önemi','Dal bloğu etiyoloji veya akut iskemi tanısını tek başına belirlemez; eski EKG ve klinik bağlam gerekir.']]},
  rbbb:{title:'Sağ dal bloğu (RBBB)',label:'SAĞ DAL BLOĞU • RBBB',lead:'V1',summary:'Sağ dal iletiminin gecikmesi QRS’yi genişletir. V1–V2’de terminal R′; I ve V6’da geniş terminal S dalgası belirginleşir.',clues:['QRS yaklaşık 140 ms','V1–V2’de rSR′','I–V6’da geniş terminal S'],note:'<b>Karşılaştırma:</b> Prekordiyal grupta V1 ve V6 arasında geçiş yaparak rSR′ ile geniş terminal S morfolojilerini karşılaştır.',cards:[['EKG özellikleri','V1–V2’de rsR′/rSR′, lateral derivasyonlarda geniş terminal S ve sekonder ST–T değişikliği.'],['Dolaşıma etkisi','Sağ ventrikül aktivasyonu gecikir; model hafif eşzamanlılık kaybı gösterir.'],['Klinik önemi','Tam RBBB için erişkinde QRS genişliği ve morfoloji birlikte değerlendirilir.']]}
};
const questions=window.PulseCurriculum.questions;
const LEAD_GROUPS=[['I','II','III'],['aVR','aVL','aVF'],['V1','V2','V3','V4','V5','V6']];
const freshState=()=>PulseState.blank();
let state=PulseState.decode(S.load());
PulseState.derive(state);
let models=Object.fromEntries(MODES.map(m=>[m,new CardiacModel(m,m==='af'?{afProfile:state.afProfile}:{})])),model=models[state.mode],playing=false,simVisible=true,lastFrame=0,lastText=0,lastSave=0,lastProgress=0,frameCount=0,dirty=true;
let snapshot=model.snapshot(state.time),resumeAfterDialog=false,ended=false,ecgGeom={};
let observationIntent=null,lastEligible=false,lastLearning=false;
function revokeObservation(){observationIntent=null;lastEligible=false;lastFrame=0;}
function onsite(surface=$('workspace')){if(!surface)return false;const r=surface.getBoundingClientRect();return r.width>0&&r.height>0&&r.bottom>0&&r.right>0&&r.top<innerHeight&&r.left<innerWidth;}
function baseEligible(){return !ended&&!document.hidden&&!document.querySelector('dialog[open]')&&!document.body.classList.contains('landing-open')&&!$('appRoot').hidden&&onsite($(state.activeView+'View')||$('simView'));}
function observeEligible(){return baseEligible()&&playing&&simVisible&&state.activeView==='sim'&&onsite()&&observationIntent===state.mode;}
function learningEligible(){return baseEligible()&&(['case','quiz'].includes(state.activeView)||simVisible&&playing);}
function selectMode(m,event){if(!event?.isTrusted||!(event.type==='click'||event.type==='keydown'&&(['Enter',' ','[',']','1','2','3','4','5','6','7','8','9'].includes(event.key))))return false;setMode(m);if(baseEligible()&&simVisible){observationIntent=m;lastEligible=false;lastFrame=0;}return true;}
const canvas=$('ecgCanvas'),ctx=canvas.getContext('2d');let cw=700,ch=210;
const ECG_ZOOM=1.25;
const ITEM_ZOOM_STEPS=[1,1.25,1.5,2];
const itemZoom={case:1,quiz:1};
function resize(){const r=canvas.getBoundingClientRect();cw=r.width;ch=r.height;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(cw*dpr));canvas.height=Math.max(1,Math.round(ch*dpr));ctx.setTransform(dpr,0,0,dpr,0,0);dirty=true;}
new ResizeObserver(resize).observe(canvas);
const NS='http://www.w3.org/2000/svg',particleGroup=$('particles');
const flows=[['body-return','venous','#8ad3ff',10],['ra-rv','fill','#9dddff',4],['rv-lung','eject','#9dddff',9],['lung','pulm','#cab3ef',5],['lung-la','venous','#ffabb2',8],['la-lv','fill','#ffb5b4',4],['lv-body','eject','#ffacb4',13],['body','systemic','#cea0d1',5]];
const flowObjects=flows.map(([id,type,color,count])=>{const path=$('flow-'+id),length=path.getTotalLength();const particles=Array.from({length:count},(_,i)=>{const c=document.createElementNS(NS,'circle');c.setAttribute('r',id.includes('-lv')||id.includes('-rv')?'3':'3.2');c.setAttribute('fill',color);particleGroup.append(c);return {node:c,offset:i/count};});return {id,type,path,length,particles};});
function cumulativeFlow(t,type){
  if(state.mode==='vf')return 0;
  if(type==='venous'||type==='pulm'||type==='systemic')return t*.12;
  const index=model.indexAt(t),near=model.beats.slice(Math.max(0,index-2),index+1),first=near[0];
  const fast=['svt','pat','flutter','sintach'].includes(state.mode),vt=state.mode==='vt',flowStep=vt?.07:fast?.11:.15,fillStep=vt?.07:fast?.11:.20;
  let cycles=type==='eject'?(first.prefix-first.strength)*flowStep:first.n*fillStep;
  for(const b of near){const bi=model.beats.findIndex(row=>row.n===b.n),next=model.beats[bi+1]||{r:b.r+b.rr},tl=model.mechanicalTimeline(b,next),cycle=next.r-b.r;if(type==='eject')cycles+=clamp((t-b.r-tl.ejectStart)/(tl.ejectEnd-tl.ejectStart),0,1)*flowStep*b.strength;else cycles+=clamp((t-b.r-tl.relaxEnd)/Math.max(.01,cycle-tl.relaxEnd),0,1)*fillStep;}
  return cycles;
}
const coronaryPath=$('coronaryFlow'),coronaryLength=coronaryPath?.getTotalLength()||0,coronaryBlockPoint=coronaryPath?.getPointAtLength(coronaryLength*.28),coronaryParticles=[...document.querySelectorAll('.coronary-particle')];
function renderHeart(s){
  $('ra').style.transform=`scale(${1-.08*s.atrial})`;$('la').style.transform=`scale(${1-.08*s.atrial})`;
  if(['af','flutter'].includes(state.mode)){const tremor=Math.sin(s.time*(state.mode==='flutter'?31:39))*.006;$('ra').style.transform=`scale(${1+tremor},${1-tremor})`;$('la').style.transform=`scale(${1-tremor},${1+tremor})`;}
  const delayed=state.mode==='lbbb'||state.mode==='rbbb'?model.snapshot(Math.max(0,s.time-.06)):s,rightCavity=state.mode==='rbbb'?delayed.cavity:s.cavity,leftCavity=state.mode==='lbbb'?delayed.cavity:s.cavity;
  $('rv').style.transform=`scale(${1-.065*rightCavity*s.flow},${1-.045*rightCavity*s.flow})`;
  // Ischaemic territory is a separate segment: the whole ventricle does not stop.
  $('lv').style.transform=`scale(${1-.075*leftCavity*s.flow},${1-.05*leftCavity*s.flow})`;
  $('regionalWall').setAttribute('transform',`translate(${-s.contract*(['stemi','inferior'].includes(state.mode)?.6:5)} 0)`);
  $('regionalWall').style.opacity=['stemi','inferior'].includes(state.mode)?'.3':'1';
  const patch=$('ischemicRegion');if(patch){patch.style.opacity=['stemi','inferior'].includes(state.mode)?'.8':'0';patch.setAttribute('transform',`translate(${s.contract*.5} ${-s.contract*.5})`);}
  $('tricuspid').setAttribute('d',s.avOpen?'M178 303l29 17 32-17':'M178 303l29 0 32 0');$('mitral').setAttribute('d',s.avOpen?'M298 306l33 17 33-17':'M298 306l33 0 33 0');
  $('pulmonaryValve').setAttribute('d',s.eject?'M260 242l12-13 12 13':'M260 242l12 0 12 0');$('aorticValve').setAttribute('d',s.eject?'M297 244l13-13 12 13':'M297 244l13 0 12 0');
  $('atrialWire').style.opacity=NO_P.includes(state.mode)?'.07':String(s.atrial*.8+.1);$('ventWire').style.opacity=s.phase==='qrs'?(state.mode==='vf'?'.45':'.95'):'.14';
  $('saNode').style.opacity=NO_P.includes(state.mode)?'.12':String(.3+s.atrial*.7);$('avNode').style.opacity=s.phase==='qrs'?1:.35;
  $('afSignals').style.opacity=['af','flutter','vf'].includes(state.mode)?String(.45+.3*Math.sin(s.time*(state.mode==='flutter'?31:34))):0;
  if($('coronaryBlock')){const blockAt=coronaryBlockPoint;$('coronaryBlock').setAttribute('transform',`translate(${blockAt.x} ${blockAt.y})`);$('coronaryBlock').style.opacity=['stemi','inferior'].includes(state.mode)?1:0;}
  if($('ischemiaLabel'))$('ischemiaLabel').style.opacity=['stemi','inferior'].includes(state.mode)?1:0;
  for(const f of flowObjects){const progress=cumulativeFlow(s.time,f.type);const open=state.mode!=='vf'&&(f.type==='eject'?s.eject:f.type==='fill'?s.avOpen:true);for(const p of f.particles){const pos=((progress+p.offset)%1+1)%1;const pt=f.path.getPointAtLength(pos*f.length);p.node.setAttribute('cx',pt.x.toFixed(2));p.node.setAttribute('cy',pt.y.toFixed(2));p.node.style.opacity=open?'.92':'.20';}}
  // Coronary microcirculation has its own native path and is reduced in the ischaemic example.
  const cp=coronaryPath;if(cp){coronaryParticles.forEach((p,i)=>{const f=(((state.mode==='vf'?0:s.time*.17)+i/5)%1+1)%1;const pt=cp.getPointAtLength(f*coronaryLength);p.setAttribute('cx',pt.x);p.setAttribute('cy',pt.y);p.style.opacity=state.mode==='vf'?.2:['stemi','inferior'].includes(state.mode)&&f>.28?0:.85;});}
}
function renderECG(){if(!cw||!ch)return;ctx.clearRect(0,0,cw,ch);ctx.fillStyle='#fffafb';ctx.fillRect(0,0,cw,ch);
  const gap=6,columnWidth=(cw-gap*2)/3,windowSeconds=(cw<700?2.2:2.8)/ECG_ZOOM,pxPerSecond=(columnWidth-12)/windowSeconds,small=pxPerSecond*.04,base=ch*.6,mv=small*10,leftTime=state.time-(columnWidth-12)/pxPerSecond;
  const columns=state.leads.map((lead,index)=>({lead,index,offset:index*(columnWidth+gap),width:columnWidth,cursor:index*(columnWidth+gap)+columnWidth-8,leftTime,pxPerSecond,small,base,mv}));
  const active=columns[state.activeLead]||columns[0];ecgGeom={...active,columns,windowSeconds,cw,ch};
  for(const col of columns){const {lead,offset,width,cursor}=col;ctx.save();ctx.beginPath();ctx.rect(offset,0,width,ch);ctx.clip();
    ctx.fillStyle=col.index===state.activeLead?'#fff7f8':'#fffafb';ctx.fillRect(offset,0,width,ch);
    for(let i=Math.floor(leftTime/.04);i*.04<state.time+.5;i++){const x=offset+(i*.04-leftTime)*pxPerSecond;ctx.strokeStyle=i%5===0?'#ebbec7':'#f5dce0';ctx.lineWidth=i%5===0?.8:.45;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,ch);ctx.stroke();}
    for(let i=-Math.ceil(ch/small);i<Math.ceil(ch/small);i++){const y=base+i*small;if(y<0||y>ch)continue;ctx.strokeStyle=i%5===0?'#ebbec7':'#f5dce0';ctx.lineWidth=i%5===0?.8:.45;ctx.beginPath();ctx.moveTo(offset,y);ctx.lineTo(offset+width,y);ctx.stroke();}
    if(['stemi','inferior'].includes(state.mode)){const st=(state.mode==='stemi'?anteriorST:inferiorST)[lead]||0;ctx.fillStyle=st>=0?'#fbbd7638':'#69b7d52f';for(const b of model.between(leftTime-.5,state.time)){const x=offset+(b.r+.04-leftTime)*pxPerSecond,xx=offset+(Math.min(b.r+.19,state.time)-leftTime)*pxPerSecond;if(xx>x)ctx.fillRect(x,base-mv*(st+.07),xx-x,mv*Math.max(.08,Math.abs(st)+.08));}}
    function trace(source,color,widthLine,dash=[]){ctx.save();ctx.beginPath();ctx.rect(offset,0,width-4,ch);ctx.clip();ctx.strokeStyle=color;ctx.lineWidth=widthLine;ctx.lineJoin='round';ctx.setLineDash(dash);ctx.beginPath();for(let lx=0;lx<=width-8;lx+=.55){const t=leftTime+lx/pxPerSecond,y=base-source.signal(t,lead)*mv,x=offset+lx;if(lx===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);}ctx.stroke();ctx.restore();}
    if(state.compare&&state.mode!=='normal')trace(models.normal,'rgba(46,141,247,.85)',1.5,[6,4]);trace(model,state.mode==='normal'?'#144f67':'#b92036',1.8);
    ctx.strokeStyle='#44687535';ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(offset,base);ctx.lineTo(offset+width,base);ctx.stroke();ctx.setLineDash([]);
    ctx.strokeStyle='#25657677';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(cursor,10);ctx.lineTo(cursor,ch-16);ctx.stroke();ctx.fillStyle='#136077';ctx.beginPath();ctx.arc(cursor,base-model.signal(state.time,lead)*mv,2.8,0,Math.PI*2);ctx.fill();
    ctx.font='bold 12px ui-monospace,monospace';ctx.fillStyle='#7b3a46';ctx.textAlign='left';ctx.fillText(lead,offset+7,15);ctx.restore();
    if(col.index<2){ctx.fillStyle='#cfdae0';ctx.fillRect(offset+width+gap/2-1,0,2,ch);}
  }
}
function timeFormat(t){const m=Math.floor(t/60),s=(t%60).toFixed(2).padStart(5,'0');return String(m).padStart(2,'0')+':'+s;}
function renderText(s){$('rateText').textContent=s.electricalRate||'—';$('pulseMetric').textContent=s.pulseText;$('rrMetric').textContent=s.rr?s.rr+' ms':'Ölçülemez';$('qrsMetric').textContent=s.qrs?s.qrs+' ms':'Seçilemez';const pText={af:'P yok · f dalgaları',svt:'P seçilemiyor',vt:'P–QRS ilişkisi yok',vf:'Organize atriyal etkinlik yok',flutter:'F dalgaları · 300/dk',pat:'Ektopik P dalgası',sintach:'Sinüs P dalgası var'}[state.mode];$('pMetric').textContent=pText||(state.mode==='pvc'&&s.beat.isPVC?'PVC öncesi P yok':'P dalgası var');$('phaseTag').textContent={fill:'Doluş / Gevşeme',atrial:'Atriyal etkinlik',qrs:'Depolarizasyon',eject:'Ejeksiyon',t:'Repolarizasyon'}[s.phase]||'Kaotik etkinlik';$('mechanicText').textContent=s.mechanical;$('valveText').textContent=state.mode==='vf'?'İleri akım yok':s.eject?'Çıkış kapakları açık':s.avOpen?'AV kapaklar açık':'Tüm kapaklar kapalı';$('eventTitle').textContent=s.electrical;$('eventText').textContent=s.text;$('eventIcon').textContent=state.mode==='vf'?'≈':{atrial:'P',qrs:s.beat.isPVC?'V':'R',eject:'↗',t:'T',fill:'↘'}[s.phase];document.querySelectorAll('[data-phase]').forEach(b=>b.classList.toggle('active',b.dataset.phase===s.phase));$('timeText').textContent=timeFormat(state.time);const t=$('timeline');t.max=String(Math.max(30,Math.ceil(state.time/30)*30));t.value=state.time;window.dispatchEvent(new CustomEvent('cardai:tick',{detail:{snapshot:s}}));}
function derivePrerequisites(){return PulseState.derive(state);}
function getItem(section,index){const session=section==='case'?state.caseSession:state.quizSession;return PulseCurriculum.byId[session.ids[index]];}
function progress(){const gates=derivePrerequisites();let complete=0;for(const m of MODES){const seconds=Math.min(16,state.viewed[m]),yes=seconds>=16,mark=$('viewed-'+m);mark.textContent=yes?'✓':Math.floor(seconds)+'s';mark.classList.toggle('done',yes);mark.style.setProperty('--progress',seconds/16*100+'%');mark.setAttribute('role','progressbar');mark.setAttribute('aria-valuemin','0');mark.setAttribute('aria-valuemax','16');mark.setAttribute('aria-valuenow',seconds.toFixed(1));mark.setAttribute('aria-label',content[m].title+' gözlem süresi');if(yes)complete++;}const sum=MODES.reduce((n,m)=>n+Math.min(16,state.viewed[m]),0);$('progressBar').style.width=(sum/(MODES.length*16)*100)+'%';const casesSent=state.caseSubmitted.filter(Boolean).length,quizSent=state.quizSubmitted.filter(Boolean).length;$('progressText').textContent=state.activeView==='case'?'Vaka '+(state.currentCase+1)+' / '+COUNT:state.activeView==='quiz'?'Soru '+(state.quizPage+1)+' / '+COUNT+' · ⏱ '+quizClockText():complete+' / '+MODES.length+' EKG sonucu · 16 gerçek sn';$('progressBar').style.width=(state.activeView==='case'?casesSent/COUNT*100:state.activeView==='quiz'?quizSent/COUNT*100:sum/(MODES.length*16)*100)+'%';if(state.activeView==='modes')renderModes(gates);return complete;}
function statusText(ok){if(ended)return;if(S.resumeBlocked){$('saveStatus').textContent=(S.detected?'LMS':'Tarayıcı')+' kaydı okunamadı · önceki veri korundu. Yeniden dene ya da Hakkında’dan ilerlemeyi sıfırla.';return;}const text=S.detected?(S.isLMS?(ok?'İlerleme kaydedildi · LMS':'Kayıt başarısız · yeniden denenecek'):'LMS bağlantısı yok · yerel kayıt'):(ok?'İlerleme kaydedildi · tarayıcı':'Tarayıcı kaydı kullanılamıyor');$('saveStatus').textContent=text;}
let quizClockStart=null;
function quizClockText(){if(quizClockStart===null)return '—';const total=Math.floor((Date.now()-quizClockStart)/1000);return String(Math.floor(total/60)).padStart(2,'0')+':'+String(total%60).padStart(2,'0');}
setInterval(()=>{if(state.activeView==='quiz')progress();},1000);
function persist(){progress();const ok=S.save(state);statusText(ok);if(ok&&S.lastResult.interactions==='failed-pending')$('saveStatus').textContent+=' · etkileşim raporu bekliyor';lastSave=performance.now();}
function markFeature(name,save=true){if(Object.hasOwn(state.features,name)){state.features[name]=Math.min(99,state.features[name]+1);if(save)persist();}}
function setPlaying(v){lastFrame=0;lastEligible=false;playing=!!v&&!ended;$('playBtn').innerHTML=playing?'Ⅱ <span>Duraklat</span>':'▶ <span>Oynat</span>';$('playBtn').setAttribute('aria-label',playing?'Simülasyonu duraklat':'Simülasyonu oynat');$('liveBadge').innerHTML=playing?'<i></i> CANLI · Ⅱ DURAKLAT':'▶ OYNAT';$('liveBadge').setAttribute('aria-label',playing?'Simülasyonu duraklat':'Simülasyonu oynat');dirty=true;}
const MODE_LEADS={normal:['II','aVF','V3'],af:['II','aVF','V1'],stemi:['II','aVL','V3'],pvc:['II','aVR','V1'],svt:['II','aVF','V1'],inferior:['II','aVF','V1'],vt:['II','aVR','V1'],vf:['II','aVF','V1'],pat:['II','aVF','V1'],flutter:['II','aVF','V1'],sintach:['II','aVF','V3'],lbbb:['I','aVL','V6'],rbbb:['I','aVR','V1']};
function setMode(m,resetTime=true){if(!MODES.includes(m))return;revokeObservation();state.mode=m;if(resetTime){state.time=2;state.leads=[...MODE_LEADS[m]];state.activeLead=0;state.lead=state.leads[0];}model=models[m];applyMode();document.querySelector(`.rhythm-tab[data-mode="${m}"]`)?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'});persist();}
function setLead(column,lead){if(typeof lead==='undefined'){lead=column;column=LEAD_GROUPS.findIndex(g=>g.includes(lead));}column=Number(column);if(!LEAD_GROUPS[column]?.includes(lead))return;state.leads[column]=lead;state.activeLead=column;state.lead=lead;applyMode();persist();}
function setAfProfile(profile){state.afProfile=profile==='rapid'?'rapid':'controlled';models.af=new CardiacModel('af',{afProfile:state.afProfile});if(state.mode==='af')model=models.af;state.time=2;applyMode();persist();}
function applyMode(){const d=content[state.mode];state.lead=state.leads[state.activeLead];document.body.dataset.mode=state.mode;document.querySelectorAll('.rhythm-tab[data-mode]').forEach(b=>{const yes=b.dataset.mode===state.mode;b.classList.toggle('selected',yes);b.setAttribute('aria-pressed',yes);});$('explanationTitle').textContent=d.title;$('summaryText').textContent=d.summary;$('traceLabel').textContent=d.label;document.querySelectorAll('.lead-select').forEach((select,i)=>{select.value=state.leads[i];select.closest('.lead-choice').classList.toggle('active',i===state.activeLead);});$('afProfile').hidden=state.mode!=='af';$('afProfile').value=state.afProfile;const clues=[...d.clues];if(['stemi','inferior'].includes(state.mode)){const map=state.mode==='stemi'?anteriorST:inferiorST,lead=state.leads[state.activeLead],st=map[lead]||0;clues[0]=lead+' J+20 ms '+(st>=0?'+':'')+st.toFixed(2).replace('.',',')+' mV';}$('clues').innerHTML=clues.map(x=>'<span>'+x+'</span>').join('');$('teachingNote').innerHTML=d.note;$('detailCards').innerHTML=d.cards.map((x,i)=>'<article><h3><span>'+['∿','♡','+'][i]+'</span> '+x[0]+'</h3><p>'+x[1]+'</p></article>').join('');const ab=document.querySelector('[data-phase="atrial"]'),noDiscreteP=NO_P.includes(state.mode);ab.textContent=state.mode==='af'?'f / Sürekli':state.mode==='flutter'?'F / Sürekli':noDiscreteP?'P seçilemiyor':'P / Atriyum';ab.disabled=noDiscreteP;ab.title=noDiscreteP?'Bu örnekte ayrı bir P olayı seçilemez.':'';$('speed').value=state.speed;$('compareBtn').disabled=state.mode==='normal'||state.mode==='vf';if(state.mode==='normal'||state.mode==='vf'){state.compare=false;$('compareBtn').classList.remove('active');$('compareBtn').setAttribute('aria-pressed','false');$('compareKey').hidden=true;}$('measurementOutput').textContent='Bir derivasyon grubunun izine tıklayarak onu etkinleştir; dalgayı seçerek ilgili faza git.';$('selectedMetric').textContent='—';dirty=true;draw();window.dispatchEvent(new CustomEvent('cardai:mode',{detail:{mode:state.mode}}));}
function draw(){snapshot=model.snapshot(state.time);renderHeart(snapshot);renderECG();renderText(snapshot);dirty=false;}
function seek(t){setPlaying(false);state.time=clamp(t,0,36000);draw();persist();}
function showView(view='sim'){revokeObservation();if(!['sim','case','quiz','about','modes','tutorial','results'].includes(view))view='sim';const gates=derivePrerequisites();state.activeView=view;simVisible=view==='sim'||view==='tutorial';setPlaying(false);if(view==='quiz'&&quizClockStart===null)quizClockStart=Date.now();const scene=view==='tutorial'?'sim':view;for(const v of ['sim','case','quiz','about','modes','results'])$(v+'View').hidden=v!==scene;$('tutorialPanel').hidden=view!=='tutorial';renderHeader(view);if(view==='sim'||view==='tutorial'){requestAnimationFrame(resize);dirty=true;}else {const heading=$('modesView')?.querySelector('.mode-title')&&view==='modes'?$('modesTitle'):$(view+'Title');heading?.setAttribute('tabindex','-1');heading?.focus();}if(view==='quiz')renderQuiz();if(view==='modes')renderModes(gates);progress();persist();window.dispatchEvent(new CustomEvent('cardai:view',{detail:{view}}));}
function retrySample(section){revokeObservation();const key=section==='case'?'caseSession':'quizSession',session=state[key];session.id=PulseState.sample(section).id;session.answers.fill(null);session.submitted.fill(false);session.interactionIndices.fill(null);if(section==='case')state.currentCase=0;else state.quizPage=0;state.returnContext=null;derivePrerequisites();renderQuiz();persist();window.dispatchEvent(new CustomEvent('cardai:session',{detail:{section}}));if(state.activeView==='results'||(section==='case'&&state.activeView==='quiz'))showView(section);}
function newSample(section){revokeObservation();const key=section==='case'?'caseSession':'quizSession';state[key]=PulseState.sample(section,state[key].ids);if(section==='case')state.currentCase=0;else state.quizPage=0;state.returnContext=null;derivePrerequisites();renderQuiz();persist();window.dispatchEvent(new CustomEvent('cardai:session',{detail:{section}}));if(state.activeView==='results'||(section==='case'&&state.activeView==='quiz'))showView(section);}
const STAGE_HINTS={case:'Öneri: 13 EKG sonucunun her birini 16 gerçek saniye izleyin',quiz:'Öneri: önce oturumdaki 10 vaka yanıtını gönderin'};
let pendingExit=null;
function leaveFor(target){if(state.activeView==='quiz'&&target!=='quiz'){pendingExit=target;$('quizExitDialog').showModal();return;}if(target==='landing'){window.CardAILanding?.showLanding();return;}showView(target);}
const MODE_LABELS={sim:['learn','İnceleme Modu'],case:['practice','Uygulama Modu'],quiz:['assessment','Değerlendirme Modu']};
function renderHeader(view){const isMode=!!MODE_LABELS[view];$('headerContext').hidden=!isMode;$('modeSwitch').hidden=!isMode;if(isMode){const [kind,label]=MODE_LABELS[view],chip=$('modeChip');chip.className='mode-chip '+kind;chip.textContent=label;}$('appRoot').dataset.modeIdentity=view==='quiz'?'assessment':'';}
const MODE_ICONS={learn:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 21C7 17.5 2 13.4 2 8.9 2 6.2 4.2 4 6.9 4c1.7 0 3.2.8 4.1 2.1L12 7.6l1-1.5C13.9 4.8 15.4 4 17.1 4 19.8 4 22 6.2 22 8.9c0 4.5-5 8.6-10 12.1z"/></svg>',practice:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 2h7l5 5v15H7zM14 2v5h5M10 13h5M10 17h5"/></svg>',assessment:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 4h16v16H4zM8 12l3 3 5-6"/></svg>'};
function renderModes(gates=derivePrerequisites()){const box=$('modeCards');if(!box)return;const pool=window.PulseCurriculum,watched=MODES.filter(m=>state.viewed[m]>=16).length,sent=state.caseSubmitted.filter(Boolean).length,quizSent=state.quizSubmitted.filter(Boolean).length,pctLearn=Math.round(watched/MODES.length*100),pctCase=Math.round(sent/COUNT*100),ck='<span class="ck" aria-hidden="true">✓</span>';
const learn=`<article class="mode-card learn"><span class="ic">${MODE_ICONS.learn}</span><h3>İnceleme Modu</h3><p class="desc">${MODES.length} EKG sonucunu kalp–EKG–dolaşım birlikte, kaliper ve rehberli turla sınırsız inceleyin.</p><ul><li>${ck}${MODES.length} EKG sonucu</li><li>${ck}12 derivasyon</li><li>${ck}Kaliper, ölçüm ve rehberli tur</li></ul><div class="mode-status">${watched}/${MODES.length} EKG sonucu izlendi<div class="mode-progress"><i style="width:${pctLearn}%"></i></div></div><button class="btn" type="button" data-view="sim">${watched>0?'İncelemeye devam et':'İncelemeye başla'} <span aria-hidden="true">→</span></button></article>`;
const practice=`<article class="mode-card practice"><span class="ic">${MODE_ICONS.practice}</span><h3>Uygulama Modu</h3><p class="desc">${pool.cases.length} vakalık havuzdan her oturumda rastgele 10 vaka; gönderim sonrası açıklama ve simülatörde açma.</p><ul><li>${ck}Rastgele 10 vaka</li><li>${ck}Gönderim sonrası açıklama</li><li>${ck}Simülatörde aç</li></ul><div class="mode-status">${gates.casesUnlocked?`Oturum: ${sent}/10 gönderildi`:`${STAGE_HINTS.case} — ${watched}/${MODES.length} tamamlandı`}<div class="mode-progress"><i style="width:${gates.casesUnlocked?pctCase:pctLearn}%"></i></div></div><button class="btn" type="button" data-view="case">${sent>0?'Vakalara devam et':'Vakaları çöz'} <span aria-hidden="true">→</span></button></article>`;
const assessment=`<article class="mode-card assessment"><span class="ic">${MODE_ICONS.assessment}</span><h3>Değerlendirme Modu</h3><p class="desc">${pool.questions.length} soruluk havuzdan rastgele 10 soru; 8/10 doğru = 80 geçer, en iyi puan LMS’ye yazılır.</p><ul><li>${ck}Rastgele 10 soru</li><li>${ck}Geçme eşiği 80</li><li>${ck}SCORM puanı</li></ul><div class="mode-status">${state.assessed&&state.bestScore!==null?`En iyi puan: ${state.bestScore}`:gates.quizUnlocked?'Henüz denenmedi':`${STAGE_HINTS.quiz} — ${sent}/10 gönderildi`}${quizSent?`<div class="mode-progress"><i style="width:${quizSent*10}%"></i></div>`:''}</div><button class="btn" type="button" data-view="${state.assessed?'results':'quiz'}">${state.assessed?'Sonuçları gör':'Değerlendirmeye gir'} <span aria-hidden="true">→</span></button></article>`;
const html=learn+practice+assessment;if(box.dataset.rendered!==html){box.innerHTML=html;box.dataset.rendered=html;}if(!box.dataset.bound){box.dataset.bound='1';box.addEventListener('click',e=>{const btn=e.target.closest('button[data-view]');if(!btn||!box.contains(btn))return;btn.dataset.view==='results'?window.CardAResults.show('quiz'):showView(btn.dataset.view);});}}
function resetAll(){const fresh=freshState();for(const k of Object.keys(state))delete state[k];Object.assign(state,fresh);models=Object.fromEntries(MODES.map(m=>[m,new CardiacModel(m,m==='af'?{afProfile:'controlled'}:{})]));model=models.normal;S.clearLocal();S.acknowledgeReset();renderQuiz();applyMode();setPlaying(false);showView('sim');progress();persist();window.dispatchEvent(new Event('cardai:reset'));}
function frame(now){const elapsed=lastFrame?Math.max((now-lastFrame)/1000,0):0,dt=Math.min(elapsed,.1);lastFrame=now;const eligible=observeEligible(),learning=learningEligible();S.setActivity(learning);if(learning&&lastLearning)state.learningMs+=elapsed*1000;lastLearning=learning;if(eligible&&lastEligible){state.viewed[state.mode]=Math.min(16,state.viewed[state.mode]+elapsed);}lastEligible=eligible;if(playing&&simVisible&&baseEligible()){state.time=Math.min(36000,state.time+dt*state.speed);dirty=true;if(state.time>=36000)setPlaying(false);}if(dirty&&simVisible&&baseEligible()){snapshot=model.snapshot(state.time);renderHeart(snapshot);renderECG();if(now-lastText>90||!playing){renderText(snapshot);lastText=now;}dirty=false;frameCount++;}if(now-lastProgress>250){progress();lastProgress=now;}if(now-lastSave>10000&&!ended)persist();requestAnimationFrame(frame);}
document.querySelectorAll('.rhythm-tab[data-mode]').forEach(b=>b.addEventListener('click',e=>selectMode(b.dataset.mode,e)));
document.querySelectorAll('.lead-select').forEach((select,i)=>select.addEventListener('change',()=>setLead(i,select.value)));
$('playBtn').addEventListener('click',()=>setPlaying(!playing));$('liveBadge').addEventListener('click',()=>setPlaying(!playing));$('stepBtn').addEventListener('click',()=>seek(model.nextEvent(state.time)));$('resetBtn').addEventListener('click',()=>{state.time=0;draw();persist();});$('speed').addEventListener('change',()=>{state.speed=Number($('speed').value);persist();});$('timeline').addEventListener('input',()=>seek(Number($('timeline').value)));
document.querySelectorAll('[data-phase]').forEach(b=>b.addEventListener('click',()=>seek(model.phaseTime(state.time,b.dataset.phase))));
$('labelsToggle').addEventListener('change',()=>{$('anatomyLabels').style.display=$('labelsToggle').checked?'':'none';});$('electricToggle').addEventListener('change',()=>{$('conduction').style.display=$('electricToggle').checked?'':'none';});
function openInfo(){resumeAfterDialog=playing;setPlaying(false);$('infoDialog').showModal();}$('helpBtn').addEventListener('click',openInfo);$('closeInfo').addEventListener('click',()=>$('infoDialog').close());$('infoDialog').addEventListener('close',()=>setPlaying(resumeAfterDialog));
$('modeSwitch').addEventListener('click',()=>leaveFor('modes'));$('closeQuizExit').addEventListener('click',()=>{$('quizExitDialog').close();pendingExit=null;});$('cancelQuizExit').addEventListener('click',()=>{$('quizExitDialog').close();pendingExit=null;});$('confirmQuizExit').addEventListener('click',()=>{$('quizExitDialog').close();const target=pendingExit||'modes';pendingExit=null;if(target==='landing')window.CardAILanding?.showLanding();else showView(target);});document.querySelectorAll('.back-sim').forEach(b=>b.addEventListener('click',()=>showView('sim')));
function caseCardMarkup(item,i,section='case'){const vitals=item.vitals&&item.vitals.length?`<div class="kv-grid">${item.vitals.map(v=>`<div class="kv"><div class="k">${v.k}</div><div class="v">${v.v}</div></div>`).join('')}</div>`:'';const label=section==='quiz'?'Soru':'Vaka',id=section==='quiz'?'quizCaseCard':'caseCard',badge=section==='quiz'?label:`${label} ${String(i+1).padStart(2,'0')} / 10`;return `<article class="card case-card" id="${id}"><header class="case-card-head"><span class="ico" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M7 2h7l5 5v15H7zM14 2v5h5M10 13h5M10 17h5"/></svg></span><h2>Olgu</h2><span class="badge">${badge}</span></header><p class="case-stem">${item.stem}</p>${item.note?`<p class="case-note">${item.note}</p>`:''}${vitals}</article>`;}
function ecgMarkup(section,item){const session=section==='case'?state.caseSession:state.quizSession,index=section==='case'?state.currentCase:state.quizPage,groups=[['I','II','III'],['aVR','aVL','aVF'],['V1','V2','V3','V4','V5','V6']];
return `<div class="case-ecg-wrap"><div class="canvas-hold"><canvas id="${section}EcgCanvas" role="img" aria-label="${item.ariaLabel}"></canvas><div class="case-caliper" id="${section}Caliper" hidden><i class="a"></i><i class="b"></i></div></div><div class="lead-chips" role="group" aria-label="${section==='case'?'Vaka':'Soru'} derivasyon seçimi">${session.leadSelections[index].map((lead,j)=>`<div class="lead-chip-group" data-column="${j}">${(groups.find(g=>g.includes(item.ecg.leads[j]))||groups[j]).map(l=>`<button type="button" class="lead-chip${l===lead?' is-active':''}" data-question-lead="${section}" data-column="${j}" data-lead="${l}" aria-pressed="${l===lead}" aria-label="${section==='case'?'Vaka':'Soru'} ${j+1}. derivasyon: ${l}">${l}</button>`).join('')}</div>`).join('')}</div><p class="ecg-note">Sentetik kayıt · zaman saniye, voltaj mV ·25 mm/sn,10 mm/mV*</p></div>`;}
function drawItemECG(section=state.activeView){if(!['case','quiz'].includes(section))return;const cv=$(section+'EcgCanvas');if(!cv)return;const r=cv.getBoundingClientRect();if(r.width<20||r.height<20)return;const w=r.width,h=r.height,dpr=Math.min(devicePixelRatio||1,2);cv.width=Math.round(w*dpr);cv.height=Math.round(h*dpr);const x=cv.getContext('2d');x.setTransform(dpr,0,0,dpr,0,0);x.fillStyle='#fffafb';x.fillRect(0,0,w,h);const index=section==='case'?state.currentCase:state.quizPage,session=section==='case'?state.caseSession:state.quizSession,item=getItem(section,index),source=new CardiacModel(item.ecg.mode,item.ecg.options),gap=8,width=(w-16)/3,zoom=itemZoom[section]||1,pps=(width-32)/item.ecg.seconds*zoom,small=pps*.04,mv=small*10,base=h*.62;
for(let j=0;j<3;j++){const lead=session.leadSelections[index][j],ox=j*(width+gap),compare=state.compare&&item.ecg.mode!=='normal';x.save();x.beginPath();x.rect(ox,0,width,h);x.clip();for(let gx=0;gx<width;gx+=small){x.strokeStyle=Math.round(gx/small)%5===0?'#e6b9c2':'#f3d8dd';x.lineWidth=.6;x.beginPath();x.moveTo(ox+gx,0);x.lineTo(ox+gx,h);x.stroke();}for(let gy=base%small;gy<h;gy+=small){x.strokeStyle='#ebc8d0';x.beginPath();x.moveTo(ox,gy);x.lineTo(ox+width,gy);x.stroke();}if(compare){const reference=new CardiacModel('normal');x.save();x.strokeStyle='rgba(46,141,247,.85)';x.lineWidth=1.5;x.setLineDash([6,4]);x.beginPath();for(let px=0;px<width-8;px+=.8){const t=item.ecg.start+px/pps,y=base-reference.signal(t,lead)*mv;if(px===0)x.moveTo(ox+px,y);else x.lineTo(ox+px,y);}x.stroke();x.restore();}x.strokeStyle='#a81730';x.lineWidth=2;x.beginPath();for(let px=0;px<width-8;px+=.65){const t=item.ecg.start+px/pps,y=base-source.signal(t,lead)*mv;if(px===0)x.moveTo(ox+px,y);else x.lineTo(ox+px,y);}x.stroke();x.font='bold 12px ui-monospace,monospace';x.fillStyle='#67333f';x.fillText(lead,ox+6,16);x.fillText(item.ecg.start.toFixed(1)+'s',ox+6,h-6);x.fillText((item.ecg.start+item.ecg.seconds).toFixed(1)+'s',ox+width-40,h-6);x.fillText('1mV',ox+5,base-mv);x.restore();}cv.dataset.itemId=item.id;cv.dataset.leads=session.leadSelections[index].join(',');}
const itemResizeObserver=new ResizeObserver(entries=>{for(const entry of entries)drawItemECG(entry.target.id.startsWith('case')?'case':'quiz');});
const zoomLabel=z=>String(z).replace('.',',')+'×';
function syncZoomUI(section){const out=$(section+'ZoomLevel');if(!out)return;out.textContent=zoomLabel(itemZoom[section]);const group=out.closest('.zoom-group');if(!group)return;const idx=ITEM_ZOOM_STEPS.indexOf(itemZoom[section]);group.querySelectorAll('[data-zoom]').forEach(btn=>{btn.disabled=btn.dataset.zoom==='out'?idx<=0:idx>=ITEM_ZOOM_STEPS.length-1;});}
function bindItemZoom(section){const out=$(section+'ZoomLevel'),group=out&&out.closest('.zoom-group');if(!group)return;group.querySelectorAll('[data-zoom]').forEach(btn=>btn.onclick=()=>{const idx=ITEM_ZOOM_STEPS.indexOf(itemZoom[section]),next=clamp(idx+(btn.dataset.zoom==='in'?1:-1),0,ITEM_ZOOM_STEPS.length-1);itemZoom[section]=ITEM_ZOOM_STEPS[next];syncZoomUI(section);drawItemECG(section);});syncZoomUI(section);}
function bindItemECG(section){const cv=$(section+'EcgCanvas');if(state.activeView===section){itemResizeObserver.disconnect();if(cv)itemResizeObserver.observe(cv);}
bindItemZoom(section);
document.querySelectorAll(`[data-question-lead="${section}"]`).forEach(chip=>chip.addEventListener('click',()=>{const index=section==='case'?state.currentCase:state.quizPage,session=section==='case'?state.caseSession:state.quizSession,column=Number(chip.dataset.column);session.leadSelections[index][column]=chip.dataset.lead;chip.parentElement.querySelectorAll('.lead-chip').forEach(sibling=>{sibling.classList.toggle('is-active',sibling===chip);sibling.setAttribute('aria-pressed',String(sibling===chip));});chip.classList.add('is-seen');drawItemECG(section);persist();}));
requestAnimationFrame(()=>drawItemECG(section));}
function optionFeedback(item,answer){return item.options.map((o,j)=>`<p><b>${String.fromCharCode(65+j)}. ${j===item.correct?'Doğru seçenek':j===answer?'Seçilen çeldirici':'Çeldirici'}:</b> ${item.explanations[j]}</p>`).join('');}
function renderQuiz(){derivePrerequisites();const i=state.quizPage,q=getItem('quiz',i),form=$('quizForm'),submitted=state.quizSubmitted[i],answered=state.quizSubmitted.filter(Boolean).length;
form.innerHTML=`<article class="quiz-item"><section class="stage-card" aria-label="Soru EKG sahnesi"><div class="stage-top"><span class="stage-badge">● Sentetik kayıt</span><span class="stage-id">SORU ${String(i+1).padStart(2,'0')} /10 · ${q.id}</span><span class="zoom-group" role="group" aria-label="EKG yakınlaştırma"><button type="button" class="tool-btn" data-zoom="out" aria-label="Uzaklaştır">−</button><output class="zoom-level" id="quizZoomLevel">1×</output><button type="button" class="tool-btn" data-zoom="in" aria-label="Yakınlaştır">+</button></span></div>${ecgMarkup('quiz',q)}</section><section class="case-side"><div class="strict-banner${i===0?'':' thin'}">${i===0?'<b>Değerlendirme modu.</b> Gönderilen yanıt değiştirilemez; açıklamalar tüm sorular yanıtlanıp değerlendirildikten sonra gösterilir.':'Gönderilen yanıt değiştirilemez · açıklamalar sonuç ekranında'}</div>${caseCardMarkup(q,i,'quiz')}<article class="q-card-dark quiz-card" aria-labelledby="quizQuestionTitle"><header class="q-head"><span class="eyebrow">DEĞERLENDİRME · SORU ${i+1}/10</span><span class="q-count">${answered}/10 gönderildi</span></header><div class="q-dots" role="progressbar" aria-valuemin="0" aria-valuemax="10" aria-valuenow="${answered}" aria-label="${answered}/10 soru gönderildi">${state.quizSession.ids.map((id,j)=>`<i class="${state.quizSubmitted[j]?'done':j===i?'now':''}"></i>`).join('')}</div><fieldset class="q-body"><legend id="quizQuestionTitle">${q.text}</legend>${q.options.map((o,j)=>`<label class="opt${submitted?' is-locked':''}" role="radio" aria-checked="${state.answers[i]===j}"><input type="radio" name="q${i}" value="${j}" ${state.answers[i]===j?'checked':''} ${submitted?'disabled':''}><span class="opt-radio" aria-hidden="true"></span><span class="opt-text">${o}</span></label>`).join('')}</fieldset>${submitted?`<p class="q-locked" role="status">Yanıt gönderildi · değiştirilemez</p><button type="button" class="btn primary" id="quizItemNext">${i===9?'Yanıtları değerlendir →':'Sonraki soru →'}</button>`:`<button type="button" class="btn primary" id="quizSubmit" ${state.answers[i]===null?'disabled':''}>Yanıtla →</button>`}<div class="q-feedback" id="feedback-${i}" role="status" aria-live="polite"></div></article></section></article>`;
form.onchange=e=>{if(submitted||!e.target.matches('input[type=radio]'))return;state.answers[i]=Number(e.target.value);form.querySelectorAll('label.opt').forEach((label,j)=>label.setAttribute('aria-checked',String(j===state.answers[i])));const btn=$('quizSubmit');if(btn)btn.disabled=false;persist();};
$('quizSubmit')&&($('quizSubmit').onclick=()=>submitQuizItem());
$('quizItemNext')&&($('quizItemNext').onclick=()=>{if(i===9)grade();else $('quizNext').click();});
$('quizPage').textContent=(i+1)+' /10';$('quizPrev').disabled=i===0;$('quizNext').disabled=i===9;
$('checkBtn').hidden=false;$('checkBtn').disabled=answered<10;$('checkBtn').textContent=`Yanıtları değerlendir (${answered}/10)`;$('retryBtn').hidden=!state.assessed;
$('quizResult').textContent=state.assessed?'Değerlendirme tamamlandı · sonuçlar sonuç ekranında gösterilir.':'';
bindItemECG('quiz');}
function updateBest(){derivePrerequisites();if(state.assessed&&state.attemptScore>=(state.bestAttempt?PulseState.attemptScore(state.bestAttempt)??-1:-1)){state.bestAttempt=JSON.parse(JSON.stringify(state.quizSession));if(state.caseSession.submitted.every(Boolean))state.bestCaseAttempt=JSON.parse(JSON.stringify(state.caseSession));}derivePrerequisites();}
function submitQuizItem(){const i=state.quizPage;if(state.answers[i]===null){$('quizResult').textContent='Önce bir seçenek işaretle.';return;}state.quizSubmitted[i]=true;updateBest();persist();if(state.quizSubmitted.every(Boolean)){grade();return;}renderQuiz();}
function grade(){if(state.answers.some(x=>x===null)){$('quizResult').textContent=state.answers.filter(x=>x!==null).length+'/10 soru seçildi. Tüm soruları yanıtla.';return;}state.quizSession.submitted.fill(true);updateBest();persist();renderQuiz();window.CardAResults?.show('quiz');}
$('quizPrev').addEventListener('click',()=>{state.quizPage=Math.max(0,state.quizPage-1);renderQuiz();persist();});$('quizNext').addEventListener('click',()=>{state.quizPage=Math.min(9,state.quizPage+1);renderQuiz();persist();});$('checkBtn').addEventListener('click',grade);$('retryBtn').addEventListener('click',()=>requestResample('quiz','retry'));$('newQuizSession').addEventListener('click',()=>requestResample('quiz','new'));
let pendingResample=null;
function requestResample(section,action){const answers=section==='case'?state.caseAnswers:state.answers,submitted=section==='case'?state.caseSubmitted:state.quizSubmitted,touched=answers.some(a=>a!==null)||submitted.some(Boolean);if(!touched){(action==='new'?newSample:retrySample)(section);return;}pendingResample={section,action};$('resampleDialog').showModal();}
$('closeResample').addEventListener('click',()=>{$('resampleDialog').close();pendingResample=null;});
$('cancelResample').addEventListener('click',()=>{$('resampleDialog').close();pendingResample=null;});
$('confirmResample').addEventListener('click',()=>{$('resampleDialog').close();const p=pendingResample;pendingResample=null;if(!p)return;(p.action==='new'?newSample:retrySample)(p.section);});
$('newCaseSessionBar').addEventListener('click',()=>requestResample('case','new'));
$('retryCaseSessionBar').addEventListener('click',()=>requestResample('case','retry'));
$('retrySave').addEventListener('click',()=>{if(S.resumeBlocked){const resumed=S.load();if(S.resumeBlocked){statusText(false);return;}revokeObservation();setPlaying(false);for(const k of Object.keys(state))delete state[k];Object.assign(state,PulseState.decode(resumed));model=models[state.mode];renderQuiz();applyMode();showView(state.activeView);window.dispatchEvent(new Event('cardai:reset'));}else persist();});
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!['INPUT','SELECT','BUTTON','TEXTAREA'].includes(e.target.tagName)&&simVisible&&!document.querySelector('dialog[open]')){e.preventDefault();setPlaying(!playing);}});
document.addEventListener('visibilitychange',()=>{lastFrame=0;lastEligible=false;lastLearning=false;if(document.hidden&&!ended)persist();});window.addEventListener('pagehide',e=>{revokeObservation();if(!ended){if(e.persisted)persist();else S.finish(state);}});window.addEventListener('pageshow',e=>{revokeObservation();setPlaying(false);if(e.persisted&&S.ended)location.reload();});
new MutationObserver(()=>{lastEligible=false;lastFrame=0;}).observe(document.body,{subtree:true,attributes:true,attributeFilter:['open','hidden']});
window.addEventListener('scroll',()=>{lastEligible=false;lastFrame=0;},{passive:true});
window.CardAIController={state,content,questions,itemZoom,get model(){return model;},get models(){return models;},get snapshot(){return snapshot;},get geom(){return {...ecgGeom};},get playing(){return playing;},derivePrerequisites,getItem,newSample,retrySample,selectMode,revokeObservation,caseCardMarkup,ecgMarkup,bindItemECG,drawItemECG,optionFeedback,setMode,setLead,setAfProfile,setPlaying,seek,draw,resize,persist,progress,showView,markFeature,resetAll,leaveFor,renderModes,STAGE_HINTS};
window.CardAIDiagnostics={get state(){return JSON.parse(JSON.stringify(state));},get snapshot(){return {...snapshot};},get playing(){return playing;},get frameCount(){return frameCount;},get geom(){return {...ecgGeom};}};
renderQuiz();applyMode();setPlaying(false);progress();showView(state.activeView);requestAnimationFrame(frame);
})();
