(function(root){'use strict';
const rhythm={
 normal:{title:'Normal sinüs ritmi',lead:'D2',clue:'Her QRS öncesinde P dalgası, sabit PR ve düzenli dar QRS',mechanism:'Uyarı sinüs düğümünden çıkar ve normal ileti sistemiyle ventriküllere ulaşır.',effect:'Atriyal katkı ve düzenli ventriküler doluş korunur.',stem:'Rutin kontrolde yakınması olmayan, nabzı düzenli bir kişi'},
 af:{title:'Atriyal fibrilasyon',lead:'D2',clue:'Belirgin P dalgası yok ve R–R aralıkları düzensiz düzensiz',mechanism:'Kaotik atriyal etkinlik organize atriyal kasılmayı ortadan kaldırır.',effect:'Değişken doluş süreleri ve atriyal staz görülebilir.',stem:'Çarpıntı yakınması ve düzensiz nabzı olan bir kişi'},
 stemi:{title:'Anterior ST elevasyonlu MI örneği',lead:'V3',clue:'V2–V4 komşu derivasyonlarında belirgin ST yükselmesi',mechanism:'Anterior bölgede transmural iskemi akım örüntüsünü değiştirir.',effect:'Etkilenen sol ventrikül segmentinde kasılma azalabilir.',stem:'Baskı tarzında göğüs ağrısı ve soğuk terlemesi olan bir kişi'},
 pvc:{title:'Ventriküler erken atım',lead:'D2',clue:'Erken gelen geniş QRS ve ardından kompansatuvar duraklama',mechanism:'Uyarı beklenen sinüs atımından önce ventrikülden başlar.',effect:'Erken atımın doluşu ve mekanik etkinliği azalabilir.',stem:'Aralıklı tekleme hissi tarifleyen, temel ritmi düzenli bir kişi'},
 svt:{title:'Düzenli dar kompleks SVT',lead:'D2',clue:'Yaklaşık 167/dk hızında düzenli, dar kompleks taşikardi',mechanism:'Ventrikül üstü hızlı odak veya reentri AV sistem üzerinden iletilir.',effect:'Kısalan diyastol ventrikül doluşunu azaltabilir.',stem:'Ani başlayan hızlı ve düzenli çarpıntısı olan bir kişi'},
 inferior:{title:'İnferior ST elevasyonlu MI örneği',lead:'aVF',clue:'D2, D3 ve aVF’de ST yükselmesi; D1 ve aVL’de karşılıklı çökme',mechanism:'İnferior bölgedeki akut iskemi komşu derivasyonlarda ST değişikliği oluşturur.',effect:'İnferior duvar hareketi ve pompa etkinliği azalabilir.',stem:'Akut göğüs ağrısı, bulantı ve terlemesi olan bir kişi'},
 vt:{title:'Monomorfik ventriküler taşikardi',lead:'V1',clue:'Hızlı, düzenli ve geniş kompleksli tek biçimli ritim',mechanism:'Hızlı ritim ventriküler dokudan köken alır.',effect:'Kısa doluş ve eşzamanlılık kaybı dolaşımı bozabilir.',stem:'Baş dönmesiyle birlikte hızlı geniş kompleks ritmi olan bir kişi'},
 vf:{title:'Ventriküler fibrilasyon',lead:'D2',clue:'Organize QRS olmadan kaotik ve düzensiz elektriksel etkinlik',mechanism:'Ventriküllerde organize depolarizasyon bulunmaz.',effect:'Etkili ventriküler kasılma ve ileri akım oluşmaz.',stem:'Bilinçsiz, yanıtsız ve dolaşım bulgusu olmayan bir kişi'},
 pat:{title:'Paroksismal atriyal taşikardi',lead:'D2',clue:'Farklı morfolojili P dalgalarıyla düzenli dar kompleks taşikardi',mechanism:'Sinüs düğümü dışındaki atriyal bir odak hızlı uyarı üretir.',effect:'Atriyal kasılma sürerken yüksek hız doluş süresini kısaltır.',stem:'Ani başlayıp sonlanan düzenli çarpıntısı olan bir kişi'},
 flutter:{title:'Atriyal flutter',lead:'aVF',clue:'İnferior derivasyonlarda testere dişi F dalgaları ve 2:1 iletim',mechanism:'Düzenli makro-reentran atriyal devre yaklaşık 300/dk etkinlik üretir.',effect:'Koordineli atriyal katkı azalır; hızlı yanıt doluşu kısaltır.',stem:'Düzenli hızlı nabız ve eforla nefes darlığı olan bir kişi'},
 sintach:{title:'Sinüs taşikardisi',lead:'D2',clue:'Yaklaşık 120/dk, her QRS öncesinde sinüs P dalgası',mechanism:'Hız artmış olsa da uyarı sinüs düğümünden çıkar.',effect:'Diyastol kısalır ancak sıralı atriyoventriküler etkinlik korunur.',stem:'Ateş sonrası düzenli hızlı nabzı olan bir kişi'},
 lbbb:{title:'Sol dal bloğu',lead:'V6',clue:'Geniş QRS; V1’de derin negatif kompleks, V6’da geniş çentikli R',mechanism:'Sol ventrikül aktivasyonu gecikerek hücreden hücreye yayılır.',effect:'Ventriküller arası mekanik eşzamanlılık azalabilir.',stem:'Geniş QRS saptanan ve V1–V6 morfolojisi karşılaştırılan bir kişi'},
 rbbb:{title:'Sağ dal bloğu',lead:'V1',clue:'Geniş QRS; V1’de rSR′ ve V6’da geniş terminal S',mechanism:'Sağ ventrikül aktivasyonu sağ dal iletimindeki gecikme nedeniyle geç tamamlanır.',effect:'Sağ ventrikül kasılması hafif gecikmiş olabilir.',stem:'V1’de terminal R′ ile geniş QRS saptanan bir kişi'}
};
const keys=Object.keys(rhythm);
const caseLeads={normal:['D2','aVF','V3'],af:['D2','aVF','V1'],stemi:['D2','aVL','V3'],pvc:['D2','aVR','V1'],svt:['D2','aVF','V1'],inferior:['D2','aVF','V1'],vt:['D2','aVR','V1'],vf:['D2','aVF','V1'],pat:['D2','aVF','V1'],flutter:['D2','aVF','V1'],sintach:['D2','aVF','V3'],lbbb:['D1','aVL','V6'],rbbb:['D1','aVR','V1']};
const caseTitles={normal:'Rutin kontrol ve düzenli nabız',af:'Çarpıntı ve düzensiz nabız',stemi:'Göğüs ağrısı ve prekordiyal değişiklik',pvc:'Aralıklı tekleme hissi',svt:'Ani başlayan hızlı çarpıntı',inferior:'Göğüs ağrısı, bulantı ve terleme',vt:'Baş dönmesi ve geniş kompleks ritim',vf:'Bilinç kaybı ve dolaşım bulgusu yokluğu',pat:'Ataklar halinde düzenli çarpıntı',flutter:'Hızlı nabız ve efor dispnesi',sintach:'Ateş sonrası hızlı nabız',lbbb:'Geniş QRS ve iletim gecikmesi',rbbb:'Prekordiyal derivasyonlarda iletim gecikmesi'};
const cases=Array.from({length:50},(_,i)=>{const mode=keys[i%keys.length],d=rhythm[mode],age=24+((i*7)%58),others=[keys[(i+4)%keys.length],keys[(i+8)%keys.length]];return {id:i+1,mode,title:caseTitles[mode],diagnosis:d.title,stem:`${age} yaşında, ${d.stem}. Kayıt ${caseLeads[mode].join(', ')} derivasyonlarıyla birlikte gösteriliyor.`,question:'EKG bulgularıyla en uyumlu seçenek hangisidir?',options:[d.title,rhythm[others[0]].title,rhythm[others[1]].title],correct:0,lead:d.lead,clue:d.clue,feedback:`${d.clue}. ${d.mechanism}`};});
const questions=[];
for(const mode of keys){const d=rhythm[mode],others=[keys[(keys.indexOf(mode)+3)%keys.length],keys[(keys.indexOf(mode)+7)%keys.length]];questions.push({text:`“${d.clue}” bulgusu hangi ritim veya örnekle en iyi eşleşir?`,options:[rhythm[others[0]].title,d.title,rhythm[others[1]].title],correct:1,feedback:`Doğru eşleşme: ${d.title}. ${d.mechanism}`});}
for(const mode of keys){const d=rhythm[mode];questions.push({text:`${d.title} değerlendirilirken bu örnekte öncelikle hangi derivasyon seçilmelidir?`,options:[d.lead,d.lead==='V1'?'aVL':'V1',d.lead==='D2'?'V6':'D2'],correct:0,feedback:`Bu öğretim örneğinde odak derivasyon ${d.lead} olarak seçilmiştir; tanısal değerlendirme 12 derivasyon ve klinik bağlam gerektirir.`});}
for(const mode of keys){const d=rhythm[mode],other=rhythm[keys[(keys.indexOf(mode)+5)%keys.length]];questions.push({text:`${d.title} için mekanizmayı doğru açıklayan ifade hangisidir?`,options:[other.mechanism,'EKG yalnızca damar içindeki kanın hareketini kaydeder.',d.mechanism],correct:2,feedback:d.mechanism});}
for(const mode of keys.slice(0,11)){const d=rhythm[mode],other=rhythm[keys[(keys.indexOf(mode)+6)%keys.length]];questions.push({text:`${d.title} için olası dolaşım etkisi hangisidir?`,options:['Elektriksel etkinlik mekanik yanıtı hiçbir zaman etkilemez.',d.effect,other.effect],correct:1,feedback:d.effect});}
root.PulseCurriculum={rhythm,cases,questions:questions.slice(0,50)};
})(window);
