(function(){'use strict';
const $=id=>document.getElementById(id),C=window.CardAIController,S=window.CardAIScorm,state=C.state,clamp=window.CardAIModel.clamp;
let activeChallenge=null,guideIndex=0,caliperVisible=false,caliperTurn='a',dragHandle=null,ignoreCanvasClick=false;
const stValue=()=>((state.mode==='inferior'?window.CardAIModel.inferiorST:window.CardAIModel.anteriorST)[state.lead]||0);

// Fullscreen and panel focus keep the simulator usable on a 16:9 teaching display.
async function toggleFullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await $('appRoot').requestFullscreen();C.markFeature('fullscreen');}catch{$('saveStatus').textContent='Bu tarayıcı tam ekran isteğini engelledi.';}}
const FS_ICON_PATHS={open:'<path d="M8 3H5a2 2 0 0 0-2 2v3"/><path d="M16 3h3a2 2 0 0 1 2 2v3"/><path d="M8 21H5a2 2 0 0 1-2-2v-3"/><path d="M16 21h3a2 2 0 0 0 2-2v-3"/>',exit:'<path d="M3 8h3a2 2 0 0 0 2-2V3"/><path d="M21 8h-3a2 2 0 0 1-2-2V3"/><path d="M3 16h3a2 2 0 0 1 2 2v3"/><path d="M21 16h-3a2 2 0 0 0-2 2v3"/>'};
function syncFullscreen(){const on=!!document.fullscreenElement;const icon=$('fullscreenIcon');if(icon)icon.innerHTML=on?FS_ICON_PATHS.exit:FS_ICON_PATHS.open;$('fullscreenBtn').setAttribute('aria-label',on?'Tam ekrandan çık':'Tam ekrana geç');$('transportFullscreen').textContent=on?'↙ Tam ekrandan çık':'↗ Tam ekran';const landingBtn=$('landingFullscreen');if(landingBtn){const lIcon=$('landingFullscreenIcon');if(lIcon)lIcon.innerHTML=on?FS_ICON_PATHS.exit:FS_ICON_PATHS.open;landingBtn.setAttribute('aria-label',on?'Tam ekrandan çık':'Tam ekrana geç');}requestAnimationFrame(C.resize);}
$('fullscreenBtn').addEventListener('click',toggleFullscreen);$('transportFullscreen').addEventListener('click',toggleFullscreen);document.addEventListener('fullscreenchange',syncFullscreen);
function setFocus(which){const app=$('appRoot'),current=app.dataset.focus||'split',target=which!=='split'&&current===which?'split':which;app.dataset.focus=target==='split'?'':target;$('splitFocusBtn').classList.toggle('active',target==='split');document.querySelectorAll('.panel-focus').forEach(b=>{const active=b.dataset.focusPanel===target;b.classList.toggle('active',active);b.textContent=active?'↙':'↗';b.setAttribute('aria-label',active?'Paneli küçült ve bölünmüş görünüme dön':({anatomy:'Kalbi büyüt',ecg:'EKG’yi büyüt',explanation:'Açıklamayı büyüt'}[b.dataset.focusPanel]));});if(target!=='split')C.markFeature('focus');requestAnimationFrame(C.resize);}
document.querySelectorAll('[data-focus-panel]').forEach(b=>b.addEventListener('click',()=>setFocus(b.dataset.focusPanel)));

// The interface uses one validated 120% typography scale so 16:9 panel geometry stays stable.
function applyScale(){state.uiScale=120;requestAnimationFrame(C.resize);}

// Anatomy layer switches.
for(const [control,target] of [['flowToggle','particles'],['valveToggle','valves'],['coronaryToggle','coronaries']])$(control).addEventListener('change',()=>{$(target).style.display=$(control).checked?'':'none';if(control==='coronaryToggle')$('ischemiaLabel').style.display=$(control).checked?'':'none';});

// Explanatory views and the six-step systematic reading checklist.
const systematic={
 normal:[['Hız','75/dk'],['Ritim','Düzenli'],['P dalgası','Her QRS öncesinde var'],['PR','Yaklaşık 175 ms'],['QRS','Dar · 80 ms'],['ST–T','İzoelektrik ST, pozitif T']],
 af:[['Hız',()=>state.afProfile==='rapid'?'Yaklaşık 110–175/dk':'Yaklaşık 60–100/dk'],['Ritim','Düzensiz düzensiz'],['P dalgası','Seçilemez; f dalgaları'],['PR','Ölçülemez'],['QRS','Genellikle dar · 80 ms'],['ST–T','Bu örnekte akut ST yükselmesi yok']],
 stemi:[['Hız','75/dk'],['Ritim','Düzenli sinüs ritmi'],['P dalgası','Her QRS öncesinde var'],['PR','Yaklaşık 175 ms'],['QRS','Dar · 80 ms'],['ST–T',()=>state.lead+' derivasyonunda J noktası +'+stValue().toFixed(2).replace('.',',')+' mV']],
 pvc:[['Hız','Temel sinüs hızı 75/dk'],['Ritim','Aralıklı erken ventriküler atım'],['P dalgası','PVC öncesinde ilişkili P yok'],['PR','Sinüs atımlarında yaklaşık 175 ms'],['QRS','PVC’de geniş · yaklaşık 140 ms'],['ST–T','PVC sonrası diskordan değişiklik']],
 svt:[['Hız','Yaklaşık 167/dk'],['Ritim','Düzenli taşikardi'],['P dalgası','Bu örnekte seçilemiyor'],['PR','Ölçülemez'],['QRS','Dar · 80 ms'],['ST–T','Kısa döngü nedeniyle T sonraki komplekse yakın']],
 inferior:[['Hız','75/dk'],['Ritim','Düzenli sinüs ritmi'],['P dalgası','Her QRS öncesinde var'],['PR','Yaklaşık 175 ms'],['QRS','Dar · 80 ms'],['ST–T',()=>state.lead+' J noktası '+(stValue()>=0?'+':'')+stValue().toFixed(2).replace('.',',')+' mV']],
 vt:[['Hız','Yaklaşık 158/dk'],['Ritim','Düzenli ventriküler taşikardi'],['P dalgası','QRS ile sabit ilişki yok'],['PR','Ölçülemez'],['QRS','Geniş · yaklaşık 180 ms'],['ST–T','Geniş komplekse sekonder diskordans']],
 vf:[['Hız','Hesaplanamaz'],['Ritim','Kaotik'],['P dalgası','Seçilemez'],['PR','Ölçülemez'],['QRS','Organize kompleks yok'],['ST–T','Ayırt edilemez']],
 pat:[['Hız','Yaklaşık 150/dk'],['Ritim','Düzenli atriyal taşikardi'],['P dalgası','Ektopik morfoloji'],['PR','Sabit ·140 ms'],['QRS','Dar · 80 ms'],['ST–T','Hız nedeniyle T–P yakın']],
 flutter:[['Hız','Atriyal 300 · ventriküler 150/dk'],['Ritim','Düzenli 2:1 iletim'],['P dalgası','P yok; sürekli F dalgaları'],['PR','Ölçülemez'],['QRS','Dar · 80 ms'],['ST–T','F dalgaları temel hattı doldurur']],
 sintach:[['Hız','Yaklaşık 120/dk'],['Ritim','Düzenli sinüs taşikardisi'],['P dalgası','Her QRS öncesinde sinüs P'],['PR','Sabit'],['QRS','Dar · 80 ms'],['ST–T','Bu örnekte akut değişiklik yok']],
 lbbb:[['Hız','75/dk'],['Ritim','Düzenli sinüs ritmi'],['P dalgası','Her QRS öncesinde var'],['PR','175 ms'],['QRS','Geniş ·160 ms'],['ST–T','QRS’ye sekonder diskordans']],
 rbbb:[['Hız','75/dk'],['Ritim','Düzenli sinüs ritmi'],['P dalgası','Her QRS öncesinde var'],['PR','175 ms'],['QRS','Geniş ·140 ms'],['ST–T','V1–V3’te sekonder değişiklik']]
};
function renderSystematic(){const rows=systematic[state.mode];$('systematicList').innerHTML=rows.map(([name,value],i)=>{const key=state.mode+':'+i;return `<label class="systematic-item"><input type="checkbox" data-check="${key}" ${state.checklist[key]?'checked':''}><span><b>${name}</b><span>${typeof value==='function'?value():value}</span></span></label>`;}).join('');$('systematicList').querySelectorAll('[data-check]').forEach(input=>input.addEventListener('change',()=>{state.checklist[input.dataset.check]=input.checked;C.persist();updateSystematicResult();}));updateSystematicResult();}
function updateSystematicResult(){const done=systematic[state.mode].filter((_,i)=>state.checklist[state.mode+':'+i]).length;$('systematicResult').textContent=done===6?'6/6 adım tamamlandı. Bulguları mekanizma ve klinik bağlamla birlikte yorumla.':done+'/6 adım işaretlendi.';}
function showExplain(name){for(const n of ['mechanism','systematic','details']){$(n+'Panel').hidden=n!==name;document.querySelector(`[data-explain-tab="${n}"]`).classList.toggle('active',n===name);}if(name==='systematic'){renderSystematic();C.markFeature('systematic');}}
document.querySelectorAll('[data-explain-tab]').forEach(b=>b.addEventListener('click',()=>showExplain(b.dataset.explainTab)));

// Lead/profile variants and normal-reference overlay.
document.querySelectorAll('.lead-select').forEach((select,i)=>select.addEventListener('change',()=>{renderSystematic();if(['stemi','inferior'].includes(state.mode))showMeasurement('st');}));
$('afProfile').addEventListener('change',()=>{C.setAfProfile($('afProfile').value);renderSystematic();});
$('compareBtn').addEventListener('click',()=>{if(state.mode==='normal')return;state.compare=!state.compare;$('compareBtn').classList.toggle('active',state.compare);$('compareBtn').setAttribute('aria-pressed',String(state.compare));$('compareKey').hidden=!state.compare;if(state.compare)C.markFeature('compare',false);C.draw();C.persist();});
function syncModeTools(){renderSystematic();const comparing=state.compare&&!['normal','vf'].includes(state.mode);$('compareBtn').classList.toggle('active',comparing);$('compareBtn').setAttribute('aria-pressed',String(comparing));$('compareKey').hidden=!comparing;}
window.addEventListener('cardai:mode',syncModeTools);

// Preset and free caliper measurements.
function showMeasurement(kind){const metrics=C.model.metrics(state.time,state.lead);const values={rr:metrics.rr,pr:metrics.pr,qrs:metrics.qrs,qt:metrics.qt},names={rr:'R–R',pr:'PR',qrs:'QRS',qt:'QT'};let label=kind==='st'?(metrics.st===null?'ST: ölçülemez':'J+20 ms: '+metrics.st.toFixed(2).replace('.',',')+' mV · '+state.lead):names[kind]+': '+(values[kind]===null?'ölçülemez':values[kind]+' ms');$('measurementOutput').textContent=label;$('selectedMetric').textContent=label.split(':').slice(1).join(':').trim();$('measurementPresets').hidden=true;}
$('measureBtn').addEventListener('click',()=>{$('measurementPresets').hidden=!$('measurementPresets').hidden;});document.querySelectorAll('[data-measure]').forEach(b=>b.addEventListener('click',()=>showMeasurement(b.dataset.measure)));
document.addEventListener('click',e=>{if(!e.target.closest('#measureBtn')&&!e.target.closest('#measurementPresets'))$('measurementPresets').hidden=true;});
function renderCalipers(){const g=C.geom,a=state.caliper.a,b=state.caliper.b,ha=document.querySelector('.caliper-handle.a'),hb=document.querySelector('.caliper-handle.b');for(const [el,p] of [[ha,a],[hb,b]]){el.style.left=(p.x*100)+'%';el.style.top=(p.y*100)+'%';}const x1=a.x*g.cw,y1=a.y*g.ch,x2=b.x*g.cw,y2=b.y*g.ch,dx=x2-x1,dy=y2-y1,br=$('caliperBracket');br.style.left=x1+'px';br.style.top=y1+'px';br.style.width=Math.hypot(dx,dy)+'px';br.style.transform='rotate('+Math.atan2(dy,dx)+'rad)';if(g.pxPerSecond&&g.mv){const dt=Math.abs(dx/g.pxPerSecond),dmv=Math.abs(dy/g.mv);$('measurementOutput').textContent='Kaliper Δt '+Math.round(dt*1000)+' ms · ΔV '+dmv.toFixed(2).replace('.',',')+' mV';$('selectedMetric').textContent=Math.round(dt*1000)+' ms / '+dmv.toFixed(2).replace('.',',')+' mV';}}
function toggleCaliper(force){caliperVisible=typeof force==='boolean'?force:!caliperVisible;$('caliperLayer').hidden=!caliperVisible;$('caliperBtn').classList.toggle('active',caliperVisible);$('caliperBtn').setAttribute('aria-pressed',String(caliperVisible));if(caliperVisible){renderCalipers();C.markFeature('caliper');}}
$('caliperBtn').addEventListener('click',()=>toggleCaliper());
document.querySelectorAll('.caliper-handle').forEach(h=>h.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();dragHandle=h.dataset.handle;h.setPointerCapture?.(e.pointerId);ignoreCanvasClick=true;}));
window.addEventListener('pointermove',e=>{if(!dragHandle)return;const r=$('ecgScreen').getBoundingClientRect();state.caliper[dragHandle]={x:clamp((e.clientX-r.left)/r.width,.02,.98),y:clamp((e.clientY-r.top)/r.height,.04,.96)};renderCalipers();});
window.addEventListener('pointerup',()=>{if(dragHandle){dragHandle=null;C.persist();setTimeout(()=>ignoreCanvasClick=false,20);}});

// Wave picking maps a click back to the same model time used by heart and circulation.
function nearestBeat(t){return C.model.between(t-.55,t+.55).sort((a,b)=>Math.abs(a.r-t)-Math.abs(b.r-t))[0];}
function classifyWave(t,b){const d=t-b.r;if(state.mode==='vf')return ['Kaotik elektriksel dalga',d,'chaotic'];const candidates=[...(b.pCenter!==null?[[state.mode==='pat'?'Ektopik P':'P dalgası',b.pCenter,'atrial']]:[]),['QRS kompleksi',(b.qrsStart+b.qrsEnd)/2,'qrs'],['ST bölümü',b.stMeasure,'eject'],['T dalgası',b.tCenter,'t']];const hit=candidates.sort((a,c)=>Math.abs(d-a[1])-Math.abs(d-c[1]))[0];return Math.abs(d-hit[1])<.12?hit:null;}
function completeChallenge(type){if(state.challengeCorrect[type])return;state.challengeCorrect[type]=true;$('challengeTitle').textContent='Doğru';$('challengeText').textContent=type==='rr'?'En uzun R–R aralığını buldun.':'ST segmentini doğru gösterdin.';C.markFeature('cases',false);C.persist();setTimeout(()=>{activeChallenge=null;$('challengeBanner').hidden=true;},1400);}
function evaluateChallenge(t,b){if(activeChallenge==='st'){const d=t-b.r;if(d>=.04&&d<=.20){completeChallenge('st');return true;}$('challengeText').textContent='J noktasından sonraki yükselmiş bölgeyi seç.';return false;}if(activeChallenge==='rr'){const g=C.geom,beats=C.model.between(g.leftTime-.1,state.time-.05);let longest=null;for(let i=1;i<beats.length;i++){const row={a:beats[i-1],b:beats[i],rr:beats[i].r-beats[i-1].r};if(!longest||row.rr>longest.rr)longest=row;}if(longest&&Math.abs(t-(longest.a.r+longest.b.r)/2)<Math.min(.24,longest.rr*.32)){completeChallenge('rr');return true;}$('challengeText').textContent='Görünen en geniş iki R tepesi arasını seç.';return false;}return false;}
$('ecgCanvas').addEventListener('click',e=>{if(ignoreCanvasClick)return;const r=$('ecgCanvas').getBoundingClientRect(),g=C.geom,x=e.clientX-r.left,y=e.clientY-r.top,col=g.columns?.find(c=>x>=c.offset&&x<=c.offset+c.width)||g;C.setLead(col.index??state.activeLead,col.lead||state.lead);if(caliperVisible){state.caliper[caliperTurn]={x:clamp(x/r.width,.02,.98),y:clamp(y/r.height,.04,.96)};caliperTurn=caliperTurn==='a'?'b':'a';renderCalipers();C.persist();return;}const t=col.leftTime+(x-(col.offset||0))/col.pxPerSecond,b=nearestBeat(t);if(!b)return;if(activeChallenge)evaluateChallenge(t,b);const hit=classifyWave(t,b);if(!hit)return;C.seek(b.r+hit[1]);const tip=$('waveTip');tip.textContent=(col.lead||state.lead)+' · '+hit[0]+' · '+(hit[2]==='eject'?'ventriküler kasılma ve ejeksiyon':hit[2]==='qrs'?'ventriküler depolarizasyon':hit[2]==='atrial'?'atriyal depolarizasyon':hit[2]==='chaotic'?'organize QRS ve etkili ejeksiyon yok':'repolarizasyon');tip.style.left=(Math.min(94,Math.max(6,x/r.width*100)))+'%';tip.style.top=(Math.min(88,Math.max(18,y/r.height*100)))+'%';tip.hidden=false;setTimeout(()=>tip.hidden=true,2200);});

// Guided teaching mode.
const guideSteps=[['atrial','P dalgası ve atriyum','Uyarı sinüs düğümünden atriyuma yayılır. Atriyal kasılma doluşu tamamlar.'],['qrs','QRS ve ventrikül','Ventriküler depolarizasyon mekanik kasılmadan hemen önce oluşur.'],['eject','ST ve ejeksiyon','Basınç yükselince çıkış kapakları açılır ve kan pulmoner arter ile aortaya pompalanır.'],['t','T dalgası','Ventriküler repolarizasyon, ejeksiyonun son bölümüyle örtüşebilir.'],['fill','Doluş','Ventrikül basıncı düşünce AV kapakları açılır ve döngü yeniden başlar.']];
function availableGuide(){if(state.mode==='vf')return [['qrs','Kaotik elektriksel etkinlik','Organize QRS ve ölçülebilir elektriksel hız yoktur.'],['fill','Etkili dolaşım yok','VF’de organize kasılma, ejeksiyon ve ileri akım gösterilmez.']];const steps=guideSteps.map(row=>[...row]);if(state.mode==='pat')steps[0]=['atrial','Ektopik P ve atriyum','Sinüs düğümü dışındaki atriyal depolarizasyonu şematik kasılma izler.'];return window.CardAIModel.NO_P.includes(state.mode)?steps.filter(s=>s[0]!=='atrial'):steps;}
function renderGuide(){const steps=availableGuide();guideIndex=(guideIndex+steps.length)%steps.length;const [phase,title,description]=steps[guideIndex];$('guideStep').textContent=(guideIndex+1)+'/'+steps.length;$('guideTitle').textContent=title;$('guideText').textContent=description;C.seek(C.model.phaseTime(state.time,phase));}
function toggleGuide(on=!$('guidedCoach').hidden){const show=typeof on==='boolean'?on:$('guidedCoach').hidden;$('guidedCoach').hidden=!show;$('guideBtn').classList.toggle('active',show);$('guideBtn').setAttribute('aria-pressed',String(show));if(show){guideIndex=0;C.markFeature('guide');renderGuide();}}
$('guideBtn').addEventListener('click',()=>toggleGuide($('guidedCoach').hidden));$('guidePrev').addEventListener('click',()=>{guideIndex--;renderGuide();});$('guideNext').addEventListener('click',()=>{guideIndex++;renderGuide();});$('guideClose').addEventListener('click',()=>toggleGuide(false));

// Ten submitted session cases: a selection is not a submission.
const FEEDBACK_ICONS={good:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" aria-hidden="true"><circle cx="12" cy="12" r="10" fill="none"/><path d="m8 12.5 2.6 2.6L16.5 9"/></svg>',bad:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" aria-hidden="true"><circle cx="12" cy="12" r="10" fill="none"/><path d="M9 9l6 6M15 9l-6 6"/></svg>'};
function caseFeedbackMarkup(item,answer){const ok=answer===item.correct,letters=['A','B','C','D','E'];return `<div class="feedback-head ${ok?'good':'bad'}"><span class="ic ${ok?'good':'bad'}" aria-hidden="true">${ok?FEEDBACK_ICONS.good:FEEDBACK_ICONS.bad}</span><h2>${ok?'Doğru!':'Yanlış'}</h2></div>${ok?'':`<p class="feedback-verdict">Yanıtınız: ${letters[answer]}. ${item.options[answer]}</p><p class="feedback-verdict feedback-verdict-good">Doğru yanıt: ${letters[item.correct]}. ${item.options[item.correct]}</p>`}<p class="feedback-text">${item.explanations[item.correct]}</p>${ok?'':`<p class="feedback-text">Seçtiğiniz seçenek neden değil: ${item.explanations[answer]}</p>`}`;}
function questionCardMarkup(item,answer,submitted,last){return `<article class="q-card-dark" id="caseQuestionCard" aria-labelledby="caseQuestionTitle"><header class="q-head"><span class="eyebrow">EKG YORUMU · ${item.id}</span><span class="q-count">Soru 1 / 1</span></header><fieldset class="q-body"><legend id="caseQuestionTitle">${item.question}</legend>${item.options.map((o,j)=>`<label class="opt${submitted?(j===item.correct?' is-correct':j===answer?' is-wrong':''):''}" role="radio" aria-checked="${answer===j}"><input type="radio" name="activeCase" value="${j}" ${answer===j?'checked':''} ${submitted?'disabled':''}><span class="opt-radio" aria-hidden="true"></span><span class="opt-text">${o}</span></label>`).join('')}</fieldset>${submitted?`<div class="q-feedback case-feedback-v2" id="caseFeedback" role="status" aria-live="polite">${caseFeedbackMarkup(item,answer)}</div><button type="button" class="btn primary" id="caseContinue">${last?'Vakayı tamamla':'Devam Et'}</button>`:`<button type="button" class="btn primary" id="caseCheck" ${answer===null?'disabled':''}>Yanıtla →</button><div class="q-feedback" id="caseFeedback" role="status" aria-live="polite"></div>`}</article>`;}
function caseEndMarkup(){const rows=state.caseSession.ids.map((id,i)=>({i,correct:state.caseCorrect[i],title:window.PulseCurriculum.byId[id].title})),correct=rows.filter(row=>row.correct).length;return `<article class="case-end" id="caseEnd"><header><span class="eyebrow">VAKA OTURUMU</span><h2>Oturum tamamlandı · ${correct}/10 doğru</h2></header><div class="case-end-strip">${rows.map(row=>`<button type="button" class="dot ${row.correct?'ok':'no'}" data-case-index="${row.i}" aria-label="Vaka ${row.i+1}: ${row.title} — ${row.correct?'doğru':'yanlış'}">${row.correct?'✓':'✗'}</button>`).join('')}</div><div class="case-end-actions"><button type="button" class="secondary-btn" id="caseEndReport">Raporu gör →</button><button type="button" class="secondary-btn" id="caseEndReview">Yanlışları gözden geçir</button><button type="button" class="btn primary" id="caseEndAssessment">Değerlendirmeye gir →</button><button type="button" class="secondary-btn" id="newCaseSession">Yeni 10 vaka örneklemi</button><button type="button" class="secondary-btn" id="retryCaseSession">Aynı vakaları tekrar dene</button></div></article>`;}
function caseStageMarkup(item,i,answer,submitted){return `<section class="stage-card" aria-label="Vaka EKG sahnesi"><div class="stage-top"><span class="stage-badge" id="caseStageBadge">● Sentetik kayıt</span><span class="stage-id">VAKA ${String(i+1).padStart(2,'0')} /10 · ${item.id}</span></div>${C.ecgMarkup('case',item)}<div class="toolbar case-toolbar"><div class="tool-group"><button type="button" class="tool-btn${state.compare?' active':''}" id="caseCompareBtn" aria-pressed="${state.compare}">≋ Normalle karşılaştır</button><button type="button" class="tool-btn" id="caseCaliperBtn" aria-pressed="false">↔ Kaliper</button></div><output id="caseMeasureOut">Kaliperle iki noktaya tıkla: Δt ve ΔV okunur.</output><span class="ecg-scale">25 mm/sn · 10 mm/mV*</span><button type="button" class="tool-btn only-mobile" id="caseGoQuestion">Soruya git ↓</button>${submitted&&answer===item.correct?'<button type="button" class="secondary-btn" id="caseExpand">Simülatörde aç ↗</button>':''}</div></section>`;}
let caseCaliperOn=false,casePoints=[];
function caseGeometry(){const cv=$('caseEcgCanvas');if(!cv)return null;const r=cv.getBoundingClientRect(),item=C.getItem('case',state.currentCase),width=(r.width-16)/3,pps=(width-32)/item.ecg.seconds;return {r,pps,mv:pps*.4};}
function renderCaseCaliper(){const geometry=caseGeometry();if(!geometry)return;const {r,pps,mv}=geometry;['a','b'].forEach((key,index)=>{const point=casePoints[index],handle=document.querySelector(`#caseCaliper .${key}`);if(!point){if(handle)handle.style.display='none';return;}if(handle){handle.style.display='';handle.style.left=(point.x*100)+'%';handle.style.top=(point.y*r.height*100/r.height)+'%';}});if(casePoints.length===2){const dx=Math.abs(casePoints[1].x-casePoints[0].x)*r.width,dy=Math.abs(casePoints[1].y-casePoints[0].y)*r.height;$('caseMeasureOut').textContent='Kaliper Δt '+Math.round(dx/pps*1000)+' ms · ΔV '+(dy/mv).toFixed(2).replace('.',',')+' mV';}}
function renderCase(){C.derivePrerequisites();const i=state.currentCase,item=C.getItem('case',i),answer=state.caseAnswers[i],submitted=state.caseSubmitted[i],answered=state.caseSubmitted.filter(Boolean).length,last=i===9;
caseCaliperOn=false;casePoints=[];
$('casePager').innerHTML=`<article class="case-detail">${caseStageMarkup(item,i,answer,submitted)}<section class="case-side">${C.caseCardMarkup(item,i,'case')}${questionCardMarkup(item,answer,submitted,last)}${answered===10?caseEndMarkup():''}</section></article>`;
$('caseDots').textContent=(i+1)+' /10';$('casePrev').disabled=i===0;$('caseNext').disabled=last;C.bindItemECG('case');
const card=$('caseCard');if(card){card.classList.add('case-flash');setTimeout(()=>card.classList.remove('case-flash'),620);}
$('casePager').querySelectorAll('input[name="activeCase"]').forEach(input=>input.addEventListener('change',()=>{if(!submitted){state.caseAnswers[i]=Number(input.value);$('casePager').querySelectorAll('label.opt').forEach((label,j)=>label.setAttribute('aria-checked',String(j===Number(input.value))));const btn=$('caseCheck');if(btn)btn.disabled=false;C.persist();}}));
$('caseCheck')?.addEventListener('click',()=>{if(!C.derivePrerequisites().casesUnlocked)return;if(state.caseAnswers[i]===null){$('caseFeedback').textContent='Önce bir seçenek işaretle.';return;}state.caseSubmitted[i]=true;C.markFeature('cases',false);C.persist();renderCase();});
$('caseContinue')?.addEventListener('click',()=>{if(!last)$('caseNext').click();else{$('caseEnd')?.scrollIntoView({block:'start'});$('caseEndReview')?.focus();}});
$('caseCompareBtn')?.addEventListener('click',()=>{state.compare=!state.compare;$('caseCompareBtn').classList.toggle('active',state.compare);$('caseCompareBtn').setAttribute('aria-pressed',String(state.compare));C.drawItemECG('case');C.persist();});
$('caseCaliperBtn')?.addEventListener('click',()=>{caseCaliperOn=!caseCaliperOn;$('caseCaliperBtn').classList.toggle('active',caseCaliperOn);$('caseCaliperBtn').setAttribute('aria-pressed',String(caseCaliperOn));$('caseCaliper').hidden=!caseCaliperOn;if(!caseCaliperOn){casePoints=[];$('caseMeasureOut').textContent='Kaliperle iki noktaya tıkla: Δt ve ΔV okunur.';}else{$('caseMeasureOut').textContent='İki noktaya tıkla: Δt ve ΔV okunur.';}});
$('caseEcgCanvas')?.addEventListener('click',event=>{if(!caseCaliperOn)return;const r=$('caseEcgCanvas').getBoundingClientRect(),point={x:(event.clientX-r.left)/r.width,y:(event.clientY-r.top)/r.height};if(casePoints.length>=2)casePoints=[];casePoints.push(point);renderCaseCaliper();});
$('caseGoQuestion')?.addEventListener('click',()=>$('caseQuestionCard')?.scrollIntoView({block:'start'}));
$('caseExpand')?.addEventListener('click',()=>{state.returnContext={sessionId:state.caseSession.id,itemId:item.id,index:i};$('returnToCaseBtn').hidden=false;C.setMode(item.mode);if(item.ecg.options.afProfile)C.setAfProfile(item.ecg.options.afProfile);for(let j=0;j<3;j++){const groups=[['I','II','III'],['aVR','aVL','aVF'],['V1','V2','V3','V4','V5','V6']];if(groups[j].includes(item.ecg.leads[j]))C.setLead(j,item.ecg.leads[j]);}C.seek(item.ecg.start+item.ecg.seconds);C.showView('sim');});
$('caseEndReview')?.addEventListener('click',()=>{const firstWrong=state.caseCorrect.findIndex(correct=>!correct);state.currentCase=firstWrong<0?0:firstWrong;renderCase();C.persist();});
$('caseEndAssessment')?.addEventListener('click',()=>C.showView('quiz'));$('caseEndReport')?.addEventListener('click',()=>window.CardAResults?.show('case'));
$('caseEnd')?.querySelectorAll('[data-case-index]').forEach(button=>button.addEventListener('click',()=>{state.currentCase=Number(button.dataset.caseIndex);renderCase();C.persist();}));
}
function restoreCases(){renderCase();C.progress();}
$('casePrev').addEventListener('click',()=>{state.currentCase=Math.max(0,state.currentCase-1);renderCase();C.persist();});$('caseNext').addEventListener('click',()=>{state.currentCase=Math.min(9,state.currentCase+1);renderCase();C.persist();});
$('returnToCaseBtn').addEventListener('click',()=>{const context=state.returnContext;if(context?.sessionId===state.caseSession.id&&state.caseSession.ids[context.index]===context.itemId)state.currentCase=context.index;state.returnContext=null;$('returnToCaseBtn').hidden=true;C.showView('case');});
document.addEventListener('click',event=>{const target=event.target.closest('#retryCaseSession,#newCaseSession');if(!target)return;C[target.id==='retryCaseSession'?'retrySample':'newSample']('case');});
window.addEventListener('cardai:session',e=>{if(e.detail.section==='case')renderCase();$('returnToCaseBtn').hidden=true;});
$('cancelChallenge').addEventListener('click',()=>{activeChallenge=null;$('challengeBanner').hidden=true;});

// Educator summary, CSV export, and explicit reset.
const featureNames={fullscreen:'Tam ekran',focus:'Panel odağı',compare:'Normal karşılaştırma',caliper:'Kaliper',guide:'Rehberli tur',systematic:'Sistematik okuma',cases:'Vaka çalışmaları'};
window.addEventListener('cardai:view',e=>{if(e.detail.view==='case')renderCase();});
$('downloadReport').addEventListener('click',()=>{const q=s=>`"${String(s).replaceAll('"','""')}"`,rows=[['EGEMED PULSE Raporu','2026'],['Ritim','İzleme (sn)','Durum'],...Object.entries(state.viewed).map(([k,v])=>[k,v.toFixed(1),v>=16?'Tamamlandı':'Sürüyor']),[],['Test puanı',state.score??'Değerlendirilmedi'],['Başarı',state.passed?'Evet':'Hayır'],['Yanıtlanan vaka',state.caseAnswers.filter(x=>x!==null).length+'/10'],['Doğru vaka',state.caseCorrect.filter(Boolean).length+'/10'],[],['Araç','Kullanım'],...Object.entries(featureNames).map(([k,n])=>[n,state.features[k]])];const blob=new Blob(['\ufeff'+rows.map(r=>r.map(q).join(';')).join('\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='EGEMED_PULSE_rapor.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('reportStatus').textContent='CSV raporu indirildi.';});
$('resetProgress').addEventListener('click',()=>$('resetDialog').showModal());$('closeReset').addEventListener('click',()=>$('resetDialog').close());$('cancelReset').addEventListener('click',()=>$('resetDialog').close());$('confirmReset').addEventListener('click',()=>{$('resetDialog').close();activeChallenge=null;caliperVisible=false;C.resetAll();$('reportStatus').textContent='İlerleme sıfırlandı.';});
window.addEventListener('cardai:reset',()=>{$('caliperLayer').hidden=true;$('compareKey').hidden=true;$('guidedCoach').hidden=true;$('returnToCaseBtn').hidden=true;applyScale();setFocus('split');restoreCases();renderSystematic();});

// Keyboard controls are ignored while the learner is editing a form control.
document.addEventListener('keydown',e=>{if(!e.isTrusted||document.body.classList.contains('landing-open')||e.altKey||e.ctrlKey||e.metaKey||['INPUT','SELECT','TEXTAREA','BUTTON'].includes(e.target.tagName)||document.querySelector('dialog[open]'))return;const k=e.key.toLowerCase(),modeKeys=window.CardAIModel.MODES;if(['1','2','3','4','5','6','7','8','9'].includes(k)){C.showView('sim');C.selectMode(modeKeys[Number(k)-1],e);}else if(k==='['||k===']'){const i=modeKeys.indexOf(state.mode),next=(i+(k===']'?1:-1)+modeKeys.length)%modeKeys.length;C.showView('sim');C.selectMode(modeKeys[next],e);}else if(k==='f')toggleFullscreen();else if(k==='c')toggleCaliper();else if(e.key==='ArrowRight'){e.preventDefault();C.seek(C.model.nextEvent(state.time));}else if(e.key==='ArrowLeft'){e.preventDefault();const times=C.model.eventTimes(Math.max(0,state.time-2),state.time-.005);C.seek(times[times.length-1]??Math.max(0,state.time-.1));}else if(e.key==='Escape'){setFocus('split');toggleGuide(false);}});

// İlk kullanım öğreticisi: gerçek sahnede üç adım; gözlem sayacına dokunmaz (activeView='tutorial').
const TUTORIAL=[['Bir örüntü kartı seç','Yatay şeritten bir ritim seçin; kalp, EKG ve açıklama birlikte güncellenir.'],['EKG’yi oynat ve bir derivasyona tıkla','Oynat’a basın ve izlerden birine tıklayarak o derivasyonu ölçüme seçin.'],['Kaliperi aç ve ölçüm yap','Kaliper’i açıp iki çizgiyi sürükleyin; süre ve voltaj farkı okunur.']];
let tutorialStep=0,tutorialSeen=false,tutorialTimer=null;
function shouldRunTutorial(){const anyProgress=Object.values(state.viewed).some(value=>value>0)||state.caseSubmitted.some(Boolean)||state.quizSubmitted.some(Boolean);return !state.tutorialDone&&!tutorialSeen&&!anyProgress;}
function renderTutorial(){const list=$('tutorialSteps');if(!list)return;list.innerHTML=TUTORIAL.map((row,i)=>`<li class="${i<tutorialStep?'done':i===tutorialStep?'current':''}"><span class="n"><span>${i+1}</span></span><span><b>${row[0]}</b><span class="t">${row[1]}</span></span></li>`).join('');const next=$('tutorialNext');next.disabled=false;next.textContent=tutorialStep>=TUTORIAL.length?'Mod seçimine geç →':'Sonraki adım';}
function completeStep(i){if(i!==tutorialStep)return;tutorialStep++;renderTutorial();if(tutorialStep>=TUTORIAL.length)clearTimeout(tutorialTimer),tutorialTimer=setTimeout(endTutorial,1400);}
function startTutorial(){tutorialSeen=true;tutorialStep=0;$('tutorialDontShow').checked=false;renderTutorial();}
function endTutorial(){clearTimeout(tutorialTimer);if($('tutorialDontShow').checked){state.tutorialDone=true;C.persist();}C.showView('modes');}
$('tutorialSkip').addEventListener('click',()=>endTutorial());
$('tutorialNext').addEventListener('click',()=>{if(tutorialStep<TUTORIAL.length)completeStep(tutorialStep);else endTutorial();});
document.querySelector('.rhythm-tabs').addEventListener('click',()=>completeStep(0),true);
$('caliperBtn').addEventListener('click',()=>{if(!$('caliperLayer').hidden)completeStep(2);},true);
$('ecgCanvas').addEventListener('click',()=>{if(C.playing)completeStep(1);if(!$('caliperLayer').hidden)completeStep(2);});
window.CardAITutorial={shouldRun:shouldRunTutorial,start:startTutorial,end:endTutorial};
// Hakkında görünümü: atıf, kurum ve kaynak verisi (sources.json tek kaynak).
const esc=value=>String(value).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const TITLES=new Set(['Prof.','Doç.','Dr.','Öğr.','Uzm.','Arş.','Gör.','Op.']);
const initials=name=>name.split(/\s+/).filter(w=>!TITLES.has(w)).slice(0,2).map(w=>w[0]).join('').toLocaleUpperCase('tr');
const ICO={heart:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 21C7 17.5 2 13.4 2 8.9 2 6.2 4.2 4 6.9 4c1.7 0 3.2.8 4.1 2.1L12 7.6l1-1.5C13.9 4.8 15.4 4 17.1 4 19.8 4 22 6.2 22 8.9c0 4.5-5 8.6-10 12.1z"/></svg>',doc:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 2h7l5 5v15H7zM14 2v5h5M10 13h5M10 17h5"/></svg>',book:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 4h7v16H4zM13 4h7v16h-7z"/></svg>',warn:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3 2 20h20zM12 9v5M12 17h.01"/></svg>'};
let aboutData=null;
function aboutSection(icon,title,body){return '<section class="about-section"><h2><span class="ico">'+ICO[icon]+'</span>'+title+'</h2>'+body+'</section>';}
function creditsCards(){return '<div class="credit-groups">'+(aboutData.credits||[]).map(group=>'<div class="credit-group lead"><span class="credit-role">'+esc(group.role)+'</span><ul class="credit-people">'+(group.people||[]).map(person=>{const body='<span class="credit-avatar">'+esc(initials(person.name))+'</span><span>'+esc(person.name)+'</span>'+(person.url?'<span class="ext" aria-hidden="true">↗</span>':'');return '<li>'+(person.url?'<a class="credit-person" href="'+esc(person.url)+'" target="_blank" rel="noreferrer">'+body+'</a>':'<span class="credit-person placeholder">'+body+'</span>')+'</li>';}).join('')+'</ul></div>').join('')+'</div>';}
function institutionCard(){const m=aboutData.module||{},ev=m.evidence||{},logoSrc=$('instLogo')?.getAttribute('src')||m.logo||'assets/brand/ege-tip-seal-128.png';return '<div class="inst-card"><img src="'+esc(logoSrc)+'" alt="Ege Üniversitesi Tıp Fakültesi"><div><h3>'+esc((m.name||'EGEMED Pulse™')+' — '+(m.subtitle||''))+'</h3><p>'+esc(m.description||'')+'</p>'+(ev.statement?'<p class="inst-evidence">'+esc(ev.statement)+(ev.url?'<sup><a href="'+esc(ev.url)+'" target="_blank" rel="noreferrer" aria-label="Kaynak">[1]</a></sup>':'')+'<br><span class="inst-cite">[1] '+esc(ev.citation||'')+(ev.url?' <a href="'+esc(ev.url)+'" target="_blank" rel="noreferrer">doi:'+esc(ev.doi||ev.url)+'</a>':'')+'</span></p>':'')+'</div></div>';}
function referenceCards(){return '<div class="ds-grid">'+(aboutData.references||[]).map(ref=>'<article class="ds-card"><h3>'+esc(ref.title)+'</h3><span class="org">'+esc(ref.org)+' · '+esc(ref.year)+'</span><p>'+esc(ref.use||'')+'</p><dl><dt>Bağlantı</dt><dd><a href="'+esc(ref.url)+'" target="_blank" rel="noreferrer">'+esc(ref.id)+'</a></dd></dl></article>').join('')+'</div>';}
function limitationsBox(){const items=[window.PulseCurriculum.limitations,'Simülasyon eğitim amaçlıdır; tek başına klinik tanı koymak için kullanılamaz.','EKG sinyalleri sentetiktir; harici EKG veri seti kullanılmamıştır. Atıf ve katkı verileri sources.json dosyasında saklanır.'];return '<p class="about-note">'+items.map(esc).join(' ')+'</p>';}
function renderAbout(){const node=$('pulse-sources'),inline=node&&node.textContent.trim();const ready=aboutData?Promise.resolve(aboutData):(inline?Promise.resolve(JSON.parse(inline)):fetch('sources.json').then(r=>r.ok?r.json():Promise.reject(new Error('sources'))));ready.then(data=>{aboutData=data;$('aboutSub').textContent='EGEMED Pulse™ Etkileşimli EKG Simülatörü’nü geliştiren ekip, kurum bilgisi ve modülde kullanılan EKG verilerinin atıf ve lisans bilgileri.';$('aboutContent').innerHTML=aboutSection('heart','Geliştiriciler',creditsCards())+aboutSection('doc','Kurum',institutionCard())+aboutSection('book','Kaynaklar',referenceCards())+aboutSection('warn','Sınırlılıklar ve sorumluluk',limitationsBox());}).catch(()=>{$('aboutSub').textContent='Kaynak verisi yüklenemedi.';$('aboutContent').innerHTML='<p class="view-intro">Atıf verisi bu ortamda okunamadı; paketlenmiş sürümde çevrimdışı da çalışır.</p>';});}
$('aboutBtn').addEventListener('click',()=>C.showView('about'));
window.addEventListener('cardai:view',event=>{if(event.detail.view==='about')renderAbout();});
// Sonuçlar görünümü (Faz E — Ausculta ResultsScreen.tsx): özet şerit, alan performansı, tablo raporu.
const OBJECTIVE_LABELS={O1:'Sistematik EKG okuma',O2:'Ritim tanıma ve ayırıcı tanı',O3:'Derivasyon ve bölge bilgisi',O4:'Elektrik–mekanik ayrım',O5:'Klinik bağlam ve sınırlar',O6:'Hız, aralık ve düzen'};
const OBJECTIVE_ICONS={O1:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01"/></svg>',O2:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M2 12h3l2-6 3 12 3-9 2.5 5.5L18 9l2 3h2"/></svg>',O3:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M8 3v18M16 3v18M2 9h4M18 9h4M2 15h4M18 15h4"/></svg>',O4:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M19 14c1.5-1.5 3-3.2 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.8 0-3 .5-4.5 2-1.5-1.5-2.7-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4 3 5.5l6.5 6.5z"/></svg>',O5:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 11v6"/><circle cx="12" cy="7.5" r=".5" fill="currentColor"/></svg>',O6:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3.5 2"/></svg>'};
let resultsVariant='quiz',expandedReport=null;
function formatDuration(ms){const total=Math.max(0,Math.round(ms/1000));return String(Math.floor(total/60)).padStart(2,'0')+':'+String(total%60).padStart(2,'0');}
function rowsFor(section){const session=section==='quiz'?state.quizSession:state.caseSession,submitted=section==='quiz'?state.quizSubmitted:state.caseSubmitted,answers=section==='quiz'?state.answers:state.caseAnswers;return session.ids.map((id,i)=>{const item=window.PulseCurriculum.byId[id];return {i,id,item,answer:answers[i],submitted:submitted[i],ok:!!submitted[i]&&answers[i]===item.correct};});}
function domainRows(rows){const groups={};for(const row of rows)for(const objective of row.item.objectiveIds||[]){const group=groups[objective]||(groups[objective]={total:0,correct:0});group.total++;if(row.ok)group.correct++;}return Object.entries(groups).map(([id,value])=>({id,label:OBJECTIVE_LABELS[id]||id,...value,pct:Math.round(value.correct/value.total*100)})).sort((a,b)=>a.pct-b.pct);}
function reportRows(rows,section){const header=section==='quiz'?'<tr><th></th><th>Soru</th><th>Puan</th><th>Sonuç</th></tr>':'<tr><th></th><th>Vaka</th><th>Sonuç</th></tr>';
const body=rows.map(row=>{const isOpen=expandedReport===row.id,titleText=row.item.question||row.item.title||'',short=titleText.length>70?titleText.slice(0,69)+'…':titleText,cols=section==='quiz'?4:3;
const scoreCell=section==='quiz'?`<td>${row.submitted?(row.ok?10:0):'—'}/10</td>`:'';
const main=`<tr class="report-row-v2" data-report-toggle="${row.id}"><td class="report-chev"><svg class="${isOpen?'rot':''}" viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m9 5 7 7-7 7"/></svg></td><td>${esc(short)}</td>${scoreCell}<td class="${row.ok?'ok':'no'}">${row.ok?'Doğru':'Yanlış'}</td></tr>`;
const detail=isOpen?`<tr class="report-detail-row-v2"><td colspan="${cols}"><ul class="report-detail-list"><li class="${row.ok?'ok':'no'}"><span class="rd-q">${esc(row.item.question||'')}</span><span class="rd-mark">${row.ok?'✓':'✗'}</span><span class="rd-given">Verilen yanıt: ${row.answer===null?'—':esc('ABCDE'[row.answer]+'. '+row.item.options[row.answer])}</span><span class="rd-correct">Doğru yanıt: ${esc('ABCDE'[row.item.correct]+'. '+row.item.options[row.item.correct])}</span><span class="rd-feedback">${esc(row.item.explanations[row.item.correct]+(!row.ok&&row.answer!==null?' Seçtiğiniz seçenek neden değil: '+row.item.explanations[row.answer]:''))}</span></li></ul></td></tr>`:'';
return main+detail;}).join('');
return `<table class="report-table-v2"><thead>${header}</thead><tbody>${body}</tbody></table>`;}
function renderResults(){const section=resultsVariant==='case'?'case':'quiz',rows=rowsFor(section),correct=rows.filter(row=>row.ok).length,score=section==='quiz'?(state.attemptScore??correct*10):correct*10,passed=section==='quiz'?state.passed:correct>=8,domains=domainRows(rows);
$('resultsTitle').textContent=section==='quiz'?'Değerlendirme Tamamlandı':'Vaka Raporu';
$('resultsLead').textContent=passed?(section==='quiz'?'Tebrikler — performansınız hedefin üzerinde. Bu düzeyi korumak için İnceleme modunda farklı örüntülerle çalışmaya devam edebilirsiniz.':'Bu oturumda hedefin üzerinde bir performans gösterdiniz. İnceleme modunda farklı örüntülerle çalışmaya devam edebilirsiniz.'):(section==='quiz'?'Hedef puanın altında kaldınız. İnceleme modunda ilgili örüntüleri tekrar izleyip Uygulama modunda yeniden denemeniz önerilir.':'Bu oturumda hedefin altında kaldınız (8/10 altı). İnceleme modunda ilgili örüntüleri tekrar izlemeniz önerilir.');
const weak=domains.filter(domain=>domain.pct<60);
const weakRow=weak.length?`<div class="weak-chip-row" aria-label="Zayıf alanlar"><span class="weak-chip-lbl">Zayıf alanlar:</span>${weak.map(domain=>{const row=rows.find(entry=>!entry.ok&&(entry.item.objectiveIds||[]).includes(domain.id))||rows.find(entry=>(entry.item.objectiveIds||[]).includes(domain.id));const mode=row?row.item.ecg.mode:'normal';return `<button type="button" class="badge orange weak-chip" data-study-mode="${mode}">${esc(domain.label)} · %${domain.pct}</button>`;}).join('')}</div>`:'';
const boxes=[`<div class="rs-box"><div class="rs-ring-sm ${passed?'pass':'fail'}"><svg viewBox="0 0 80 80"><circle class="track" cx="40" cy="40" r="34" fill="none" stroke-width="8"/><circle class="prog" cx="40" cy="40" r="34" fill="none" stroke-width="8" stroke-linecap="round" stroke-dasharray="${(score/100*2*Math.PI*34).toFixed(1)} 999" transform="rotate(-90 40 40)"/></svg><b>${score}</b></div><span class="rs-lbl">Toplam puan</span></div>`,`<div class="rs-box"><div class="rs-status ${passed?'pass':'fail'}">${passed?'✓ Başarılı':'✕ Hedefin altında'}</div><span class="rs-lbl">Durum (eşik 80)</span></div>`];
if(section==='quiz')boxes.push(`<div class="rs-box"><div class="rs-num">⏱ ${formatDuration(state.learningMs)}</div><span class="rs-lbl">Süre</span></div>`);
boxes.push(`<div class="rs-box"><div class="rs-num">${rows.length}</div><span class="rs-lbl">${section==='quiz'?'Soru sayısı':'Vaka sayısı'}</span></div>`);
const domainCard=domains.length?`<div class="card mt-16"><h3 style="margin-top:0">Alan bazlı performans</h3><div class="domain-rows">${domains.map(domain=>`<div class="domain-row-v2${domain.pct<60?' low':''}"><span class="dr-ic">${OBJECTIVE_ICONS[domain.id]||''}</span><span class="dr-lbl">${esc(domain.label)}</span><span class="domain-bar"><i style="width:${domain.pct}%"></i></span><span class="dr-pct" title="${domain.correct}/${domain.total} doğru">%${domain.pct}</span></div>`).join('')}</div></div>`:'';
const reportCard=`<div class="card mt-16"><h3 style="margin-top:0">${section==='quiz'?'Soru raporu':'Vaka raporu'}</h3><div class="table-scroll">${reportRows(rows,section)}</div></div>`;
const exitAction=section==='quiz'?'<button type="button" class="primary-btn" id="resultsExit">⏏ Modülden Çık</button>':'<button type="button" class="primary-btn" id="resultsToQuiz">Değerlendirmeye gir →</button>';
$('resultsBody').innerHTML=`${weakRow}<div class="results-summary-strip">${boxes.join('')}</div>${domainCard}${reportCard}<div class="results-actions">${exitAction}<button type="button" class="secondary-btn" id="resultsRetry">Tekrar dene</button><button type="button" class="secondary-btn" id="resultsStudy">İnceleme modunda çalış</button><button type="button" class="secondary-btn" id="resultsNew">Yeni ${section==='quiz'?'10 soru':'10 vaka'} örneklemi</button></div>`;
$('resultsRetry').addEventListener('click',()=>C.retrySample(section));$('resultsNew').addEventListener('click',()=>C.newSample(section));$('resultsStudy').addEventListener('click',()=>C.showView('sim'));
$('resultsExit')?.addEventListener('click',()=>$('finishDialog').showModal());$('resultsToQuiz')?.addEventListener('click',()=>C.showView('quiz'));
$('resultsBody').querySelectorAll('[data-study-mode]').forEach(button=>button.addEventListener('click',()=>{C.setMode(button.dataset.studyMode);C.showView('sim');}));
$('resultsBody').querySelectorAll('[data-report-toggle]').forEach(button=>button.addEventListener('click',()=>{expandedReport=expandedReport===button.dataset.reportToggle?null:button.dataset.reportToggle;renderResults();}));}
window.CardAResults={show(variant){resultsVariant=variant||'quiz';expandedReport=null;C.showView('results');}};
window.addEventListener('cardai:view',event=>{if(event.detail.view==='results')renderResults();});
$('closeFinish')?.addEventListener('click',()=>$('finishDialog').close());$('cancelFinish')?.addEventListener('click',()=>$('finishDialog').close());$('confirmFinish')?.addEventListener('click',()=>{$('finishDialog').close();S.finish(state);window.CardAILanding?.showLanding();});
applyScale();restoreCases();syncModeTools();$('returnToCaseBtn').hidden=!state.returnContext;
document.querySelectorAll('.caliper-handle').forEach(h=>h.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const p=state.caliper[h.dataset.handle],step=e.shiftKey?.02:.005;if(e.key==='ArrowLeft')p.x=clamp(p.x-step,.02,.98);if(e.key==='ArrowRight')p.x=clamp(p.x+step,.02,.98);if(e.key==='ArrowUp')p.y=clamp(p.y-step,.04,.96);if(e.key==='ArrowDown')p.y=clamp(p.y+step,.04,.96);renderCalipers();C.persist();}));
})();
