(function(){'use strict';
const $=id=>document.getElementById(id),C=window.CardAIController,S=window.CardAIScorm,state=C.state,clamp=window.CardAIModel.clamp;
let activeChallenge=null,guideIndex=0,caliperVisible=false,caliperTurn='a',dragHandle=null,ignoreCanvasClick=false;
const stValue=()=>((state.mode==='inferior'?window.CardAIModel.inferiorST:window.CardAIModel.anteriorST)[state.lead]||0);

// Fullscreen and panel focus keep the simulator usable on a 16:9 teaching display.
async function toggleFullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await $('appRoot').requestFullscreen();C.markFeature('fullscreen');}catch{$('saveStatus').textContent='Bu tarayıcı tam ekran isteğini engelledi.';}}
function syncFullscreen(){const on=!!document.fullscreenElement;$('fullscreenBtn').textContent=on?'↙':'↗';$('fullscreenBtn').setAttribute('aria-label',on?'Tam ekrandan çık':'Tam ekrana geç');$('transportFullscreen').textContent=on?'↙ Tam ekrandan çık':'↗ Tam ekran';requestAnimationFrame(C.resize);}
$('fullscreenBtn').addEventListener('click',toggleFullscreen);$('transportFullscreen').addEventListener('click',toggleFullscreen);document.addEventListener('fullscreenchange',syncFullscreen);
function setFocus(which){const app=$('appRoot'),current=app.dataset.focus||'split',target=which!=='split'&&current===which?'split':which;app.dataset.focus=target==='split'?'':target;$('splitFocusBtn').classList.toggle('active',target==='split');document.querySelectorAll('.panel-focus').forEach(b=>{const active=b.dataset.focusPanel===target;b.classList.toggle('active',active);b.textContent=active?'↙':'↗';b.setAttribute('aria-label',active?'Paneli küçült ve bölünmüş görünüme dön':({anatomy:'Kalbi büyüt',ecg:'EKG’yi büyüt',explanation:'Açıklamayı büyüt'}[b.dataset.focusPanel]));});if(target!=='split')C.markFeature('focus');requestAnimationFrame(C.resize);}
document.querySelectorAll('[data-focus-panel]').forEach(b=>b.addEventListener('click',()=>setFocus(b.dataset.focusPanel)));

// The interface uses one validated 120% typography scale so 16:9 panel geometry stays stable.
function applyScale(){state.uiScale=120;$('appRoot').style.setProperty('--ui-font-scale','1.2');requestAnimationFrame(C.resize);}

// Anatomy layer switches.
for(const [control,target] of [['flowToggle','particles'],['valveToggle','valves'],['coronaryToggle','coronaries']])$(control).addEventListener('change',()=>{$(target).style.display=$(control).checked?'':'none';if(control==='coronaryToggle')$('ischemiaLabel').style.display=$(control).checked?'':'none';});

// Explanatory views and the six-step systematic reading checklist.
const systematic={
 normal:[['Hız','75/dk'],['Ritim','Düzenli'],['P dalgası','Her QRS öncesinde var'],['PR','Yaklaşık 175 ms'],['QRS','Dar · 80 ms'],['ST–T','İzoelektrik ST, pozitif T']],
 af:[['Hız',()=>state.afProfile==='rapid'?'Yaklaşık 110–175/dk':'Yaklaşık 60–100/dk'],['Ritim','Düzensiz düzensiz'],['P dalgası','Seçilemez; f dalgaları'],['PR','Ölçülemez'],['QRS','Genellikle dar · 80 ms'],['ST–T','Bu örnekte akut ST yükselmesi yok']],
 stemi:[['Hız','75/dk'],['Ritim','Düzenli sinüs ritmi'],['P dalgası','Her QRS öncesinde var'],['PR','Yaklaşık 175 ms'],['QRS','Dar · 80 ms'],['ST–T',()=>state.lead+' derivasyonunda J noktası +'+stValue().toFixed(2).replace('.',',')+' mV']],
 pvc:[['Hız','Temel sinüs hızı 75/dk'],['Ritim','Aralıklı erken ventriküler atım'],['P dalgası','PVC öncesinde ilişkili P yok'],['PR','Sinüs atımlarında yaklaşık 175 ms'],['QRS','PVC’de geniş · yaklaşık 140 ms'],['ST–T','PVC sonrası diskordan değişiklik']],
 svt:[['Hız','Yaklaşık 167/dk'],['Ritim','Düzenli taşikardi'],['P dalgası','Bu örnekte seçilemiyor'],['PR','Ölçülemez'],['QRS','Dar · 80 ms'],['ST–T','Kısa döngü nedeniyle T sonraki komplekse yakın']],
 inferior:[['Hız','75/dk'],['Ritim','Düzenli sinüs ritmi'],['P dalgası','Her QRS öncesinde var'],['PR','Yaklaşık 175 ms'],['QRS','Dar · 80 ms'],['ST–T',()=>state.lead+' J noktası '+(stValue()>=0?'+':'')+stValue().toFixed(2).replace('.',',')+' mV']],
 vt:[['Hız','Yaklaşık 158/dk'],['Ritim','Düzenli ventriküler taşikardi'],['P dalgası','QRS ile sabit ilişki yok'],['PR','Ölçülemez'],['QRS','Geniş · yaklaşık 180 ms'],['ST–T','Geniş komplekse sekonder diskordans']],
 vf:[['Hız','Hesaplanamaz'],['Ritim','Kaotik'],['P dalgası','Seçilemez'],['PR','Ölçülemez'],['QRS','Organize kompleks yok'],['ST–T','Ayırt edilemez']],
 pat:[['Hız','Yaklaşık 150/dk'],['Ritim','Düzenli atriyal taşikardi'],['P dalgası','Ektopik morfoloji'],['PR','Kısa/sabit örnek'],['QRS','Dar · 80 ms'],['ST–T','Hız nedeniyle T–P yakın']],
 flutter:[['Hız','Atriyal 300 · ventriküler 150/dk'],['Ritim','Düzenli 2:1 iletim'],['P dalgası','P yok; sürekli F dalgaları'],['PR','Ölçülemez'],['QRS','Dar · 80 ms'],['ST–T','F dalgaları temel hattı doldurur']],
 sintach:[['Hız','Yaklaşık 120/dk'],['Ritim','Düzenli sinüs taşikardisi'],['P dalgası','Her QRS öncesinde sinüs P'],['PR','Sabit'],['QRS','Dar · 80 ms'],['ST–T','Bu örnekte akut değişiklik yok']],
 lbbb:[['Hız','75/dk'],['Ritim','Düzenli sinüs ritmi'],['P dalgası','Her QRS öncesinde var'],['PR','Yaklaşık 175 ms'],['QRS','Geniş · yaklaşık 160 ms'],['ST–T','QRS’ye sekonder diskordans']],
 rbbb:[['Hız','75/dk'],['Ritim','Düzenli sinüs ritmi'],['P dalgası','Her QRS öncesinde var'],['PR','Yaklaşık 175 ms'],['QRS','Geniş · yaklaşık 140 ms'],['ST–T','V1–V3’te sekonder değişiklik']]
};
function renderSystematic(){const rows=systematic[state.mode];$('systematicList').innerHTML=rows.map(([name,value],i)=>{const key=state.mode+':'+i;return `<label class="systematic-item"><input type="checkbox" data-check="${key}" ${state.checklist[key]?'checked':''}><span><b>${name}</b><span>${typeof value==='function'?value():value}</span></span></label>`;}).join('');$('systematicList').querySelectorAll('[data-check]').forEach(input=>input.addEventListener('change',()=>{state.checklist[input.dataset.check]=input.checked;C.persist();updateSystematicResult();}));updateSystematicResult();}
function updateSystematicResult(){const done=systematic[state.mode].filter((_,i)=>state.checklist[state.mode+':'+i]).length;$('systematicResult').textContent=done===6?'6/6 adım tamamlandı. Bulguları mekanizma ve klinik bağlamla birlikte yorumla.':done+'/6 adım işaretlendi.';}
function showExplain(name){for(const n of ['mechanism','systematic','details']){$(n+'Panel').hidden=n!==name;document.querySelector(`[data-explain-tab="${n}"]`).classList.toggle('active',n===name);}if(name==='systematic'){renderSystematic();C.markFeature('systematic');}}
document.querySelectorAll('[data-explain-tab]').forEach(b=>b.addEventListener('click',()=>showExplain(b.dataset.explainTab)));

// Lead/profile variants and normal-reference overlay.
document.querySelectorAll('.lead-select').forEach((select,i)=>select.addEventListener('change',()=>{renderSystematic();if(['stemi','inferior'].includes(state.mode))showMeasurement('st');}));
$('afProfile').addEventListener('change',()=>{C.setAfProfile($('afProfile').value);renderSystematic();});
$('compareBtn').addEventListener('click',()=>{if(state.mode==='normal')return;state.compare=!state.compare;$('compareBtn').classList.toggle('active',state.compare);$('compareBtn').setAttribute('aria-pressed',String(state.compare));$('compareKey').hidden=!state.compare;if(state.compare)C.markFeature('compare',false);C.draw();C.persist();});
function syncModeTools(){renderSystematic();const comparing=state.compare&&!['normal','vf'].includes(state.mode);$('compareBtn').classList.toggle('active',comparing);$('compareBtn').setAttribute('aria-pressed',String(comparing));$('compareKey').hidden=!comparing;}
window.addEventListener('cardai:mode',syncModeTools);

// Preset and free caliper measurements.
function showMeasurement(kind){let label='';if(kind==='rr')label=C.snapshot.rr?'R–R: '+C.snapshot.rr+' ms':'R–R: ölçülemez';if(kind==='pr')label=window.CardAIModel.NO_P.includes(state.mode)?'PR: ölçülemez (belirgin P yok)':state.mode==='pvc'?'PR: sinüs atımlarında yaklaşık 175 ms':'PR: yaklaşık 175 ms';if(kind==='qrs')label=C.snapshot.qrs?'QRS: '+C.snapshot.qrs+' ms':'QRS: seçilemez';if(kind==='st')label=['stemi','inferior'].includes(state.mode)?'J noktası: '+(stValue()>=0?'+':'')+stValue().toFixed(2).replace('.',',')+' mV · '+state.lead:'ST–T: seçili derivasyonda sentetik örnek';$('measurementOutput').textContent=label;$('selectedMetric').textContent=label.split(':').slice(1).join(':').trim();$('measurementPresets').hidden=true;}
$('measureBtn').addEventListener('click',()=>{$('measurementPresets').hidden=!$('measurementPresets').hidden;});document.querySelectorAll('[data-measure]').forEach(b=>b.addEventListener('click',()=>showMeasurement(b.dataset.measure)));
document.addEventListener('click',e=>{if(!e.target.closest('#measureBtn')&&!e.target.closest('#measurementPresets'))$('measurementPresets').hidden=true;});
function renderCalipers(){const g=C.geom,a=state.caliper.a,b=state.caliper.b,ha=document.querySelector('.caliper-handle.a'),hb=document.querySelector('.caliper-handle.b');for(const [el,p] of [[ha,a],[hb,b]]){el.style.left=(p.x*100)+'%';el.style.top=(p.y*100)+'%';}const x1=a.x*g.cw,y1=a.y*g.ch,x2=b.x*g.cw,y2=b.y*g.ch,dx=x2-x1,dy=y2-y1,br=$('caliperBracket');br.style.left=x1+'px';br.style.top=y1+'px';br.style.width=Math.hypot(dx,dy)+'px';br.style.transform='rotate('+Math.atan2(dy,dx)+'rad)';if(g.pxPerSecond&&g.mv){const dt=Math.abs(dx/g.pxPerSecond),dmv=Math.abs(dy/g.mv);$('measurementOutput').textContent='Kaliper Δt '+Math.round(dt*1000)+' ms · ΔV '+dmv.toFixed(2).replace('.',',')+' mV';$('selectedMetric').textContent=Math.round(dt*1000)+' ms / '+dmv.toFixed(2).replace('.',',')+' mV';}}
function toggleCaliper(force){caliperVisible=typeof force==='boolean'?force:!caliperVisible;$('caliperLayer').hidden=!caliperVisible;$('caliperBtn').classList.toggle('active',caliperVisible);$('caliperBtn').setAttribute('aria-pressed',String(caliperVisible));if(caliperVisible){renderCalipers();C.markFeature('caliper');}}
$('caliperBtn').addEventListener('click',()=>toggleCaliper());
document.querySelectorAll('.caliper-handle').forEach(h=>h.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();dragHandle=h.dataset.handle;h.setPointerCapture?.(e.pointerId);ignoreCanvasClick=true;}));
window.addEventListener('pointermove',e=>{if(!dragHandle)return;const r=$('ecgScreen').getBoundingClientRect();state.caliper[dragHandle]={x:clamp((e.clientX-r.left)/r.width,.02,.98),y:clamp((e.clientY-r.top)/r.height,.04,.96)};renderCalipers();});
window.addEventListener('pointerup',()=>{if(dragHandle){dragHandle=null;C.persist();setTimeout(()=>ignoreCanvasClick=false,20);}});

// Wave picking maps a click back to the same model time used by heart and circulation.
function nearestBeat(t){return C.model.between(t-.55,t+.55).sort((a,b)=>Math.abs(a.r-t)-Math.abs(b.r-t))[0];}
function classifyWave(t,b){const d=t-b.r;let candidates;if(state.mode==='vf')return ['Kaotik VF dalgası',d,'qrs'];if(['af','flutter'].includes(state.mode))candidates=[['QRS kompleksi',0,'qrs'],[state.mode==='flutter'?'F dalgaları':'f dalgaları',.12,'eject'],['T dalgası',.245,'t']];else if(state.mode==='vt')candidates=[['Geniş VT kompleksi',.04,'qrs'],['Sekonder ST–T',.245,'t']];else if(['svt','pat','sintach'].includes(state.mode))candidates=[...(state.mode==='pat'?[['Ektopik P dalgası',-.125,'atrial']]:state.mode==='sintach'?[['Sinüs P dalgası',-.17,'atrial']]:[]),['QRS kompleksi',0,'qrs'],['T dalgası',.20,'t']];else if(b.isPVC)candidates=[['Geniş PVC kompleksi',0,'qrs'],['PVC sonrası ST',.14,'eject'],['Diskordan T dalgası',.285,'t']];else candidates=[['P dalgası',-.17,'atrial'],['QRS kompleksi',0,'qrs'],['ST segmenti',.12,'eject'],['T dalgası',.245,'t']];let hit=candidates.sort((a,c)=>Math.abs(d-a[1])-Math.abs(d-c[1]))[0];return Math.abs(d-hit[1])<.12?hit:(['af','flutter'].includes(state.mode)?[state.mode==='flutter'?'F dalgaları':'f dalgaları',d,'fill']:null);}
function completeChallenge(type){if(state.challengeCorrect[type])return;state.challengeCorrect[type]=true;$('challengeTitle').textContent='Doğru';$('challengeText').textContent=type==='rr'?'En uzun R–R aralığını buldun.':'ST segmentini doğru gösterdin.';CardAIScorm.interaction(type==='rr'?7:8,0,true);C.markFeature('cases',false);C.persist();setTimeout(()=>{activeChallenge=null;$('challengeBanner').hidden=true;},1400);}
function evaluateChallenge(t,b){if(activeChallenge==='st'){const d=t-b.r;if(d>=.04&&d<=.20){completeChallenge('st');return true;}$('challengeText').textContent='J noktasından sonraki yükselmiş bölgeyi seç.';return false;}if(activeChallenge==='rr'){const g=C.geom,beats=C.model.between(g.leftTime-.1,state.time-.05);let longest=null;for(let i=1;i<beats.length;i++){const row={a:beats[i-1],b:beats[i],rr:beats[i].r-beats[i-1].r};if(!longest||row.rr>longest.rr)longest=row;}if(longest&&Math.abs(t-(longest.a.r+longest.b.r)/2)<Math.min(.24,longest.rr*.32)){completeChallenge('rr');return true;}$('challengeText').textContent='Görünen en geniş iki R tepesi arasını seç.';return false;}return false;}
$('ecgCanvas').addEventListener('click',e=>{if(ignoreCanvasClick)return;const r=$('ecgCanvas').getBoundingClientRect(),g=C.geom,x=e.clientX-r.left,y=e.clientY-r.top,col=g.columns?.find(c=>x>=c.offset&&x<=c.offset+c.width)||g;C.setLead(col.index??state.activeLead,col.lead||state.lead);if(caliperVisible){state.caliper[caliperTurn]={x:clamp(x/r.width,.02,.98),y:clamp(y/r.height,.04,.96)};caliperTurn=caliperTurn==='a'?'b':'a';renderCalipers();C.persist();return;}const t=col.leftTime+(x-(col.offset||0))/col.pxPerSecond,b=nearestBeat(t);if(!b)return;if(activeChallenge)evaluateChallenge(t,b);const hit=classifyWave(t,b);if(!hit)return;C.seek(b.r+hit[1]);const tip=$('waveTip');tip.textContent=(col.lead||state.lead)+' · '+hit[0]+' · '+(hit[2]==='eject'?'ventriküler kasılma ve ejeksiyon':hit[2]==='qrs'?'ventriküler depolarizasyon':hit[2]==='atrial'?'atriyal depolarizasyon':'repolarizasyon');tip.style.left=(Math.min(94,Math.max(6,x/r.width*100)))+'%';tip.style.top=(Math.min(88,Math.max(18,y/r.height*100)))+'%';tip.hidden=false;setTimeout(()=>tip.hidden=true,2200);});

// Guided teaching mode.
const guideSteps=[['atrial','P dalgası ve atriyum','Uyarı sinüs düğümünden atriyuma yayılır. Atriyal kasılma doluşu tamamlar.'],['qrs','QRS ve ventrikül','Ventriküler depolarizasyon mekanik kasılmadan hemen önce oluşur.'],['eject','ST ve ejeksiyon','Basınç yükselince çıkış kapakları açılır ve kan pulmoner arter ile aortaya pompalanır.'],['t','T dalgası','Ventriküler repolarizasyon, ejeksiyonun son bölümüyle örtüşebilir.'],['fill','Doluş','Ventrikül basıncı düşünce AV kapakları açılır ve döngü yeniden başlar.']];
function availableGuide(){return window.CardAIModel.NO_P.includes(state.mode)?guideSteps.filter(s=>s[0]!=='atrial'):guideSteps;}
function renderGuide(){const steps=availableGuide();guideIndex=(guideIndex+steps.length)%steps.length;const [phase,title,description]=steps[guideIndex];$('guideStep').textContent=(guideIndex+1)+'/'+steps.length;$('guideTitle').textContent=title;$('guideText').textContent=description;C.seek(C.model.phaseTime(state.time,phase));}
function toggleGuide(on=!$('guidedCoach').hidden){const show=typeof on==='boolean'?on:$('guidedCoach').hidden;$('guidedCoach').hidden=!show;$('guideBtn').classList.toggle('active',show);$('guideBtn').setAttribute('aria-pressed',String(show));if(show){guideIndex=0;C.markFeature('guide');renderGuide();}}
$('guideBtn').addEventListener('click',()=>toggleGuide($('guidedCoach').hidden));$('guidePrev').addEventListener('click',()=>{guideIndex--;renderGuide();});$('guideNext').addEventListener('click',()=>{guideIndex++;renderGuide();});$('guideClose').addEventListener('click',()=>toggleGuide(false));

// Fifty paginated cases keep the synthetic ECG and clinical question on one page.
const cases=window.PulseCurriculum.cases,caseLeadMap={D1:'I',D2:'II',D3:'III'};
function drawCaseECG(){const canvas=$('caseEcgCanvas');if(!canvas)return;const rect=canvas.getBoundingClientRect();if(rect.width<50||rect.height<50)return;const w=rect.width,h=rect.height,dpr=Math.min(devicePixelRatio||1,2);canvas.width=w*dpr;canvas.height=h*dpr;const x=canvas.getContext('2d');x.setTransform(dpr,0,0,dpr,0,0);x.fillStyle='#fffafb';x.fillRect(0,0,w,h);const item=cases[state.currentCase],model=C.models[item.mode],leads=(item.mode==='lbbb'?['I','aVL','V6']:item.mode==='rbbb'?['I','aVR','V1']:C.state.leads).map(l=>caseLeadMap[l]||l),gap=8,cw=(w-gap*2)/3,seconds=3.2,pps=(cw-12)/seconds,small=pps*.04,mv=small*10,base=h*.58;for(let c=0;c<3;c++){const ox=c*(cw+gap);x.save();x.beginPath();x.rect(ox,0,cw,h);x.clip();for(let gx=0;gx<cw;gx+=small){x.strokeStyle=Math.round(gx/small)%5===0?'#e6b9c2':'#f3d8dd';x.lineWidth=.55;x.beginPath();x.moveTo(ox+gx,0);x.lineTo(ox+gx,h);x.stroke();}for(let gy=base%small;gy<h;gy+=small){x.strokeStyle=Math.round(gy/small)%5===0?'#e6b9c2':'#f3d8dd';x.lineWidth=.55;x.beginPath();x.moveTo(ox,gy);x.lineTo(ox+cw,gy);x.stroke();}x.strokeStyle='#b4233a';x.lineWidth=2;x.beginPath();for(let px=0;px<cw-8;px+=.6){const t=.5+px/pps,y=base-model.signal(t,leads[c])*mv;if(px===0)x.moveTo(ox+px,y);else x.lineTo(ox+px,y);}x.stroke();x.fillStyle='#713442';x.font='700 12px ui-monospace,monospace';x.fillText(leads[c],ox+8,17);x.restore();if(c<2){x.fillStyle='#cbd8df';x.fillRect(ox+cw+gap/2-1,0,2,h);}}}
function renderCase(){const i=state.currentCase,item=cases[i],answer=state.caseAnswers[i],answered=state.caseAnswers.filter(x=>x!==null).length;$('casePager').innerHTML=`<article class="case-detail"><div class="case-ecg-wrap"><div class="case-ecg-head"><span>${item.lead} odak derivasyonu</span><button type="button" class="secondary-btn" id="caseExpand">EKG’yi simülasyonda aç ↗</button></div><canvas id="caseEcgCanvas" role="img" aria-label="${item.title} için üç derivasyonlu sentetik EKG"></canvas><p>EKG’yi klinik öyküyle birlikte incele ve en uygun yanıtı seç.</p></div><div class="case-question"><header><span>VAKA ${String(i+1).padStart(2,'0')}</span><h2>${item.title}</h2></header><p>${item.stem}</p><fieldset><legend>${item.question}</legend>${item.options.map((o,j)=>`<label><input type="radio" name="activeCase" value="${j}" ${answer===j?'checked':''}>${o}</label>`).join('')}</fieldset><button type="button" class="primary-btn" id="caseCheck">Yanıtı değerlendir</button><p class="case-feedback" id="caseFeedback">${answer===null?'':state.caseCorrect[i]?'Doğru. '+item.feedback:'Bu yanıt EKG bulgularıyla uyuşmuyor. Yeniden değerlendir.'}</p></div></article>`;$('casePageLabel').textContent=`Vaka ${String(i+1).padStart(2,'0')} / 50`;$('caseDots').textContent=(i+1)+' / 50';$('caseAnswered').textContent=`Yanıtlanan ${answered} / 50`;$('caseProgressBar').style.width=(answered*2)+'%';$('casePrev').disabled=i===0;$('caseNext').disabled=i===49;requestAnimationFrame(drawCaseECG);$('caseExpand').addEventListener('click',()=>{$('returnToCaseBtn').hidden=false;C.setMode(item.mode);C.showView('sim');});$('caseCheck').addEventListener('click',()=>{const picked=document.querySelector('input[name="activeCase"]:checked');if(!picked){$('caseFeedback').textContent='Önce bir seçenek işaretle.';return;}state.caseAnswers[i]=Number(picked.value);state.caseCorrect[i]=state.caseAnswers[i]===item.correct;$('caseFeedback').textContent=state.caseCorrect[i]?'Doğru. '+item.feedback:'Bu yanıt EKG bulgularıyla uyuşmuyor. Yeniden değerlendir.';S.interaction(50+i,state.caseAnswers[i],state.caseCorrect[i]);C.markFeature('cases',false);C.persist();renderCase();});}
function restoreCases(){renderCase();C.progress();}
$('casePrev').addEventListener('click',()=>{state.currentCase=Math.max(0,state.currentCase-1);renderCase();C.persist();});$('caseNext').addEventListener('click',()=>{state.currentCase=Math.min(49,state.currentCase+1);renderCase();C.persist();});$('returnToCaseBtn').addEventListener('click',()=>{$('returnToCaseBtn').hidden=true;C.showView('case');});
$('cancelChallenge').addEventListener('click',()=>{activeChallenge=null;$('challengeBanner').hidden=true;});

// Educator summary, CSV export, and explicit reset.
const featureNames={fullscreen:'Tam ekran',focus:'Panel odağı',compare:'Normal karşılaştırma',caliper:'Kaliper',guide:'Rehberli tur',systematic:'Sistematik okuma',cases:'Vaka çalışmaları'};
function renderEducator(){const observed=Object.values(state.viewed).filter(x=>x>=16).length,casesAnswered=state.caseAnswers.filter(x=>x!==null).length,casesCorrect=state.caseCorrect.filter(Boolean).length;$('educatorMetrics').innerHTML=`<div><span>Ritim</span><strong>${observed}/${window.CardAIModel.MODES.length}</strong></div><div><span>Vaka</span><strong>${casesAnswered}/50 · ${casesCorrect} doğru</strong></div><div><span>Test</span><strong>${state.score===null?'—':state.score}</strong></div><div><span>Durum</span><strong>${state.passed?'Başarılı':'Sürüyor'}</strong></div>`;$('featureReport').innerHTML=Object.entries(featureNames).map(([k,n])=>`<span class="${state.features[k]?'used':''}">${state.features[k]?'✓':'○'} ${n}${state.features[k]>1?' · '+state.features[k]:''}</span>`).join('');$('observationRows').innerHTML=window.CardAIModel.MODES.map(k=>`<tr><td>${C.content[k].title}</td><td>${state.viewed[k].toFixed(1).replace('.',',')} sn</td><td>${state.viewed[k]>=16?'Tamamlandı':'Devam ediyor'}</td></tr>`).join('');}
window.addEventListener('cardai:view',e=>{if(e.detail.view==='educator')renderEducator();if(e.detail.view==='case')renderCase();});
$('downloadReport').addEventListener('click',()=>{const q=s=>`"${String(s).replaceAll('"','""')}"`,rows=[['EGEMED PULSE Raporu','2026'],['Ritim','İzleme (sn)','Durum'],...Object.entries(state.viewed).map(([k,v])=>[k,v.toFixed(1),v>=16?'Tamamlandı':'Sürüyor']),[],['Test puanı',state.score??'Değerlendirilmedi'],['Başarı',state.passed?'Evet':'Hayır'],['Yanıtlanan vaka',state.caseAnswers.filter(x=>x!==null).length+'/50'],['Doğru vaka',state.caseCorrect.filter(Boolean).length+'/50'],[],['Araç','Kullanım'],...Object.entries(featureNames).map(([k,n])=>[n,state.features[k]])];const blob=new Blob(['\ufeff'+rows.map(r=>r.map(q).join(';')).join('\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='EGEMED_PULSE_rapor.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('reportStatus').textContent='CSV raporu indirildi.';});
$('resetProgress').addEventListener('click',()=>$('resetDialog').showModal());$('closeReset').addEventListener('click',()=>$('resetDialog').close());$('cancelReset').addEventListener('click',()=>$('resetDialog').close());$('confirmReset').addEventListener('click',()=>{$('resetDialog').close();activeChallenge=null;caliperVisible=false;C.resetAll();$('reportStatus').textContent='İlerleme sıfırlandı.';});
window.addEventListener('cardai:reset',()=>{$('caliperLayer').hidden=true;$('compareKey').hidden=true;$('guidedCoach').hidden=true;$('returnToCaseBtn').hidden=true;applyScale();setFocus('split');restoreCases();renderSystematic();});

// Keyboard controls are ignored while the learner is editing a form control.
document.addEventListener('keydown',e=>{if(e.altKey||e.ctrlKey||e.metaKey||['INPUT','SELECT','TEXTAREA','BUTTON'].includes(e.target.tagName)||document.querySelector('dialog[open]'))return;const k=e.key.toLowerCase(),modeKeys=window.CardAIModel.MODES;if(['1','2','3','4','5','6','7','8','9'].includes(k)){C.showView('sim');C.setMode(modeKeys[Number(k)-1]);}else if(k==='['||k===']'){const i=modeKeys.indexOf(state.mode),next=(i+(k===']'?1:-1)+modeKeys.length)%modeKeys.length;C.showView('sim');C.setMode(modeKeys[next]);}else if(k==='f')toggleFullscreen();else if(k==='c')toggleCaliper();else if(e.key==='ArrowRight'){e.preventDefault();C.seek(C.model.nextEvent(state.time));}else if(e.key==='ArrowLeft'){e.preventDefault();const times=C.model.eventTimes(Math.max(0,state.time-2),state.time-.005);C.seek(times[times.length-1]??Math.max(0,state.time-.1));}else if(e.key==='Escape'){setFocus('split');toggleGuide(false);}});

applyScale();restoreCases();syncModeTools();renderEducator();
})();
