/* EGEMED PULSE: bounded, deterministic educational signal. Seconds / mV.
   Shared fiducials describe the drawn support, not patient measurements. */
(function(root){
'use strict';
const MODES=['normal','af','stemi','pvc','svt','inferior','vt','vf','pat','flutter','sintach','lbbb','rbbb'];
const LEADS=['I','II','III','aVR','aVL','aVF','V1','V2','V3','V4','V5','V6'];
const NO_P=['af','svt','vt','vf','flutter'];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const bell=(t,c,w,a)=>Math.abs(t-c)>w?0:a*(1+Math.cos(Math.PI*(t-c)/w))/2;
function interpolate(t,pts){for(let i=1;i<pts.length;i++){const a=pts[i-1],b=pts[i];if(t>=a[0]&&t<=b[0])return a[1]+(b[1]-a[1])*(t-a[0])/(b[0]-a[0]);}return 0;}
function limb(i,ii){return {I:i,II:ii,III:ii-i,aVR:-(i+ii)/2,aVL:i-ii/2,aVF:ii-i/2};}
const leadShape={...limb(.72,1),V1:-.62,V2:-.28,V3:.34,V4:.92,V5:1.06,V6:.82};
const pShape={...limb(.8,1),V1:.55,V2:.75,V3:.78,V4:.7,V5:.62,V6:.55};
const tShape={...limb(.72,1),V1:-.28,V2:.15,V3:.55,V4:1,V5:1.05,V6:.86};
const anteriorST={...limb(.04,-.04),V1:.12,V2:.24,V3:.32,V4:.24,V5:.08,V6:.03};
const inferiorST={...limb(-.08,.20),V1:-.04,V2:-.03,V3:0,V4:.02,V5:.04,V6:.04};
const SHAPES={normal:[[0,0],[.2,-.13],[.5,1],[.7,-.25],[1,0]],pvc:[[0,0],[.12,-.18],[.27,.25],[.45,1.08],[.67,-.58],[.86,-.12],[1,0]],vt:[[0,0],[.13,-.22],[.30,.35],[.46,1.08],[.65,.65],[.83,-.42],[1,0]],lRight:[[0,0],[.15,.10],[.40,-.88],[.65,-1.12],[.90,-.25],[1,0]],lLeft:[[0,0],[.20,0],[.40,.72],[.56,.48],[.73,1.02],[.92,.22],[1,0]],lOther:[[0,0],[.20,-.12],[.44,.72],[.67,.48],[.92,-.18],[1,0]],rRight:[[0,0],[.14,.28],[.33,-.34],[.58,.92],[.83,.42],[1,0]],rLeft:[[0,0],[.20,-.08],[.36,.90],[.55,.18],[.83,-.48],[1,0]],rOther:[[0,0],[.18,-.10],[.35,.82],[.56,.14],[.85,-.34],[1,0]]};
function hash(n){let x=(n+173812)>>>0;x=Math.imul(x^(x>>>16),0x45d9f3b);x=Math.imul(x^(x>>>16),0x45d9f3b);return ((x^(x>>>16))>>>0)/4294967296;}
function fiducials(mode,isPVC=false){const kind=isPVC?'pvc':mode==='pvc'?'normal':mode,qrs=kind==='pvc'?.14:kind==='vt'?.18:kind==='lbbb'?.16:kind==='rbbb'?.14:.08,qrsStart=['pvc','rbbb'].includes(kind)?-.06:['vt','lbbb'].includes(kind)?-.07:-.04,qrsEnd=qrsStart+qrs,hasP=!NO_P.includes(mode)&&!isPVC,pr=mode==='pat'?.14:.175,pStart=hasP?qrsStart-pr:null,pEnd=hasP?pStart+.09:null;
const fast=['svt','pat','flutter','sintach','vt'].includes(mode),tStart=qrsEnd+(fast?.025:.07),tEnd=tStart+(fast?.14:.20);
return {qrsStart,qrsEnd,pStart,pEnd,pCenter:hasP?(pStart+pEnd)/2:null,pr:hasP?pr:null,qrs,qt:tEnd-qrsStart,tStart,tEnd,tCenter:(tStart+tEnd)/2,j:qrsEnd,stMeasure:qrsEnd+.02};}
class CardiacModel {
constructor(mode,options={}){this.mode=MODES.includes(mode)?mode:'normal';this.afProfile=options.afProfile==='rapid'?'rapid':'controlled';this.options={afProfile:this.afProfile};if(Number.isFinite(options.rate)&&options.rate>=50&&options.rate<=220&& !['af','pvc','flutter','vf'].includes(this.mode))this.options.rate=options.rate;this.checkpoints=[{n:0,r:-8.8,prefix:0}];this.beats=[];this.cacheFrom=Infinity;this.cacheTo=-Infinity;this.ensure(2);}
rrAt(n){if(this.mode==='af')return this.afProfile==='rapid'?.34+Math.pow(hash(n),1.18)*.22:.60+Math.pow(hash(n),1.22)*.40;if(this.mode==='pvc')return [.8,.8,.48,1.12,.8][n%5];if(this.options.rate)return 60/this.options.rate;return {svt:.36,vt:.38,vf:.28,pat:.40,flutter:.40,sintach:.50}[this.mode]||.8;}
strengthAt(n,rr){if(this.mode==='vf')return 0;if(this.mode==='af')return clamp(.68+(rr-(this.afProfile==='rapid'?.34:.60))*.55,.68,1.02);if(this.mode==='pvc')return n%5===2?.68:n%5===3?1.06:1;return {svt:.76,vt:.48,pat:.74,flutter:.70,sintach:.84,lbbb:.90,rbbb:.90}[this.mode]||1;}
// Sparse checkpoints (one per128 beats) keep a ten-hour seek below ~1,100 records.
ensureCheckpoints(time){let c=this.checkpoints[this.checkpoints.length-1];while(c.r<time+8){let r=c.r,prefix=c.prefix;for(let j=c.n;j<c.n+128;j++){const rr=this.rrAt(j);r+=rr;prefix+=this.strengthAt(j,rr);}c={n:c.n+128,r,prefix};this.checkpoints.push(c);}}
ensure(time){time=clamp(Number(time)||0,-8,36002);if(time>=this.cacheFrom&&time<=this.cacheTo)return;this.ensureCheckpoints(time);const from=Math.max(-8.7,time-6),to=time+6;let lo=0,hi=this.checkpoints.length-1;while(lo<hi){const mid=Math.ceil((lo+hi)/2);if(this.checkpoints[mid].r<=from)lo=mid;else hi=mid-1;}const c=this.checkpoints[lo];let r=c.r,prefix=c.prefix;const beats=[];for(let n=c.n;r<=to;n++){const rr=this.rrAt(n),strength=this.strengthAt(n,rr);r+=rr;prefix+=strength;const isPVC=this.mode==='pvc'&&n%5===2;if(r>=from-1.2)beats.push({n,r,rr,strength,isPVC,prefix,...fiducials(this.mode,isPVC)});}this.beats=beats;this.cacheFrom=from+1.2;this.cacheTo=to-1.2;}
lowerBound(time){let lo=0,hi=this.beats.length;while(lo<hi){const mid=(lo+hi)>>>1;if(this.beats[mid].r<time)lo=mid+1;else hi=mid;}return lo;}
between(a,b){if(!Number.isFinite(a)||!Number.isFinite(b)||b<a)return [];a=clamp(a,-8,36002);b=clamp(b,-8,36002);if(b<a)return [];if(b-a>20){let result=[];for(let t=a;t<=b;t+=8)result.push(...this.between(t,Math.min(b,t+8)));return [...new Map(result.map(x=>[x.n,x])).values()];}this.ensure((a+b)/2);if(a<this.cacheFrom-1.2||b>this.cacheTo+1.2){const result=[];for(let t=a;t<b;t+=6)result.push(...this.between(t,Math.min(b,t+6)));return [...new Map(result.map(x=>[x.n,x])).values()];}return this.beats.slice(this.lowerBound(a),this.lowerBound(b+1e-10));}
indexAt(time){this.ensure(time);return Math.max(0,this.lowerBound(time+1e-10)-1);}
qrsSignal(d,lead,b){const u=(d-b.qrsStart)/b.qrs;if(u<0||u>1)return 0;if(b.isPVC||this.mode==='vt')return interpolate(u,SHAPES[b.isPVC?'pvc':'vt'])*leadShape[lead];if(this.mode==='lbbb'){if(['V1','V2','V3'].includes(lead))return interpolate(u,SHAPES.lRight);if(['V5','V6','I'].includes(lead))return interpolate(u,SHAPES.lLeft);return interpolate(u,SHAPES.lOther)*leadShape[lead];}if(this.mode==='rbbb'){if(['V1','V2'].includes(lead))return interpolate(u,SHAPES.rRight);if(['V5','V6','I'].includes(lead))return interpolate(u,SHAPES.rLeft);return interpolate(u,SHAPES.rOther)*leadShape[lead];}return interpolate(u,SHAPES.normal)*leadShape[lead];}
independentSignal(time,lead){if(this.mode==='vf'){const k=lead==='I'?1:lead==='II'?2:LEADS.indexOf(lead)+1;return .22*Math.sin(2*Math.PI*(3.2+.07*k)*time)+.14*Math.sin(2*Math.PI*(5.7+.03*k)*time+1.1)+.10*Math.sin(2*Math.PI*8.9*time+.37*k)+.07*Math.sin(2*Math.PI*1.7*time*time+.1*k);}
this.ensure(time);const i=this.indexAt(time);let value=0;
if(this.mode==='af')value=(lead==='I'?.8:lead==='II'?1:pShape[lead])*(.020*Math.sin(2*Math.PI*6.3*time+.7*Math.sin(2.1*time))+.013*Math.sin(2*Math.PI*8.7*time)+.009*Math.sin(2*Math.PI*4.9*time+.2));
if(this.mode==='flutter'){const phase=((time*5)%1+1)%1,scale=lead==='I'?-.025:lead==='II'?-.085:lead==='V1'?.07:.035;value+=(2*phase-1)*scale;}
for(let j=Math.max(0,i-1);j<=Math.min(this.beats.length-1,i+2);j++){const b=this.beats[j],d=time-b.r;if(b.pStart!==null)value+=bell(d,b.pCenter,.045,(this.mode==='pat'?-.13:.14)*pShape[lead]);value+=this.qrsSignal(d,lead,b);
const ls=leadShape[lead],secondary=b.isPVC||this.mode==='vt'||this.mode==='lbbb'||this.mode==='rbbb';let ta=.28*tShape[lead];if(secondary){const side=this.mode==='rbbb'?Math.sign(this.qrsSignal(b.qrsStart+b.qrs*.85,lead,b)):this.mode==='lbbb'&&['V1','V2','V3'].includes(lead)?-1:Math.sign(ls);ta=-.24*side;}value+=bell(d,b.tCenter,(b.tEnd-b.tStart)/2,ta);
if(['stemi','inferior'].includes(this.mode)){const st=(this.mode==='stemi'?anteriorST:inferiorST)[lead];value+=interpolate(d,[[b.qrsEnd-.016,0],[b.qrsEnd,st],[b.tStart,st],[b.tCenter,st*.95],[b.tEnd,0]]);}}
return value;}
signal(time,lead='II'){lead=LEADS.includes(lead)?lead:'II';if(['I','II','V1','V2','V3','V4','V5','V6'].includes(lead))return this.independentSignal(time,lead);const i=this.independentSignal(time,'I'),ii=this.independentSignal(time,'II');return limb(i,ii)[lead];}
mechanicalTimeline(beat,next){const cycle=next.r-beat.r,fast=['svt','pat','flutter','sintach'].includes(this.mode)||this.mode==='af'&&cycle<.60,vt=this.mode==='vt',relaxEnd=vt?.32:fast?.27:.43,scale=Math.min(1,Math.max(.25,(cycle-.04)/relaxEnd));return {start:(vt?.04:fast?.025:.035)*scale,ejectStart:(vt?.10:fast?.06:.09)*scale,ejectEnd:(vt?.25:fast?.18:.30)*scale,relaxEnd:relaxEnd*scale,contractEnd:(vt?.30:fast?.25:.38)*scale,cycle};}
metrics(time,lead='II'){const s=this.snapshot(time),b=s.beat;if(this.mode==='vf')return {pr:null,qrs:null,qt:null,rr:null,j:null,st:null};return {pr:b.pr===null?null:Math.round(b.pr*1000),qrs:Math.round(b.qrs*1000),qt:Math.round(b.qt*1000),rr:Math.round(b.rr*1000),j:b.r+b.j,st:this.signal(b.r+b.stMeasure,lead),fiducials:{...b}};}
snapshot(time){this.ensure(time);const i=this.indexAt(time),beat=this.beats[i],next=this.beats[i+1]||{...beat,r:beat.r+beat.rr},d=time-beat.r;if(this.mode==='vf')return {time,beat,next,d,phase:'chaotic',electrical:'Kaotik ventriküler elektriksel etkinlik',mechanical:'Etkili kasılma ve mekanik nabız yok',text:'VF örneğinde organize QRS, ejeksiyon ve ileri akım yoktur. Elektriksel hız ölçülemez. Arrest bağlamında acil resüsitasyon değerlendirmesi gerekir.',atrial:0,contract:0,cavity:0,eject:false,avOpen:false,rate:null,electricalRate:null,mechanicalPulse:null,pulseText:'VF: etkili mekanik nabız yok',rr:0,qrs:0,flow:0,ischaemia:false};
const tl=this.mechanicalTimeline(beat,next),systolic=d>=tl.start&&d<tl.contractEnd,eject=d>=tl.ejectStart&&d<tl.ejectEnd,avOpen=d>=tl.relaxEnd||d<tl.start,contract=systolic?Math.sin(Math.PI*(d-tl.start)/(tl.contractEnd-tl.start)):0,cavity=d<tl.ejectStart?0:d<tl.ejectEnd?(d-tl.ejectStart)/(tl.ejectEnd-tl.ejectStart):d<tl.relaxEnd?1:1-clamp((d-tl.relaxEnd)/Math.max(.01,tl.cycle-tl.relaxEnd),0,1);
const until=next.r-time,atrial=next.pStart!==null?bell(until,-next.pCenter-.035,.045,1):0;let phase='fill',mechanical='Ventriküler doluş',text='AV kapaklar açık; şematik ventrikül hacmi doluş boyunca geri kazanılır.';if(d>=tl.start&&d<tl.ejectStart){phase='qrs';mechanical='İzovolümetrik kasılma';text='Kasılma başlar; tüm kapaklar kapalıdır. Henüz ileri ejeksiyon yoktur.';}else if(eject){phase=d>=beat.tStart?'t':'eject';mechanical='Ventriküler ejeksiyon';text='Çıkış kapakları açık; şematik ileri akım sürer.';}else if(d>=tl.ejectEnd&&d<tl.relaxEnd){phase='t';mechanical='İzovolümetrik gevşeme';text='Ejeksiyon sona erdi; tüm kapaklar kısa süre kapalıdır.';}else if(atrial>0){phase='atrial';mechanical='Doluş ve atriyal kasılma';text='Ayrık P etkinliğini şematik atriyal kasılma izler; AV kapaklar açıktır.';}
let electrical='İzoelektrik aralık';const nextD=time-next.r;if(next.pStart!==null&&nextD>=next.pStart&&nextD<=next.pEnd)electrical=this.mode==='pat'?'Ektopik P · Atriyal depolarizasyon':'P · Atriyal depolarizasyon';else if(d>=beat.qrsStart&&d<=beat.qrsEnd||nextD>=next.qrsStart&&nextD<=next.qrsEnd)electrical='QRS · Ventriküler depolarizasyon';else if(d>=beat.tStart&&d<=beat.tEnd)electrical='T · Ventriküler repolarizasyon';else if(d>beat.qrsEnd&&d<beat.tStart)electrical='ST segmenti';if(this.mode==='af')electrical+=' · sürekli f etkinliği';if(this.mode==='flutter')electrical+=' · sürekli F etkinliği';const rate=Math.round(60/beat.rr);return {time,beat,next,d,phase,electrical,mechanical,text,atrial,contract:Math.max(0,contract),cavity:clamp(cavity,0,1),eject,avOpen,rate,electricalRate:rate,mechanicalPulse:null,pulseText:'Mekanik nabız EKG’den belirlenemez',rr:Math.round(beat.rr*1000),qrs:Math.round(beat.qrs*1000),flow:beat.strength,ischaemia:['stemi','inferior'].includes(this.mode),timeline:tl};}
eventTimes(from,to){if(this.mode==='vf')return [from+.1].filter(t=>t<=to);return this.between(from-.6,to+.6).flatMap(b=>{const tl=this.mechanicalTimeline(b,{r:b.r+b.rr});return [b.pCenter,b.qrsStart,tl.ejectStart+.01,b.tCenter,tl.relaxEnd+.02].filter(v=>v!==null).map(o=>b.r+o);}).filter(t=>t>from+.001&&t<=to).sort((a,b)=>a-b);}
nextEvent(time){return this.eventTimes(time,time+2)[0]||time+.1;}
phaseTime(time,phase){if(this.mode==='vf')return time+.1;const beats=this.between(time-.5,time+2);for(const b of beats){const tl=this.mechanicalTimeline(b,{r:b.r+b.rr}),offset={atrial:b.pCenter,qrs:b.qrsStart+.01,eject:tl.ejectStart+.02,t:b.tCenter,fill:tl.relaxEnd+.02}[phase];if(offset!==null&&Number.isFinite(offset)&&b.r+offset>time+.015)return b.r+offset;}return time+.1;}
}
const api={CardiacModel,MODES,LEADS,NO_P,anteriorST,inferiorST,clamp,fiducials,limb};if(typeof module!=='undefined'&&module.exports)module.exports=api;root.CardAIModel=api;
})(typeof window!=='undefined'?window:globalThis);
