/* SCORM1.2: honest core persistence, optional interaction reporting, no network. */
(function(){'use strict';
const KEY='egemed-pulse-6.0',LEGACY_KEYS=['egemed-pulse-5.0','egemed-cardai-4.0','egemed-cardai-3.0','egemed-cardai-2.0','egemed-cardai-1.0'];
let api=null,initialized=false,finished=false,previousStatus='',activeMs=0,lastActive=performance.now(),activity=false,nextIndex=0,lmsCount=0;const allocatedIndices=new Set();
let statusReadOK=!api,resumeReadOK=!api,interactionCountReady=!api,interactionCountError='';
let lastResult={ok:false,core:'not-saved',interactions:'none',errors:[]};const pending=new Map(),committedInteractions=new Map();
function findAPI(start){let win=start;const visited=new Set();for(let i=0;win&&i<30;i++){if(visited.has(win))break;visited.add(win);try{const candidate=win.API;if(candidate&&typeof candidate.LMSInitialize==='function')return candidate;}catch{}let parent;try{parent=win.parent;}catch{break;}if(!parent||parent===win)break;win=parent;}return null;}
try{api=findAPI(window);}catch{}if(!api){try{api=findAPI(window.opener);}catch{}}
function invoke(name,args=[],boolean=false){if(!api||typeof api[name]!=='function')return {ok:false,value:'',error:'missing '+name};try{const raw=api[name](...args),value=String(raw);let code='0';if(name!=='LMSGetLastError'&&typeof api.LMSGetLastError==='function'){try{code=String(api.LMSGetLastError());}catch{return {ok:false,value,error:'LastError threw'};}}const ok=code==='0'&&(!boolean||value.toLowerCase()==='true');return {ok,value,error:ok?'':name+': '+(code==='0'?'returned '+value:'error '+code),code};}catch(e){return {ok:false,value:'',error:name+' threw',code:''};}}
if(api){statusReadOK=false;resumeReadOK=false;interactionCountReady=false;initialized=invoke('LMSInitialize',[''],true).ok;if(initialized){const status=invoke('LMSGetValue',['cmi.core.lesson_status']);if(status.ok){previousStatus=status.value;statusReadOK=true;}const count=invoke('LMSGetValue',['cmi.interactions._count']);if(count.ok&&/^\d+$/.test(count.value)){nextIndex=Math.min(2147480000,Number(count.value));lmsCount=nextIndex;interactionCountReady=true;}else interactionCountError=count.error||'cmi.interactions._count biçimi okunamadı';}}
function blockResume(reason){resumeReadOK=false;lastResult={ok:false,core:'resume-read-failed',interactions:'pending',errors:[reason]};return null;}
function load(){let raw='';try{if(api){if(!initialized)return blockResume('LMS bağlantısı başlatılamadı');if(!statusReadOK){const status=invoke('LMSGetValue',['cmi.core.lesson_status']);if(status.ok){previousStatus=status.value;statusReadOK=true;}else return blockResume(status.error);}const result=invoke('LMSGetValue',['cmi.suspend_data']);if(!result.ok)return blockResume(result.error);raw=result.value;}else raw=localStorage.getItem(KEY)||LEGACY_KEYS.map(k=>localStorage.getItem(k)).find(Boolean)||'';
if(!raw){resumeReadOK=true;return null;}if(new TextEncoder().encode(raw).length>4096)return blockResume('Devam kaydı4096 bayt sınırından büyük; önceki veri korundu');let obj;try{obj=JSON.parse(raw);}catch{return blockResume('Devam kaydı bozuk JSON; önceki veri korundu');}if(!obj||typeof obj!=='object'||Array.isArray(obj)||!Number.isInteger(obj.version)||obj.version<1||obj.version>6)return blockResume('Desteklenmeyen devam kaydı sürümü/biçimi; önceki veri korundu');resumeReadOK=true;return obj;
}catch{return blockResume('Devam kaydı okunamadı; önceki veri korundu');}}
function acknowledgeReset(){pending.clear();resumeReadOK=true;lastResult={ok:false,core:'reset-pending',interactions:'none',errors:[]};}
function addTime(){const now=performance.now();if(activity&&!document.hidden&&!finished)activeMs+=Math.max(0,now-lastActive);lastActive=now;}
function setActivity(on){addTime();activity=!!on;}
function sessionTime(){addTime();const cs=Math.floor(activeMs/10),h=Math.min(9999,Math.floor(cs/360000)),m=Math.floor(cs/6000)%60,s=Math.floor(cs/100)%60;return String(h).padStart(4,'0')+':'+String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')+'.'+String(cs%100).padStart(2,'0');}
function interaction(payload,response,correct){if(!payload||typeof payload!=='object')return null;const valid=/^(case|quiz)$/.test(payload.section)&&/^[A-Za-z0-9_-]{1,32}$/.test(payload.sessionId)&&/^[CQ]\d{3}$/.test(payload.itemId)&&Number.isInteger(payload.response)&&payload.response>=0&&payload.response<5&&Number.isInteger(payload.correctResponse)&&payload.correctResponse>=0&&payload.correctResponse<5;if(!valid)return null;const id='pulse_'+payload.section+'_'+payload.sessionId+'_'+payload.itemId;let index=Number.isInteger(payload.index)&&payload.index>=0&&payload.index<2147480000&&(payload.index<lmsCount||allocatedIndices.has(payload.index))?payload.index:null;if(index===null&&interactionCountReady){index=nextIndex++;allocatedIndices.add(index);}else if(index!==null)nextIndex=Math.max(nextIndex,index+1);const row={...payload,id,index};pending.set(id,row);return index;}
function queueFromState(state){for(const [section,session] of [['case',state.caseSession],['quiz',state.quizSession]]){if(!session)continue;session.ids.forEach((id,i)=>{if(!session.submitted[i])return;const item=window.PulseCurriculum?.byId[id];if(!item)return;session.interactionIndices[i]=interaction({section,sessionId:session.id,itemId:id,response:session.answers[i],correctResponse:item.correct,index:session.interactionIndices[i]});});}}
function save(state){if(finished){lastResult={ok:false,core:'ended',interactions:'none',errors:['LMS oturumu sonlandırıldı']};return false;}
if(!resumeReadOK||api&&!statusReadOK){lastResult={ok:false,core:'resume-read-failed',interactions:'pending',errors:['Devam kaydı okunamadı; önce yeniden okuma gerekir']};return false;}
if(api&&initialized&&!interactionCountReady){const count=invoke('LMSGetValue',['cmi.interactions._count']);if(count.ok&&/^\d+$/.test(count.value)){lmsCount=Math.min(2147480000,Number(count.value));nextIndex=Math.max(nextIndex,lmsCount);interactionCountReady=true;interactionCountError='';}else interactionCountError=count.error||'cmi.interactions._count biçimi okunamadı';}
queueFromState(state);let serial;try{serial=JSON.stringify(window.PulseState?window.PulseState.encode(state):state);}catch{lastResult={ok:false,core:'serialization-failed',interactions:'pending',errors:['Durum kodlanamadı']};return false;}
if(new TextEncoder().encode(serial).length>4096){lastResult={ok:false,core:'oversize',interactions:'pending',errors:['suspend_data 4096 bayt sınırını aşıyor']};return false;}
if(!api){try{localStorage.setItem(KEY,serial);lastResult={ok:true,core:'local',interactions:'local-only',errors:[]};return true;}catch{lastResult={ok:false,core:'local-failed',interactions:'local-only',errors:['Tarayıcı kaydı reddetti']};return false;}}
if(!initialized){lastResult={ok:false,core:'initialize-failed',interactions:'pending',errors:['LMSInitialize başarısız']};return false;}
const errors=[],writes=[['cmi.suspend_data',serial],['cmi.core.lesson_location',state.mode+':'+Number(state.time).toFixed(2)],['cmi.core.score.min','0'],['cmi.core.score.max','100']];
if(state.bestScore!==null)writes.push(['cmi.core.score.raw',state.bestScore]);const status=state.passed||previousStatus==='passed'?'passed':state.assessed?'failed':'incomplete';writes.push(['cmi.core.lesson_status',status],['cmi.core.session_time',sessionTime()],['cmi.core.exit',status==='passed'?'':'suspend']);
for(const [k,v] of writes){const r=invoke('LMSSetValue',[k,String(v)],true);if(!r.ok)errors.push(r.error+' ['+k+']');}
const interactionErrors=[],sent=[];if(!interactionCountReady&&pending.size)interactionErrors.push(interactionCountError);for(const row of pending.values()){if(!interactionCountReady)break;if(row.index===null){row.index=nextIndex++;allocatedIndices.add(row.index);}const signature=row.response+':'+row.correctResponse;if(committedInteractions.get(row.id)===signature)continue;const p='cmi.interactions.'+row.index+'.',fields=[['id',row.id],['type','choice'],['correct_responses.0.pattern',String.fromCharCode(97+row.correctResponse)],['student_response',String.fromCharCode(97+row.response)],['result',row.response===row.correctResponse?'correct':'wrong']];let ok=true;for(const [field,v] of fields){const r=invoke('LMSSetValue',[p+field,v],true);if(!r.ok){ok=false;interactionErrors.push(r.error+' ['+p+field+']');}}if(ok)sent.push([row.id,signature]);}
const commit=invoke('LMSCommit',[''],true);if(!commit.ok)errors.push(commit.error);const ok=errors.length===0;
if(ok){previousStatus=status;for(const [id,signature] of sent){committedInteractions.set(id,signature);pending.delete(id);}}
lastResult={ok,core:ok?'saved':'failed',interactions:interactionErrors.length?'failed-pending':pending.size?'pending':'saved',errors:[...errors,...interactionErrors]};return ok;
}
function finish(state){if(finished)return false;if(!save(state))return false;if(!api)return true;const result=invoke('LMSFinish',[''],true);if(result.ok){finished=true;activity=false;lastResult={...lastResult,core:'finished'};return true;}lastResult={...lastResult,ok:false,core:'finish-failed',errors:[...lastResult.errors,result.error]};return false;}
function clearLocal(){try{localStorage.removeItem(KEY);LEGACY_KEYS.forEach(k=>localStorage.removeItem(k));return true;}catch{return false;}}
document.addEventListener('visibilitychange',addTime);
window.addEventListener('pagehide',()=>{try{if(!finished)finish(window.CardAIController?.state);}catch{}});
window.CardAIScorm={load,save,finish,interaction,clearLocal,acknowledgeReset,setActivity,sessionTime,get isLMS(){return initialized;},get detected(){return !!api;},get ended(){return finished;},get previousStatus(){return previousStatus;},get resumeBlocked(){return !resumeReadOK||!!api&&!statusReadOK;},get lastResult(){return {...lastResult,errors:[...lastResult.errors]};},get activeMilliseconds(){addTime();return activeMs;},get pendingInteractions(){return pending.size;},key:KEY};
})();
