/* Narrow version6 progress schema. Derived correctness, score and gates are never trusted. */
(function(root){'use strict';
const {MODES,LEADS,clamp}=root.CardAIModel,POOL=root.PulseCurriculum,COUNT=10;
const int=(v,a,b,fallback=a)=>Number.isInteger(v)&&v>=a&&v<=b?v:fallback;
const finite=(v,a,b,fallback=a)=>typeof v==='number'&&Number.isFinite(v)?clamp(v,a,b):fallback;
function randomInt(max){if(root.crypto?.getRandomValues){const range=4294967296,limit=range-range%max,u=new Uint32Array(1);do{root.crypto.getRandomValues(u);}while(u[0]>=limit);return u[0]%max;}return Math.floor(Math.random()*max);}
function sessionId(){const u=new Uint32Array(3);if(root.crypto?.getRandomValues)root.crypto.getRandomValues(u);else for(let i=0;i<3;i++)u[i]=randomInt(4294967296);return Array.from(u,n=>n.toString(36)).join('_').slice(0,32);}
function sample(section,oldIds){const pool=(section==='case'?POOL.cases:POOL.questions).map(x=>x.id);for(let i=pool.length-1;i>0;i--){const j=randomInt(i+1);[pool[i],pool[j]]=[pool[j],pool[i]];}const ids=pool.slice(0,COUNT);return {id:sessionId(),ids,answers:Array(COUNT).fill(null),submitted:Array(COUNT).fill(false),leadSelections:ids.map(id=>[...POOL.byId[id].ecg.leads]),interactionIndices:Array(COUNT).fill(null)};}
function validateSession(raw,section){const fresh=sample(section),prefix=section==='case'?'C':'Q';if(!raw||typeof raw!=='object'||Array.isArray(raw)||!Array.isArray(raw.n)||raw.n.length!==COUNT)return fresh;const ids=raw.n.map(n=>prefix+String(int(n,1,200,0)).padStart(3,'0'));if(new Set(ids).size!==COUNT||ids.some(id=>!POOL.byId[id]))return fresh;const id=typeof raw.i==='string'&&/^[A-Za-z0-9_-]{1,32}$/.test(raw.i)?raw.i:sessionId();const mask=int(raw.s,0,1023,0);return {id,ids,answers:ids.map((_,i)=>int(raw.a?.[i],0,4,null)),submitted:ids.map((_,i)=>!!(mask&(1<<i))&&Number.isInteger(raw.a?.[i])&&raw.a[i]>=0&&raw.a[i]<5),leadSelections:ids.map((id,i)=>[0,1,2].map(j=>LEADS[int(raw.l?.[i]?.[j],0,11,LEADS.indexOf(POOL.byId[id].ecg.leads[j]))])),interactionIndices:ids.map((_,i)=>int(raw.x?.[i],0,2147479999,null))};}
function compactSession(s){return {i:s.id,n:s.ids.map(id=>Number(id.slice(1))),a:s.answers.map(a=>a===null?-1:a),s:s.submitted.reduce((mask,on,i)=>mask|(on?1<<i:0),0),l:s.leadSelections.map(row=>row.map(l=>LEADS.indexOf(l))),x:s.interactionIndices.map(n=>n===null?-1:n)};}
function blank(){return {version:6,mode:'normal',time:2,speed:1,uiScale:120,viewed:Object.fromEntries(MODES.map(m=>[m,0])),caseSession:sample('case'),quizSession:sample('quiz'),bestAttempt:null,bestCaseAttempt:null,leads:['II','aVF','V3'],activeLead:0,lead:'II',afProfile:'controlled',compare:false,caliper:{a:{x:.06,y:.46},b:{x:.25,y:.46}},currentCase:0,quizPage:0,challengeCorrect:{rr:false,st:false},features:{fullscreen:0,focus:0,compare:0,caliper:0,guide:0,systematic:0,cases:0},checklist:{},activeView:'modes',tutorialDone:false,learningMs:0,returnContext:null,assessed:false,score:null,attemptScore:null,bestScore:null,passed:false};}
function correctness(s){return s.ids.map((id,i)=>s.submitted[i]&&s.answers[i]===POOL.byId[id].correct);}
function attemptScore(s){return s.submitted.every(Boolean)?correctness(s).filter(Boolean).length*10:null;}
function derive(s){s.caseAnswers=s.caseSession.answers;s.caseSubmitted=s.caseSession.submitted;s.caseCorrect=correctness(s.caseSession);s.answers=s.quizSession.answers;s.quizSubmitted=s.quizSession.submitted;s.assessed=s.quizSubmitted.every(Boolean);s.attemptScore=attemptScore(s.quizSession);const historical=s.bestAttempt?attemptScore(s.bestAttempt):null;s.bestScore=Math.max(s.attemptScore??-1,historical??-1);if(s.bestScore<0)s.bestScore=null;s.score=s.bestScore;const simComplete=MODES.every(m=>s.viewed[m]>=16),casesComplete=s.caseSubmitted.every(Boolean);s.passed=(simComplete&&(casesComplete||s.bestCaseAttempt?.submitted.every(Boolean))&&(s.bestScore??0)>=80)||root.CardAIScorm.previousStatus==='passed';return {simComplete,casesComplete,casesUnlocked:simComplete,quizUnlocked:simComplete&&casesComplete,passed:s.passed};}
function decode(raw){const s=blank();if(!raw||typeof raw!=='object'||Array.isArray(raw)||!Number.isInteger(raw.version)||raw.version<1||raw.version>6){derive(s);return s;}
if(raw.version<6){s.mode=MODES.includes(raw.mode)?raw.mode:'normal';s.time=finite(raw.time,0,36000,2);for(const m of MODES)s.viewed[m]=finite(raw.viewed?.[m],0,16);s.afProfile=raw.afProfile==='rapid'?'rapid':'controlled';// Previous fixed50-item answers have no mapping to the authored v6 pool.
}else {s.mode=MODES[int(raw.m,0,12,0)];s.time=finite(raw.t,0,36000,2);s.speed=[.25,.5,1,2].includes(raw.p)?raw.p:1;s.afProfile=raw.f===1?'rapid':'controlled';MODES.forEach((m,i)=>s.viewed[m]=int(raw.v?.[i],0,16000,0)/1000);s.caseSession=validateSession(raw.c,'case');s.quizSession=validateSession(raw.q,'quiz');if(raw.b&&Array.isArray(raw.b.n)&&raw.b.n.length===COUNT){const b=validateSession(raw.b,'quiz');if(b.submitted.every(Boolean)&&b.ids.every((id,i)=>id==='Q'+String(raw.b.n[i]).padStart(3,'0')))s.bestAttempt=b;}
if(raw.bc&&Array.isArray(raw.bc.n)&&raw.bc.n.length===COUNT){const bc=validateSession(raw.bc,'case');if(bc.submitted.every(Boolean)&&bc.ids.every((id,i)=>id==='C'+String(raw.bc.n[i]).padStart(3,'0')))s.bestCaseAttempt=bc;}
s.currentCase=int(raw.j,0,COUNT-1,0);s.quizPage=int(raw.k,0,COUNT-1,0);s.activeView=['sim','case','quiz','educator','modes','about','results','tutorial'][int(raw.u,0,7,0)];s.tutorialDone=raw.w===1;s.learningMs=int(raw.z,0,31536000000,0);s.leads=[['I','II','III'],['aVR','aVL','aVF'],['V1','V2','V3','V4','V5','V6']].map((group,i)=>group.includes(LEADS[raw.d?.[i]])?LEADS[raw.d[i]]:s.leads[i]);s.activeLead=int(raw.h,0,2,0);s.compare=raw.o===1;
for(const [i,key] of Object.keys(s.features).entries())s.features[key]=int(raw.e?.[i],0,99,0);MODES.forEach((m,i)=>{const mask=int(raw.y?.[i],0,63,0);for(let j=0;j<6;j++)if(mask&(1<<j))s.checklist[m+':'+j]=true;});if(Array.isArray(raw.g)&&raw.g.length===4){s.caliper={a:{x:finite(raw.g[0],.02,.98,.06),y:finite(raw.g[1],.04,.96,.46)},b:{x:finite(raw.g[2],.02,.98,.25),y:finite(raw.g[3],.04,.96,.46)}};}
if(raw.r&&raw.r[0]===s.caseSession.id&&s.caseSession.ids.includes(raw.r[1])){const i=s.caseSession.ids.indexOf(raw.r[1]);if(s.caseSession.submitted[i]&&s.caseSession.answers[i]===POOL.byId[raw.r[1]].correct)s.returnContext={sessionId:raw.r[0],itemId:raw.r[1],index:i};}}
s.lead=s.leads[s.activeLead];const used=new Set();for(const session of [s.caseSession,s.quizSession])session.interactionIndices=session.interactionIndices.map(x=>x===null||used.has(x)?null:(used.add(x),x));derive(s);return s;}
function encode(s){derive(s);return {version:6,m:MODES.indexOf(s.mode),t:Math.round(s.time*100)/100,p:s.speed,f:s.afProfile==='rapid'?1:0,v:MODES.map(m=>Math.round(clamp(s.viewed[m],0,16)*1000)),c:compactSession(s.caseSession),q:compactSession(s.quizSession),b:s.bestAttempt?compactSession(s.bestAttempt):null,bc:s.bestCaseAttempt?compactSession(s.bestCaseAttempt):null,j:s.currentCase,k:s.quizPage,u:['sim','case','quiz','educator','modes','about','results','tutorial'].indexOf(s.activeView),w:s.tutorialDone?1:0,d:s.leads.map(l=>LEADS.indexOf(l)),h:s.activeLead,o:s.compare?1:0,z:Math.round(s.learningMs),e:Object.values(s.features),y:MODES.map(m=>[0,1,2,3,4,5].reduce((mask,j)=>mask|(s.checklist[m+':'+j]?1<<j:0),0)),g:[s.caliper.a.x,s.caliper.a.y,s.caliper.b.x,s.caliper.b.y].map(n=>Math.round(n*1000)/1000),r:s.returnContext?[s.returnContext.sessionId,s.returnContext.itemId]:null};}
root.PulseState={blank,decode,encode,derive,sample,COUNT,attemptScore};
})(window);
