import {chromium} from '/Users/ozankaraca/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
import vm from 'node:vm';
const root=path.resolve(import.meta.dirname,'..'),out=path.join(root,'qa/evidence/baseline');
const require=createRequire(import.meta.url),M=require('../cardai/model.js');
const report={date:new Date().toISOString(),kind:'Real Chromium browser + separately identified direct model checks',observations:[],errors:[]};
const record=(id,data)=>{report.observations.push({id,...data});console.log(id,JSON.stringify(data));fs.writeFileSync(path.join(out,'audit-baseline.json'),JSON.stringify(report,null,2));};
const scope={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'cardai/curriculum.js'),'utf8'),scope);
const curriculum=scope.window.PulseCurriculum;
fs.writeFileSync(path.join(out,'all-items.json'),JSON.stringify(curriculum,null,2));
record('CONTENT',{cases:curriculum.cases.length,questions:curriculum.questions.length,caseClinicalStems:new Set(curriculum.cases.map(c=>c.stem.replace(/\d+ yaşında, /g,''))).size,optionCounts:[...new Set([...curriculum.cases,...curriculum.questions].map(q=>q.options.length))],duplicateOptions:curriculum.questions.flatMap((q,i)=>new Set(q.options).size<q.options.length?[{number:i+1,options:q.options}]:[])});
for(const mode of M.MODES){const model=new M.CardiacModel(mode);let residual=0,augmentedResidual=0,nonfinite=0;for(let t=0;t<10;t+=.003){const [a,b,c,vr,vl,vf]=M.LEADS.slice(0,6).map(l=>model.signal(t,l));residual=Math.max(residual,Math.abs(b-a-c));augmentedResidual=Math.max(augmentedResidual,Math.abs(vr+(a+b)/2),Math.abs(vl-a+b/2),Math.abs(vf-b+a/2));for(const lead of M.LEADS)if(!Number.isFinite(model.signal(t,lead)))nonfinite++;}record('MODEL-'+mode,{residual,augmentedResidual,nonfinite,qrs:model.beats.find(b=>mode!=='pvc'||b.isPVC).qrs,rate:model.snapshot(3).rate});}
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1366,height:768}});
const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));
const url='http://127.0.0.1:8765/cardai/';
const state=()=>page.evaluate(()=>CardAIDiagnostics.state);
const snap=async name=>page.screenshot({path:path.join(out,name+'.png'),fullPage:true});
await page.goto(url);let before=await state();await page.waitForTimeout(17000);let after=await state();record('LANDING-17s',{before:before.viewed.normal,after:after.viewed.normal,landingVisible:await page.locator('#landingPage').isVisible()});
await page.locator('#startSimulator').click();await snap('sim-1366');
await page.evaluate(()=>{CardAIController.resetAll();CardAIController.setPlaying(true);CardAIController.setMode('af');});before=await state();await page.waitForTimeout(1200);after=await state();record('PROGRAMMATIC',{before:before.viewed.af,after:after.viewed.af});
await page.evaluate(()=>{CardAIController.resetAll();CardAIController.setPlaying(true);});await page.locator('.rhythm-tab[data-mode="normal"]').click();await page.locator('#speed').selectOption('2');before=await state();await page.waitForTimeout(16500);after=await state();record('EXPLICIT-16s-speed2',{before:before.viewed.normal,after:after.viewed.normal,simTime:after.time});
await page.locator('#helpBtn').click();before=await state();await page.waitForTimeout(1100);after=await state();record('HELP-MODAL',{delta:after.viewed.normal-before.viewed.normal,open:await page.locator('#infoDialog').isVisible()});await page.locator('#closeInfo').click();
await page.evaluate(()=>{CardAIController.resetAll();CardAIController.setPlaying(true);document.getElementById('resetDialog').showModal();});before=await state();await page.waitForTimeout(1100);after=await state();record('OTHER-MODAL',{delta:after.viewed.normal-before.viewed.normal});await page.locator('#cancelReset').click();
for(const size of [{width:1366,height:768},{width:1920,height:1080},{width:390,height:844}]){await page.setViewportSize(size);await page.waitForTimeout(120);record('LAYOUT-'+size.width,await page.evaluate(()=>{const rail=document.querySelector('.rhythm-tabs').getBoundingClientRect();return {viewport:{w:innerWidth,h:innerHeight},documentWidth:document.documentElement.scrollWidth,cards:[...document.querySelectorAll('.rhythm-tab')].map(x=>{const r=x.getBoundingClientRect();return {mode:x.dataset.mode,height:r.height,bottom:r.bottom,railBottom:rail.bottom,scrollHeight:x.scrollHeight,clientHeight:x.clientHeight};}),font:getComputedStyle(document.querySelector('.summary-text')).fontSize,leadSelectors:[...document.querySelectorAll('.lead-select')].map(x=>({x:x.getBoundingClientRect().x,width:x.getBoundingClientRect().width})),ecg:document.getElementById('ecgCanvas').getBoundingClientRect().toJSON()};}));await snap('layout-'+size.width);}
await page.setViewportSize({width:1366,height:768});
for(const focus of ['anatomy','ecg','explanation']){await page.locator(`[data-focus-panel="${focus}"]`).click();const expanded=await page.locator('#appRoot').getAttribute('data-focus');await page.locator(`[data-focus-panel="${focus}"]`).click();record('FOCUS-'+focus,{expanded,collapsed:await page.locator('#appRoot').getAttribute('data-focus')});}
try{await page.locator('#fullscreenBtn').click();await page.waitForTimeout(200);await page.locator('#helpBtn').click();record('FULLSCREEN',{element:await page.evaluate(()=>document.fullscreenElement?.id),dialogVisible:await page.locator('#infoDialog').isVisible(),closeEnabled:await page.locator('#closeInfo').isEnabled()});await snap('fullscreen-modal');await page.locator('#closeInfo').click();await page.evaluate(()=>document.fullscreenElement&&document.exitFullscreen());}catch(e){record('FULLSCREEN-ERROR',{message:e.message});}
await page.evaluate(()=>{for(const m of CardAIModel.MODES)CardAIController.state.viewed[m]=16;CardAIController.progress();});await page.locator('#quizTab').click();record('QUIZ-WITH-ZERO-CASES',{view:(await state()).activeView,answers:(await state()).caseAnswers.filter(x=>x!==null).length,ecgCanvases:await page.locator('#quizView canvas').count()});await snap('quiz-baseline');
await page.locator('#caseTab').click();record('CASE-BEFORE-ANSWER',{expandVisible:await page.locator('#caseExpand').isVisible(),leadMenus:await page.locator('#caseView select').count(),canvas:await page.locator('#caseEcgCanvas').evaluate(c=>({width:c.width,height:c.height}))});await snap('case-baseline');
await page.locator('#caseNext').click();const initialSize=await page.locator('#caseEcgCanvas').evaluate(c=>({width:c.width,height:c.height,cssWidth:c.clientWidth,cssHeight:c.clientHeight}));await page.setViewportSize({width:1920,height:1080});await page.waitForTimeout(200);record('CASE-RESIZE',{before:initialSize,after:await page.locator('#caseEcgCanvas').evaluate(c=>({width:c.width,height:c.height,cssWidth:c.clientWidth,cssHeight:c.clientHeight}))});
await page.locator('#simTab').click();await page.evaluate(()=>{CardAIController.setMode('vf');CardAIController.setPlaying(true);});const particles=()=>page.locator('#particles circle').evaluateAll(xs=>xs.map(x=>[x.getAttribute('cx'),x.getAttribute('cy'),x.style.opacity]));const p1=await particles();await page.waitForTimeout(700);const p2=await particles();record('VF-FLOW',{movingParticles:p1.filter((x,i)=>JSON.stringify(x)!==JSON.stringify(p2[i])).length,total:p1.length});
await page.close();await context.close();
for(const fixture of ['save-false','finish-success','malformed']){const ctx=await browser.newContext({viewport:{width:1366,height:768}});await ctx.addInitScript(({fixture})=>{window.mockCalls=[];window.mockData={'cmi.core.lesson_status':'incomplete'};window.rejectSet=false;window.API={LMSInitialize:()=> 'true',LMSGetValue:k=>mockData[k]||'',LMSSetValue:(k,v)=>{mockCalls.push(['set',k,v]);if(window.rejectSet)return 'false';mockData[k]=v;return 'true';},LMSGetLastError:()=> '0',LMSCommit:()=>{mockCalls.push(['commit']);return 'true';},LMSFinish:()=>{mockCalls.push(['finish']);return 'true';}};if(fixture==='malformed')mockData['cmi.suspend_data']=JSON.stringify({version:5,currentCase:.5,quizPage:.5,activeLead:.5,passed:true,score:100,viewed:{},answers:[],caseAnswers:[999]});},{fixture});const p=await ctx.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url);if(fixture==='save-false'){await p.locator('#startSimulator').click();record('SCORM-SET-FALSE',await p.evaluate(()=>{rejectSet=true;return {reportedSuccess:CardAIScorm.save(CardAIController.state),bytes:JSON.stringify(CardAIController.state).length};}));}if(fixture==='finish-success'){await p.locator('#startSimulator').click();await p.locator('#finishBtn').click();record('SCORM-FINISH',{dialogOpen:await p.locator('#finishDialog').isVisible(),closeEnabled:await p.locator('#closeFinish').isEnabled(),continueEnabled:await p.locator('#continueBtn').isEnabled(),calls:await p.evaluate(()=>mockCalls.filter(x=>x[0]==='finish').length)});await p.screenshot({path:path.join(out,'finish-disabled.png')});}if(fixture==='malformed')record('MALFORMED-RESTORE',{errors,controllerExists:await p.evaluate(()=>!!window.CardAIController)});await ctx.close();}
await browser.close();fs.writeFileSync(path.join(out,'audit-baseline.json'),JSON.stringify(report,null,2));
