import fs from 'node:fs';
import path from 'node:path';
import {chromium,logger,assert,addMock,root} from './independent_support.mjs';
const log=logger('independent-scorm');log.note('scope',{kind:'Real Chromium running actual scorm.js adapter with API mock; not real LMS and not full product UI'});
const browser=await chromium.launch({headless:true});
const initialState={version:6,mode:'normal',time:2,bestScore:null,assessed:false,passed:false};
async function fixture(initial={},failure={}){const c=await browser.newContext();await addMock(c,initial,failure);const p=await c.newPage();await p.goto('about:blank');await p.addScriptTag({path:path.join(root,'cardai/scorm.js')});await p.evaluate(s=>{window.__testState=s;CardAIScorm.load();},initialState);return {c,p};}
for(const fail of [{fn:'LMSSetValue',key:'cmi.suspend_data'},{fn:'LMSSetValue',key:'cmi.core.lesson_status',code:'101'},{fn:'LMSCommit'},{fn:'LMSCommit',throw:true},{fn:'LMSSetValue',key:'cmi.core.score.min',throw:true}]){
 await log.test('T11-'+fail.fn+'-'+(fail.key||'all')+'-'+(fail.throw?'throw':fail.code||'false'),async()=>{const {c,p}=await fixture();await p.evaluate(f=>__lms.failure=f,fail);const failed=await p.evaluate(()=>({ok:CardAIScorm.save(__testState),result:CardAIScorm.lastResult}));assert(failed.ok===false,'False success on injected failure');await p.evaluate(()=>__lms.failure={});const retried=await p.evaluate(()=>({ok:CardAIScorm.save(__testState),result:CardAIScorm.lastResult}));assert(retried.ok,'Retry failed');await c.close();return {failed,retried};});
}
await log.test('T11-Initialize-failure',async()=>{const {c,p}=await fixture({}, {fn:'LMSInitialize'});const result=await p.evaluate(()=>({load:CardAIScorm.load(),save:CardAIScorm.save(__testState),calls:__lms.calls}));assert(result.save===false,'Initfailed save succeeds');assert(!result.calls.some(c=>['LMSGetValue','LMSSetValue','LMSCommit','LMSFinish'].includes(c[0])),'Used uninitialized API');await c.close();return result;});
await log.test('T11-Get-failure-preserve-resume',async()=>{const old=JSON.stringify({version:6,marker:'previous-learning-progress'});const {c,p}=await fixture({'cmi.suspend_data':old},{fn:'LMSGetValue',key:'cmi.suspend_data',code:'101',result:''});const result=await p.evaluate(()=>({load:CardAIScorm.load(),save:CardAIScorm.save(__testState),data:__lms.data['cmi.suspend_data'],result:CardAIScorm.lastResult}));assert(result.save===false&&result.data===old,'Failed GetValue silently overwritten with fresh state');await c.close();return result;});
for(const raw of ['{"version":9,"important":"future-progress"}','{invalid json']){await log.test('T13-unreadable-schema-preserve-'+raw.slice(0,12),async()=>{const {c,p}=await fixture({'cmi.suspend_data':raw});const result=await p.evaluate(()=>({load:CardAIScorm.load(),save:CardAIScorm.save(__testState),data:__lms.data['cmi.suspend_data']}));assert(!result.save&&result.data===raw,'Unreadable existing payload silently overwritten');await c.close();return result;});}
await log.test('T11-status-ledger-after-commit',async()=>{const {c,p}=await fixture();const result=await p.evaluate(()=>{__testState.bestScore=80;__testState.assessed=true;__testState.passed=true;__lms.failure={fn:'LMSCommit'};const failed=CardAIScorm.save(__testState),afterFailed=CardAIScorm.previousStatus;__lms.failure={};const success=CardAIScorm.save(__testState);return {failed,afterFailed,success,afterSuccess:CardAIScorm.previousStatus};});assert(!result.failed&&result.afterFailed!=='passed'&&result.success&&result.afterSuccess==='passed','Premature status ledger');await c.close();return result;});
await log.test('T14-oversize-no-truncation',async()=>{const {c,p}=await fixture({'cmi.suspend_data':'{"version":6,"marker":"original"}'});const result=await p.evaluate(()=>{__testState.padding='ü'.repeat(3000);return {ok:CardAIScorm.save(__testState),result:CardAIScorm.lastResult,data:__lms.data['cmi.suspend_data']};});assert(!result.ok&&result.data.includes('original')&&result.result.core==='oversize','Oversized state saved/truncated');await c.close();return result;});
await log.test('T15-correct-response-identity-retry',async()=>{const {c,p}=await fixture();const result=await p.evaluate(()=>{const payload={section:'case',sessionId:'sessionabc',itemId:'C017',response:4,correctResponse:2};const index=CardAIScorm.interaction(payload);__lms.failure={fn:'LMSSetValue',key:'interactions',code:'401'};const core=CardAIScorm.save(__testState),failed={...CardAIScorm.lastResult};__lms.failure={};const retry=CardAIScorm.save(__testState);return {index,core,failed,retry,data:__lms.data,result:CardAIScorm.lastResult,pending:CardAIScorm.pendingInteractions};});assert(result.core&&result.failed.interactions!=='saved','Optional interaction failure falsely reported');assert(result.retry&&result.pending===0,'Interaction didnotretry');const prefix='cmi.interactions.'+result.index+'.';assert(result.data[prefix+'correct_responses.0.pattern']==='c'&&result.data[prefix+'student_response']==='e'&&result.data[prefix+'result']==='wrong'&&result.data[prefix+'id'].includes('C017'),'Interaction identity/answer mismatch');await c.close();return result;});
await log.test('T15-invalid-saved-index',async()=>{const {c,p}=await fixture();const result=await p.evaluate(()=>{const index=CardAIScorm.interaction({section:'quiz',sessionId:'abc',itemId:'Q200',response:0,correctResponse:1,index:2000000000});const ok=CardAIScorm.save(__testState);return {index,ok,data:__lms.data,result:CardAIScorm.lastResult};});assert(result.index===0&&result.ok,'Sparse index trusted');await c.close();return result;});
await log.test('T12-finish-failed-save-retry-once',async()=>{const {c,p}=await fixture();const result=await p.evaluate(()=>{__lms.failure={fn:'LMSCommit'};const saveFail=CardAIScorm.finish(__testState),finishCallsAfterSaveFailure=__lms.calls.filter(c=>c[0]==='LMSFinish').length;__lms.failure={fn:'LMSFinish'};const finishFail=CardAIScorm.finish(__testState);__lms.failure={};const success=CardAIScorm.finish(__testState),callCount=__lms.calls.length;CardAIScorm.save(__testState);CardAIScorm.finish(__testState);return {saveFail,finishCallsAfterSaveFailure,finishFail,success,ended:CardAIScorm.ended,callsAfterEnded:__lms.calls.length-callCount};});assert(!result.saveFail&&result.finishCallsAfterSaveFailure===0&&!result.finishFail&&result.success&&result.ended&&result.callsAfterEnded===0,'Finish lifecycle violation');await c.close();return result;});
await log.test('T14-active-session-time',async()=>{const {c,p}=await fixture();await p.evaluate(()=>CardAIScorm.setActivity(false));await p.waitForTimeout(300);const idle=await p.evaluate(()=>CardAIScorm.activeMilliseconds);await p.evaluate(()=>CardAIScorm.setActivity(true));await p.waitForTimeout(700);await p.evaluate(()=>CardAIScorm.setActivity(false));const active=await p.evaluate(()=>({ms:CardAIScorm.activeMilliseconds,formatted:CardAIScorm.sessionTime()}));await p.waitForTimeout(300);const stopped=await p.evaluate(()=>CardAIScorm.activeMilliseconds);assert(idle<50&&active.ms>=650&&active.ms<1100&&stopped===active.ms,'Session activity time wrong');assert(/^\d{4}:\d{2}:\d{2}\.\d{2}$/.test(active.formatted),'Invalid SCORM time');await c.close();return {idle,active,stopped};});
await browser.close();console.log(JSON.stringify({tests:log.rows.length,failed:log.rows.filter(r=>r.status==='FAIL').map(r=>r.id)}));process.exitCode=log.rows.some(r=>r.status==='FAIL')?1:0;
