import vm from 'node:vm';
import fs from 'node:fs';
import path from 'node:path';
import {root,evidence,logger,assert} from './independent_support.mjs';
const log=logger('independent-content'),w={};w.window=w;vm.createContext(w);
for(const file of ['model.js','curriculum.js'])vm.runInContext(fs.readFileSync(path.join(root,'cardai',file),'utf8'),w);
const {cases,questions}=w.PulseCurriculum,{CardiacModel,MODES,LEADS}=w.CardAIModel,all=[...cases,...questions];
const sources=new Set(['AF2024','SVT2019','VA2022','ALS2025','ACS2023','BBB2009','ECG','CYCLE','REPOL2009']);
await log.test('T03-T04-all400-schema-mapping-neutrality',()=>{const invalid=[];for(const item of all){if(!/^([CQ])\d{3}$/.test(item.id)||item.options.length!==5||new Set(item.options).size!==5||item.correct<0||item.correct>4||item.explanations.length!==5||!item.objectiveIds.every(id=>/^O[1-6]$/.test(id))||!item.sourceIds.every(id=>sources.has(id))||item.mode!==item.ecg.mode||item.ecg.leads.some(l=>!LEADS.includes(l))||/AF|flutter|STEMI|VF|sinüs|bloğu/i.test(item.title+' '+item.ariaLabel))invalid.push(item.id);}assert(invalid.length===0,'Invalid items '+invalid);return {count:all.length,invalid};});
await log.test('T04-unique-content-and-position-distribution',()=>{const pools=[cases,questions].map(pool=>({count:pool.length,exactText:new Set(pool.map(x=>x.stem+'\n'+x.question)).size,distinctModeDecision:new Set(pool.map(x=>x.mode+':'+x.decisionId)).size,correctPositions:[0,1,2,3,4].map(c=>pool.filter(x=>x.correct===c).length)}));assert(pools.every(x=>x.count===200&&x.exactText===200&&x.distinctModeDecision===200&&x.correctPositions.every(n=>n===40)),'Repeated within-pool decisions');const caseKeys=new Set(cases.map(x=>x.mode+':'+x.decisionId)),across=questions.filter(x=>caseKeys.has(x.mode+':'+x.decisionId));return {pools,crossSectionSharedConcepts:across.length,limitation:'Case and assessment repeat learning concepts; this is not400independentclinicalconditions.'};});
const numeric=[];
for(const item of all){const id=item.decisionId,m=new CardiacModel(item.mode,item.ecg.options),beats=m.between(0,8),pvc=/q140|qt410/.test(id)&&item.mode==='pvc',b=beats.find(b=>b.isPVC===pvc)||beats[0];let expected=null,kind='';if(/^q(80|140|160|180)$/.test(id)){expected=Math.round(b.qrs*1000);kind='ms';}else if(/^pr(L|R)?(175|140)$/.test(id)){expected=Math.round(b.pr*1000);kind='ms';}else if(/^qt(350|245|345|430|410)$/.test(id)){expected=Math.round(b.qt*1000);kind='ms';}else if(/^rr(800|360|380|400|500)$/.test(id)){expected=Math.round(60/b.rr);kind='/dk';}else if(id==='st32'){expected=+.32;kind='mV';assert(Math.abs(m.metrics(b.r+.1,'V3').st-expected)<1e-5,'ModelV3ST');}else if(id==='st20'){expected=+.20;kind='mV';assert(Math.abs(m.metrics(b.r+.1,'II').st-expected)<1e-5,'ModelIIST');}else if(id==='iii28'){expected=.28;kind='mV';}else if(id==='avf24'){expected=.24;kind='mV';}else if(id==='avl18'){expected=-.18;kind='mV';}else if(id==='inferiorAVR'){expected=-.06;kind='mV';}else if(id==='anteriorAVL'){expected=.06;kind='mV';}else if(id==='pToQR315'){expected=315;kind='ms';}else if(id==='pToQL335'){expected=335;kind='ms';}else if(id==='grid200'){expected=200;kind='ms';}else if(id==='pvcAverage'){expected=75;kind='/dk';}
 if(expected!==null){const correct=item.options[item.correct].replaceAll('−','-').replace(',','.');const match=correct.match(/[+-]?\d+(?:\.\d+)?/);numeric.push({id:item.id,mode:item.mode,decision:id,expected,correct,pass:!!match&&Math.abs(Number(match[0])-expected)<.001});}
}
await log.test('T04-T08-all-numeric-targets-model',()=>{assert(numeric.every(x=>x.pass),'Numeric mismatch '+numeric.filter(x=>!x.pass).map(x=>x.id));return {checked:numeric.length,rows:numeric};});
fs.writeFileSync(path.join(evidence,'all400-independent-inventory.json'),JSON.stringify(all.map(x=>({...x,review:{schema:'checked',numeric:numeric.find(n=>n.id===x.id)||null,clinicalValidation:'Not independently clinician validated'}})),null,2));
fs.writeFileSync(path.join(evidence,'all400-independent-review.tsv'),'id\tmode\tdecision\tobjective\tsources\tstem\ttask\tcorrect\n'+all.map(x=>[x.id,x.mode,x.decisionId,x.objectiveIds.join(','),x.sourceIds.join(','),x.stem,x.question,x.options[x.correct]].map(t=>t.replaceAll('\t',' ')).join('\t')).join('\n')+'\n');
console.log(JSON.stringify({tests:log.rows.length,failed:log.rows.filter(x=>x.status==='FAIL').map(x=>x.id)}));process.exitCode=log.rows.some(x=>x.status==='FAIL')?1:0;
