import fs from 'node:fs';import vm from 'node:vm';import {performance} from 'node:perf_hooks';import {webcrypto} from 'node:crypto';
const box={window:{crypto:webcrypto,CardAIScorm:{previousStatus:''}},TextEncoder};vm.createContext(box);for(const file of ['model.js','curriculum.js','state.js'])vm.runInContext(fs.readFileSync('cardai/'+file,'utf8'),box);const {CardAIModel:M,PulseState:P,PulseCurriculum:C}=box.window;const results=[];function check(name,pass,details){results.push({name,pass:!!pass,details});if(!pass)throw Error(name+': '+JSON.stringify(details));}
for(const mode of M.MODES){const model=new M.CardiacModel(mode);let residual=0;for(let t=0;t<4;t+=.003){const i=model.signal(t,'I'),ii=model.signal(t,'II');residual=Math.max(residual,Math.abs(ii-i-model.signal(t,'III')),Math.abs(model.signal(t,'aVR')+(i+ii)/2),Math.abs(model.signal(t,'aVL')-i+ii/2),Math.abs(model.signal(t,'aVF')-ii+i/2));for(const lead of M.LEADS)check('finite-'+mode+'-'+lead+'-'+t.toFixed(3),Number.isFinite(model.signal(t,lead)));}check('limb-'+mode,residual<1e-9,residual);
let phaseErrors=0;for(let t=0;t<2;t+=.01){const s=model.snapshot(t);if(s.eject!==s.mechanical.includes('ejeksiyon'))phaseErrors++;if(mode==='vf'&&(s.flow!==0||s.eject||s.electricalRate!==null))phaseErrors++;}check('phase-'+mode,phaseErrors===0,phaseErrors);
const started=performance.now();for(let i=0;i<50;i++)model.between(35998,36001);check('bounded-cache-'+mode,model.beats.length<100&&model.checkpoints.length<1200,{beats:model.beats.length,checkpoints:model.checkpoints.length,milliseconds:performance.now()-started});}
const right=new M.CardiacModel('rbbb');const rb=right.between(0,2)[0];for(const lead of ['I','V5','V6'])check('rbbb-lateral-T-'+lead,right.signal(rb.r+rb.tCenter,lead)>0);for(const lead of ['V1','V2'])check('rbbb-right-T-'+lead,right.signal(rb.r+rb.tCenter,lead)<0);
const pvc=new M.CardiacModel('pvc');const mixed=pvc.between(0,8);check('pvc-sinus80-and-early140',mixed.some(b=>!b.isPVC&&Math.round(b.qrs*1000)===80)&&mixed.some(b=>b.isPVC&&Math.round(b.qrs*1000)===140)&&mixed.every(b=>Math.round(b.qrs*1000)===(b.isPVC?140:80)));
const rapid=new M.CardiacModel('af',{afProfile:'rapid'});for(const b of rapid.between(1,20)){const before=rapid.snapshot(b.r-.00001),after=rapid.snapshot(b.r+.00001);check('rapid-AF-cavity-continuity-'+b.n,Math.abs(before.cavity-after.cavity)<.001,{before:before.cavity,after:after.cavity});}
check('horizon-safe',M.MODES.every(mode=>new M.CardiacModel(mode).between(36000,36010).every(b=>b.r<=36002)));
let maxBytes=0;for(let k=0;k<100;k++){const s=P.blank();for(const m of M.MODES)s.viewed[m]=16;for(const session of [s.caseSession,s.quizSession]){session.submitted.fill(true);session.answers=session.ids.map(id=>C.byId[id].correct);session.interactionIndices=session.ids.map((_,i)=>2147479900+i);}s.bestAttempt=JSON.parse(JSON.stringify(s.quizSession));s.bestCaseAttempt=JSON.parse(JSON.stringify(s.caseSession));s.learningMs=31536000000;Object.keys(s.features).forEach(key=>s.features[key]=99);M.MODES.forEach(m=>{for(let j=0;j<6;j++)s.checklist[m+':'+j]=true;});P.derive(s);const encoded=P.encode(s),serial=JSON.stringify(encoded);maxBytes=Math.max(maxBytes,new TextEncoder().encode(serial).length);const restored=P.decode(encoded);check('restore-score-'+k,restored.attemptScore===100&&restored.bestScore===100&&restored.passed);check('restore-sample-'+k,JSON.stringify(restored.quizSession.ids)===JSON.stringify(s.quizSession.ids));}
check('suspend-budget',maxBytes<=4096,maxBytes);
for(const raw of [null,[],{version:999},{version:6,m:.5,j:.5,k:-5,h:.5,c:{n:Array(10).fill(999),a:Array(10).fill(999),s:1023},b:{n:Array(10).fill(1),a:Array(10).fill(999),s:1023},y:{'<img onerror=alert(1)>':true},score:100,passed:true},...[1,2,3,4,5].map(version=>({version,currentCase:.5,activeLead:.5,viewed:{normal:Infinity},passed:true,score:100,caseCorrect:Array(50).fill(true),checklist:{bad:'<script>'}}))]){const s=P.decode(raw);check('malformed-'+JSON.stringify(raw).slice(0,60),s.currentCase===0&&s.activeLead===0&&s.bestScore===null&&!s.passed&&Object.keys(s.checklist).length===0);}
const all=[...C.cases,...C.questions],cross=[];for(const mode of M.MODES)for(const decision of new Set(all.filter(x=>x.mode===mode).map(x=>x.decisionId))){const matches=all.filter(x=>x.mode===mode&&x.decisionId===decision);if(matches.length>1)cross.push(matches.map(x=>x.id));}
fs.writeFileSync('qa/sol_state_model_results.json',JSON.stringify({checks:results.length,failed:results.filter(x=>!x.pass),maxSuspendBytes:maxBytes,crossPoolModeDecisionGroups:cross},null,2));fs.writeFileSync('qa/sol_item_inventory.json',JSON.stringify(all,null,2));console.log(JSON.stringify({checks:results.length,maxSuspendBytes:maxBytes,crossPoolModeDecisionGroups:cross.length}));
