import {chromium} from '/Users/ozankaraca/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';import fs from 'node:fs';
const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1366,height:768}}),results=[],errors=[];page.on('pageerror',e=>errors.push(e.message));function check(name,pass,details){results.push({name,pass:!!pass,details});if(!pass)throw Error(name+': '+JSON.stringify(details));}
// H5: acilis tam ekran onerisi modal oldugu icin #startSimulator tikini engeller; testler icin bastan kapat.
await page.addInitScript(()=>{try{localStorage.setItem('pulse.fsPromptDone','1');}catch{}});
try{await page.goto('http://127.0.0.1:8765/cardai/');await page.click('#startSimulator');if(await page.locator('#tutorialPanel').isVisible())await page.click('#tutorialSkip');await page.evaluate(()=>{for(const m of CardAIModel.MODES)CardAIController.state.viewed[m]=16;CardAIController.showView('case');});
const before=await page.evaluate(()=>CardAIScorm.activeMilliseconds);await page.waitForTimeout(1200);const after=await page.evaluate(()=>CardAIScorm.activeMilliseconds);check('visible-case-learning-time',after-before>1100,{before,after});
await page.click('#helpBtn');const modalStart=await page.evaluate(()=>CardAIScorm.activeMilliseconds);await page.waitForTimeout(850);const modalEnd=await page.evaluate(()=>CardAIScorm.activeMilliseconds);check('dialog-excludes-learning-time',modalEnd-modalStart<60,{modalStart,modalEnd});await page.click('#closeInfo');
const item=await page.evaluate(()=>CardAIController.getItem('case',0));await page.check('input[name="activeCase"][value="'+item.correct+'"]');await page.click('#caseCheck');check('correct-expand-visible',await page.locator('#caseExpand').count()===1);const ctx=await page.evaluate(()=>({sid:CardAIController.state.caseSession.id,id:CardAIController.getItem('case',0).id}));await page.click('#caseExpand');check('expand-correct-mode',await page.evaluate(()=>CardAIController.state.mode)===item.mode);await page.click('#returnToCaseBtn');check('return-exact-case-context',await page.evaluate(context=>CardAIController.state.currentCase===0&&CardAIController.state.caseSession.id===context.sid&&CardAIController.getItem('case',0).id===context.id&&CardAIController.state.caseSubmitted[0],ctx));
await page.evaluate(()=>{CardAIController.state.caseSession.submitted.fill(true);CardAIController.state.caseSession.answers=CardAIController.state.caseSession.ids.map(id=>PulseCurriculum.byId[id].correct);CardAIController.showView('quiz');});const qStart=await page.evaluate(()=>CardAIScorm.activeMilliseconds);await page.waitForTimeout(1100);const qEnd=await page.evaluate(()=>CardAIScorm.activeMilliseconds);check('visible-quiz-learning-time',qEnd-qStart>1000,{qStart,qEnd});
await page.evaluate(()=>CardAIController.persist());await page.reload();await page.click('#startSimulator');if(await page.locator('#tutorialPanel').isVisible())await page.locator('#tutorialSkip').click();const old=await page.locator('#quizEcgCanvas').evaluate(c=>({width:c.width,css:c.getBoundingClientRect().width,id:c.dataset.itemId}));await page.setViewportSize({width:1920,height:1080});await page.waitForTimeout(150);const resized=await page.locator('#quizEcgCanvas').evaluate(c=>({width:c.width,css:c.getBoundingClientRect().width,id:c.dataset.itemId}));check('quiz-reload-resize-redraw',resized.width>old.width&&resized.id===old.id,{old,resized});
await page.evaluate(()=>{CardAIController.showView('sim');CardAIController.setMode('vf');CardAIController.setPlaying(true);});await page.waitForTimeout(120);const positions=()=>page.evaluate(()=>[...document.querySelectorAll('#particles circle,.coronary-particle')].map(p=>[p.getAttribute('cx'),p.getAttribute('cy')]));const a=await positions();await page.waitForTimeout(750);const b=await positions();check('vf-all63-particles-stop',a.length===63&&JSON.stringify(a)===JSON.stringify(b),{count:a.length});check('five-metric-containers',await page.locator('.metrics>div').count()===5);check('footer-exact',await page.evaluate(()=>{const text=document.querySelector('#appRoot .eg-footer')?.textContent.replace(/\s+/g,' ').trim();return text==='EGEMED Pulse™ Etkileşimli EKG Simülatörü, Ege Üniversitesi Tıp Fakültesi Dekanlığı tarafından geliştirilmiştir. Tüm hakları saklıdır © 2026Sinyaller sentetiktir · klinik tanı için kullanılmaz';}));check('no-browser-errors',errors.length===0,errors);fs.writeFileSync('qa/sol_followup_results.json',JSON.stringify({results,errors},null,2));console.log(JSON.stringify({checks:results.length,errors}));}finally{await browser.close();}
