import { chromium } from '/Users/ozankaraca/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import fs from 'node:fs';
const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1366,height:768}});const errors=[];page.on('pageerror',e=>errors.push(e.message));const results=[];
function check(name,value,details){results.push({name,pass:!!value,details});if(!value)throw Error(name+': '+JSON.stringify(details));}
try{
await page.goto('http://127.0.0.1:8765/cardai/');await page.waitForTimeout(600);check('load-no-errors',errors.length===0,errors);
const curriculum=await page.evaluate(()=>{const p=PulseCurriculum,all=[...p.cases,...p.questions];return {cases:p.cases.length,questions:p.questions.length,ids:new Set(all.map(x=>x.id)).size,valid:all.every(x=>x.options.length===5&&new Set(x.options).size===5&&x.explanations.length===5&&x.sourceIds.length&&x.objectiveIds.length),answers:all.reduce((a,x)=>(a[x.correct]++,a),[0,0,0,0,0])};});check('400-item-schema',curriculum.cases===200&&curriculum.questions===200&&curriculum.ids===400&&curriculum.valid,curriculum);
await page.click('#startSimulator');if(await page.locator('#tutorialPanel').isVisible())await page.click('#tutorialSkip');await page.click('.mode-card.learn .btn');await page.click('.rhythm-tab[data-mode="af"]');await page.selectOption('#speed','2');await page.click('#playBtn');await page.waitForTimeout(16350);
const watched=await page.evaluate(()=>({seconds:CardAIController.state.viewed.af,normal:CardAIController.state.viewed.normal,time:CardAIController.state.time}));check('trusted-real16-at2x',watched.seconds===16&&watched.normal===0,watched);
await page.evaluate(()=>CardAIController.persist());const savedIds=await page.evaluate(()=>[CardAIController.state.caseSession.ids,CardAIController.state.quizSession.ids]);await page.reload();await page.waitForTimeout(300);await page.click('#startSimulator');check('resume-paused',await page.evaluate(()=>!CardAIController.playing));check('samples-preserved',JSON.stringify(savedIds)===JSON.stringify(await page.evaluate(()=>[CardAIController.state.caseSession.ids,CardAIController.state.quizSession.ids])));
await page.evaluate(()=>{CardAIController.setMode('pvc');CardAIController.setPlaying(true);});await page.waitForTimeout(650);check('programmatic-no-observation',await page.evaluate(()=>CardAIController.state.viewed.pvc===0));
await page.evaluate(()=>{CardAIController.setPlaying(false);for(const m of CardAIModel.MODES)CardAIController.state.viewed[m]=16;CardAIController.progress();});await page.evaluate(()=>CardAIController.showView('case'));
check('open-access-with-hints',await page.evaluate(()=>{CardAIController.showView('modes');const card=document.querySelector('.mode-card.assessment');return !card.classList.contains('locked')&&card.querySelector('.btn').dataset.view==='quiz'&&card.querySelector('.mode-status').textContent.includes('Öneri:');}));
await page.evaluate(()=>CardAIController.showView('case'));
for(let i=0;i<10;i++){
const item=await page.evaluate(()=>CardAIController.getItem('case',CardAIController.state.currentCase));await page.waitForTimeout(30);check('case-ecg-'+i,await page.getAttribute('#caseEcgCanvas','data-item-id')===item.id);
if(i===0){const chip=page.locator('.lead-chip[data-question-lead="case"][data-column="0"][data-lead="III"]');await chip.click();check('case-lead-controls',await page.getAttribute('#caseEcgCanvas','data-leads')?.then(s=>s.startsWith('III')));check('no-preanswer-expand',await page.locator('#caseExpand').count()===0);}
await page.check('input[name="activeCase"][value="'+((item.correct+1)%5)+'"]');await page.click('#caseCheck');check('wrong-no-expand-'+i,await page.locator('#caseExpand').count()===0);if(i<9)await page.click('#caseNext');}
check('assessment-open-after-cases',await page.evaluate(()=>{CardAIController.showView('modes');const card=document.querySelector('.mode-card.assessment');return !card.classList.contains('locked')&&!card.querySelector('.mode-status').textContent.includes('Öneri:');}));await page.click('.mode-card.assessment .btn');
for(let i=0;i<10;i++){const item=await page.evaluate(()=>CardAIController.getItem('quiz',CardAIController.state.quizPage));await page.waitForTimeout(30);check('quiz-ecg-'+i,await page.getAttribute('#quizEcgCanvas','data-item-id')===item.id);await page.check('input[name="q'+i+'"][value="'+(i<8?item.correct:(item.correct+1)%5)+'"]');if(i<9)await page.click('#quizNext');}
await page.click('#checkBtn');await page.waitForTimeout(180);const grade=await page.evaluate(()=>({attempt:CardAIController.state.attemptScore,best:CardAIController.state.bestScore,passed:CardAIController.state.passed}));check('grade-eight-is80',grade.attempt===80&&grade.best===80&&grade.passed,grade);
const old=await page.evaluate(()=>CardAIController.state.quizSession.ids);await page.click('#resultsNew');const fresh=await page.evaluate(()=>({ids:CardAIController.state.quizSession.ids,attempt:CardAIController.state.attemptScore,best:CardAIController.state.bestScore,passed:CardAIController.state.passed}));check('new-quiz-distinct-clears-attempt-keeps-best',JSON.stringify(old)!==JSON.stringify(fresh.ids)&&fresh.attempt===null&&fresh.best===80&&fresh.passed,fresh);
check('final-no-errors',errors.length===0,errors);
fs.writeFileSync('qa/sol_core_results.json',JSON.stringify({results,errors},null,2));console.log(JSON.stringify({passed:results.length,errors},null,2));
}finally{await browser.close();}
