import {chromium} from '/Users/ozankaraca/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import fs from 'node:fs';
const out=new URL('./evidence/sol-ui/',import.meta.url);fs.mkdirSync(out,{recursive:true});
const report={kind:'Real Chromium UI measurements',date:new Date().toISOString(),rows:[],errors:[]};
const browser=await chromium.launch({headless:true});
const page=await browser.newPage();page.on('pageerror',e=>report.errors.push(e.message));
// H5: acilis tam ekran onerisi modal oldugu icin #startSimulator tikini engeller; testler icin bastan kapat.
await page.addInitScript(()=>{try{localStorage.setItem('pulse.fsPromptDone','1');}catch{}});
function rgb(hex){return hex.match(/[a-f\d]{2}/gi).map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4)}
function contrast(a,b){const lum=x=>{const c=rgb(x);return c[0]*.2126+c[1]*.7152+c[2]*.0722};const l=[lum(a),lum(b)].sort((a,b)=>b-a);return(l[0]+.05)/(l[1]+.05)}
report.contrast={primaryWhite:contrast('087493','ffffff'),focusWhite:contrast('065a80','ffffff'),bodyWhite:contrast('405f71','ffffff'),bodyTint:contrast('405f71','e3eff4')};
for(const [width,height] of [[1366,768],[1920,1080],[390,844],[768,1024]]){
 await page.setViewportSize({width,height});await page.goto('http://127.0.0.1:8765/cardai/');if(await page.locator('#startSimulator').isVisible())await page.locator('#startSimulator').click();if(await page.locator('#tutorialPanel').isVisible())await page.locator('#tutorialSkip').click();await page.evaluate(()=>CardAIController.showView('sim'));await page.waitForTimeout(180);
 for(const mode of ['normal','af']){
  await page.locator(`.rhythm-tab[data-mode=${mode}]`).click();await page.waitForTimeout(180);await page.evaluate(()=>scrollTo(0,0));
  const data=await page.evaluate(()=>{const rect=x=>x.getBoundingClientRect().toJSON();const rail=document.querySelector('.rhythm-tabs');const rr=rect(rail);return{viewport:{width:innerWidth,height:innerHeight},pageWidth:document.documentElement.scrollWidth,pageHeight:document.documentElement.scrollHeight,rail:rr,cards:[...rail.children].map(x=>({mode:x.dataset.mode,rect:rect(x),client:x.clientHeight,scroll:x.scrollHeight})),fonts:Object.fromEntries(['.summary-text','.lead-choice span','.metrics small','.metrics strong','.pulse-note','.rhythm-tab small','.layer-menu label'].map(s=>[s,getComputedStyle(document.querySelector(s)).fontSize])),groups:[...document.querySelectorAll('.lead-choice')].map(x=>({rect:rect(x),select:rect(x.querySelector('select'))})),af:rect(document.querySelector('#afProfile')),afVisible:!document.querySelector('#afProfile').hidden,ecg:rect(document.querySelector('#ecgCanvas')),metrics:[...document.querySelectorAll('.metrics>div')].map(x=>({rect:rect(x),client:x.clientHeight,scroll:x.scrollHeight})),transport:rect(document.querySelector('.transport')),minFont:Math.min(...[...document.querySelectorAll('#appRoot *')].filter(x=>x.firstChild?.nodeType===3&&x.firstChild.textContent.trim()&&x.getBoundingClientRect().width&&getComputedStyle(x).display!=='none'&&!(x instanceof SVGElement)).map(x=>parseFloat(getComputedStyle(x).fontSize)))};});
  report.rows.push({id:`${width}-${mode}`,data});console.log(width,mode,data.pageWidth,data.pageHeight,data.minFont);await page.screenshot({path:new URL(`${width}-${mode}.png`,out).pathname,fullPage:true});
  if(mode==='af'){await page.locator('#afProfile').selectOption('rapid');await page.locator('#afProfile').selectOption('controlled');}
 }
 for(const focus of ['anatomy','ecg','explanation']){await page.locator(`[data-focus-panel=${focus}]`).click();await page.waitForTimeout(90);report.rows.push({id:`${width}-focus-${focus}`,data:await page.evaluate(()=>({focus:document.querySelector('#appRoot').dataset.focus,pageWidth:document.documentElement.scrollWidth}))});await page.locator(`[data-focus-panel=${focus}]`).click();}
 if(width>1000){await page.locator('#fullscreenBtn').click();await page.locator('#helpBtn').click();report.rows.push({id:`${width}-fullscreen-modal`,data:await page.evaluate(()=>({fullscreen:document.fullscreenElement?.id,modal:document.querySelector('#infoDialog').getBoundingClientRect().toJSON(),close:document.querySelector('#closeInfo').getBoundingClientRect().toJSON()}))});await page.screenshot({path:new URL(`${width}-fullscreen-modal.png`,out).pathname});await page.locator('#closeInfo').click();await page.evaluate(()=>document.exitFullscreen());}
 await page.evaluate(()=>{const C=CardAIController;for(const m of CardAIModel.MODES)C.state.viewed[m]=16;C.state.caseSession.ids.forEach((id,i)=>{C.state.caseSession.answers[i]=PulseCurriculum.byId[id].correct;C.state.caseSession.submitted[i]=true});C.progress();});
 for(const section of ['case','quiz']){await page.evaluate(()=>CardAIController.showView('modes'));await page.locator(`.mode-card.${section==='case'?'practice':'assessment'} .btn`).click();await page.waitForTimeout(80);await page.screenshot({path:new URL(`${width}-${section}.png`,out).pathname,fullPage:true});report.rows.push({id:`${width}-${section}`,data:await page.evaluate(section=>{const c=document.querySelector(`#${section}EcgCanvas`),w=c.closest('.case-ecg-wrap');return{pageWidth:document.documentElement.scrollWidth,canvas:c.getBoundingClientRect().toJSON(),wrap:w.getBoundingClientRect().toJSON(),scrollWidth:w.scrollWidth};},section)});}
}
await browser.close();fs.writeFileSync(new URL('report.json',out),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
